### ISSUE TITLE
Can't add related item

### ISSUE THREAD

**Issue by JannieT** [directus/app#1844] opened 2019-07-12 08:17 UTC
Editing an item with a O2M relationship seems broken.

![screenshot](https://user-images.githubusercontent.com/5163423/61113147-cdb44c00-a48d-11e9-8bf1-0e2bcfa1ca3a.png)

**Steps to reproduce**

1. Add a M2O field called storyline to a collection of stories.
2. Add a M2O alias field called stories to the storyline collection.
3. Add a storyline item and select some stories that relate to it.
4. Hit the save button

**Expected result**

The storyline item will be saved and I return to the Storylines index page

**What actually happened**

Item was not saved and I get a validation error:

```
{
  "request": {
    "bodySize": 31,
    "method": "PATCH",
    "url": "http://directus.dv/_/items/storylines/1?fields=%2A.%2A.%2A.%2A",
    "httpVersion": "HTTP/1.1",
    "headers": [
      {
        "name": "Host",
        "value": "directus.dv"
      },
      {
        "name": "User-Agent",
        "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0"
      },
      {
        "name": "Accept",
        "value": "application/json, text/plain, */*"
      },
      {
        "name": "Accept-Language",
        "value": "af,en-US;q=0.7,en;q=0.3"
      },
      {
        "name": "Accept-Encoding",
        "value": "gzip, deflate"
      },
      {
        "name": "Referer",
        "value": "http://directus.dv/admin"
      },
      {
        "name": "Content-Type",
        "value": "application/json;charset=utf-8"
      },
      {
        "name": "Authorization",
        "value": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTYyOTE4MDE2LCJ0eXBlIjoiYXV0aCIsImtleSI6Ijx0eXBlLWEtcHVibGljLWF1dGhlbnRpY2F0aW9uLWtleS1zdHJpbmc-IiwicHJvamVjdCI6Il8ifQ.Cvxufapo-0ASc03ezA83B6XMXjCTnOipdwbz4CTDidY"
      },
      {
        "name": "Content-Length",
        "value": "31"
      },
      {
        "name": "Connection",
        "value": "keep-alive"
      },
      {
        "name": "Cookie",
        "value": "PHPSESSID=qf35tad0r792jg3s57osivfi74"
      },
      {
        "name": "Pragma",
        "value": "no-cache"
      },
      {
        "name": "Cache-Control",
        "value": "no-cache"
      }
    ],
    "cookies": [
      {
        "name": "PHPSESSID",
        "value": "qf35tad0r792jg3s57osivfi74"
      }
    ],
    "queryString": [
      {
        "name": "fields",
        "value": "*.*.*.*"
      }
    ],
    "headersSize": 752,
    "postData": {
      "mimeType": "application/json;charset=utf-8",
      "params": [],
      "text": "{\"stories\":[{\"id\":2},{\"id\":3}]}"
    }
  },
  "response": {
    "status": 422,
    "statusText": "Unprocessable Entity",
    "httpVersion": "HTTP/1.1",
    "headers": [
      {
        "name": "Server",
        "value": "nginx/1.12.0"
      },
      {
        "name": "Date",
        "value": "Fri, 12 Jul 2019 07:42:48 GMT"
      },
      {
        "name": "Content-Type",
        "value": "application/json"
      },
      {
        "name": "Content-Length",
        "value": "115"
      },
      {
        "name": "Connection",
        "value": "keep-alive"
      },
      {
        "name": "X-Powered-By",
        "value": "PHP/7.2.7"
      },
      {
        "name": "Access-Control-Allow-Origin",
        "value": "*"
      }
    ],
    "cookies": [],
    "content": {
      "mimeType": "application/json",
      "size": 115,
      "text": "{\"error\":{\"code\":4,\"message\":\"headline: This value should not be blank. article: This value should not be blank.\"}}"
    },
    "redirectURL": "",
    "headersSize": 230,
    "bodySize": 345
  },
  "cache": {},
  "timings": {
    "blocked": 4,
    "dns": 0,
    "connect": 0,
    "ssl": 0,
    "send": 0,
    "wait": 113,
    "receive": 0
  },
  "time": 117,
  "_securityState": "insecure",
  "serverIPAddress": "127.0.0.1",
  "connection": "80"
}

```

**Comment by benhaynes** [comment] 2019-07-12 14:16
I believe this is a duplicate, but I'll let @rijkvanzanten decide that.

Also, we're planning to fix this issue today! Thanks for reporting it @JannieT! 😄

**Comment by rijkvanzanten** [comment] 2019-07-12 14:28
This is a duplicate of https://github.com/directus/app/issues/1798

**Closed by rijkvanzanten** 2019-07-12 14:28 UTC
Labels: bug

**Comment by rijkvanzanten** [comment] 2019-07-12 14:29
I believe this was fixed in https://github.com/directus/api/issues/1072
