### ISSUE TITLE
User with only one collection logged in display blank left menu

### ISSUE THREAD

**Issue by dickyj** [directus/app#2872] opened 2020-06-14 10:37 UTC
Hi,
Great app here, reporting a bug, as a result, the user cannot log out.

• directus/directus:v8.7.2-apache
• Ubuntu

`vue.runtime.esm.js:1888 TypeError: Expected a string
    at f (format-title.umd.js:1)
    at Object.formatTitle (format-title.umd.js:1)
    at Object.As [as formatCollection] (format-collection.js:4)
    at nav-sidebar.vue:114
    at Array.map (<anonymous>)
    at nav-sidebar.vue:107
    at Array.map (<anonymous>)
    at a.customCollections (nav-sidebar.vue:104)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.evaluate (vue.runtime.esm.js:4584)`

Steps to Reproduce:
Login as user with read only access to one collection, and the error happens.

![Screenshot (274)_LI](https://user-images.githubusercontent.com/6478334/84591071-addb9400-ae65-11ea-9213-551b4357b2ec.jpg)

**Comment by dickyj** [comment] 2020-06-14 11:14
Saw this issue, apparently still not fixed yet...
https://github.com/directus/app/issues/2344

**Comment by rijkvanzanten** [comment] 2020-06-18 19:51
@dickyj The OP never got back on #2344 unfortunately. Are you able to accurately reproduce this @dickyj? What steps did you take when this started happening?

**Comment by rijkvanzanten** [comment] 2020-06-18 19:51
Duplicate of #2344

**Closed by rijkvanzanten** 2020-06-18 19:51 UTC

**Comment by dickyj** [comment] 2020-06-19 01:35
> @dickyj The OP never got back on #2344 unfortunately. Are you able to accurately reproduce this @dickyj? What steps did you take when this started happening?

Hi, the problem can be reproduced all the time, in fact its a blocker right now coz we cannot use the application due to this. Do you have an issue tracking system? I can give you the credentials, its a demo site with no confidential data. You can access it publicly. This system has good potential and as an enterprise we may want to adopt it.

**Comment by rijkvanzanten** [comment] 2020-06-19 13:26
By reproducing I mean, what steps do I have to take to get to that point, and does it happen every time you do those steps.

> Do you have an issue tracking system?

You're on it right now!

**Comment by benhaynes** [comment] 2020-06-19 14:34
Hey @dickyj — you can also privately provide us creds to the server via our Slack channel: https://directus.chat

**Comment by benhaynes** [comment] 2020-06-22 14:55
Thank you for the credentials, @dickyj — however those creds are for the user that doesn't work, so there's no way for us to verify your permissions/interfaces are configured properly. Both this issue and #2344 have not provided enough information for us to debug, so there's not much else we can do at this point. 

I'm almost certain that this is a configuration issue somewhere in your Settings. Chances are you only gave that Role access to ONE collection... and in doing so, also removed access to all the system collections (eg: `directus_users`). There are default system collections set when you create a role, and in v8 (will be different in v9) you can not just remove all these and still have the App work. Directus and all roles need access to certain system collections to write activity logs, access user info, etc. That seems to be the issue here.
