### ISSUE TITLE
Weird irreversible error after changing the logo

### ISSUE THREAD

**Issue by judehunter** [directus/app#1587] opened 2019-05-06 00:25 UTC
# Bug Report

I wanted to change the logo in the global settings, but after I do, the logo is just the missing image icon, and I can't change the logo again (the options under the logo sections vanished). Also I get the errors:
`vue.runtime.esm.js:1888 TypeError: Cannot read property 'full_url' of undefined
    at a.created (logo.vue:37)`
and
`TypeError: Cannot read property 'split' of undefined
    at a.subtitle (input.vue:116)`
that are probably related to the logo. The src attrinute in the logo's `<img>` element is `(unknown)`

Is there a manual way of reverting this error?

## Steps to Reproduce

1. Go to Global Settings
2. Click on the desktop icon to upload the image
3. After refreshing the logo is missing

## Expected Behavior
Logo should be set without errors

## Actual Behavior
Weird vanishing of the logo options and logo is now missing with `src(unknown)`

## Technical Details

- Device: desktop
- OS: win10
- Browser: chrome@latest
- Directus App: latest
- Directus API: latest
- Install Method: cloned `master` branch of `directus/directus`

## Screenshots
![image](https://user-images.githubusercontent.com/32528507/57202526-b137f700-6fa6-11e9-9ba1-ac1cd358d091.png)
![image](https://user-images.githubusercontent.com/32528507/57202544-c4e35d80-6fa6-11e9-8041-789019c4781f.png)

**Comment by Lapsus** [comment] 2019-05-06 06:12
go to the database directly. look at table `directus_settings` remove the `value` on the key `logo`
or in sql terms 
```
UPDATE directus_settings SET value='' WHERE `key` = 'logo';
```
At least this makes the settings operational again. It does not fix your problem which should be a configuration issue. Please check that api.php has the correct entries in section `storage`. You can verify the urls manually in your browser. If you get the image and thumbnail there, it should work in the app as well.

**Comment by diegogurpegui** [comment] 2019-05-06 20:01
I can confirm this issue happens to me as well.
I could successfully upload images to Directus, and I also could successfully consume those files thru API. There seems to be a problem specifically with the App Logo.

**Comment by rijkvanzanten** [comment] 2019-05-06 20:10
@bjgajjar Did your change in the datatype casting from / to a directus_files object potentially cause this?

I'm suspecting that the API doesn't return the correct object format for files in settings.

**Comment by Lapsus** [comment] 2019-05-08 15:19
@rijkvanzanten you were right on this one. The api did indeed return just the id of the file but not the correct object format. If fixed this and sent the pr to the api.

**Comment by diegogurpegui** [comment] 2019-05-08 15:29
@Lapsus that is what usually happens when you query an item that has a File field (hence, a second level item). But if you indicate that you want second level fields (ie: "*.*") you'll get the entire File object. Am I right?
That is what we've been doing and seems fine.

**Comment by Lapsus** [comment] 2019-05-08 15:36
@diegogurpegui i am not shure i understand what you do.

What happens when you upload a file and use it as custom logo for your App is described in the bug report above. The global settings form is kind of broken and the custom logo does not work as well.

This happens because after storing the settings, the settings endpoint does not provide the "correct" data structure. I fixed this for the settings endpoint and solved the problem described above and also got the custom app logo working (which was mentioned in a few other issues i am not able to find).

**Comment by diegogurpegui** [comment] 2019-05-08 16:39
@Lapsus what I mean is that if you query an item from the API, that has a file field, it will be returned like this:
```
{
  id: 123,
  someField: "Test",
  oneFile: 3,  // being this the ID of the file
}
```

But if you specificy the fields you want to receive with something like "*.*" such as:
`http://api.../items/yourtable/123?fields=*.*`
You will get this:
```
{
  id: 123,
  someField: "Test",
  oneFile: {
    id: 3,
    full_url: "....",
    url: "....",
    ...
  }
}
```
More info here: https://docs.directus.io/api/reference.html#fields

To sum up: if you only get the ID of the file instead of the rest of the fields, I believe that is how the API is supposed to work. You need to specify what you want by query parameters.

**Comment by diegogurpegui** [comment] 2019-05-08 16:40
I don't want to diverge from the main issue here.
So, perhaps the problem is related to this "field" feature I mentioned and needs to be fixed from the Vue.js side?

**Comment by Lapsus** [comment] 2019-05-08 18:05
@diegogurpegui thanks for the clarification. 

The problem is on https://docs.directus.io/api/reference.html#settings and for this endpoint you dont have the fields parameter available.

**Comment by am-webdev** [comment] 2019-05-10 07:15
For me, it is even not possible to change the logo. While saving, an error is shown on the Admin UI:

`Attempting to write an array as the value for field "value" in "directus_settings"`

It happened for files from my OS and for images from URL as well. 

The Image it self was uploaded, I can browse and view it on the file library. Due to the error on save, I don't be able to reproduce the behavior described above.

**Comment by cnotethegr8** [comment] 2019-05-13 04:13
@am-webdev I too was using the latest docker image and experienced the problem you mentioned. Upon further investigation I realised the docker image hasn't been update in a few months and is pretty outdated. The bug you're experiencing doesn't exist anymore in the latest code. 

However I am also getting the bug described in this ticket.

**Comment by Nitwel** [comment] 2019-05-30 08:44
@rijkvanzanten this can be closed because fix: directus/api#940 is already merged.

**Comment by rijkvanzanten** [comment] 2019-05-30 19:45
Perfect. Thanks for the heads up 😄

**Comment by anelad** [comment] 2019-07-05 11:23
> @rijkvanzanten this can be closed because fix: [directus/api#940](https://github.com/directus/api/pull/940) is already merged.

I'm still having the issue :/ Cloned the repo 3 or 4 days ago.

**Comment by benhaynes** [comment] 2019-07-05 14:35
Hmm, I'll re-open this for visibility...

**Comment by theharshin** [comment] 2019-08-09 06:18
@anelad I'm not able to reproduce the issue. Did you tried with another image?
Please make sure you have:
- Latest App Build.
- Latest API Build.
- The database schema is updated. (You can do it from: Admin Settings > Update Database )

If the issue still persist, kindly share the database dump and more information on how to reproduce the issue.

**Comment by anelad** [comment] 2019-08-09 13:14
Yes, I tried with other images with different kinds. My builds' are up-to-date as well as DB schema.

**Comment by benhaynes** [comment] 2019-08-09 13:27
The dump (and any other details) will certainly help us get this resolved. Did you try performing the same thing on the demo? If the demo works it will at least rule out a few things as the root problem.

**Comment by anelad** [comment] 2019-08-09 13:41
The same issue occurs on the demo app too.

**Comment by benhaynes** [comment] 2019-08-09 13:53
Could you perhaps Slack us the image you're using too, there's always a chance it's corrupt or there's is some other issue specific to the file.

https://directus.chat

**Comment by anelad** [comment] 2019-08-09 13:56
There is no need, I've just tried the demo app with the existing images in it. There is no chance that all the images are corrupted.

P.S. I'm already in the Slack team. I will say hello to you now.

**Comment by benhaynes** [comment] 2019-08-09 14:00
@theharshin @bjgajjar — if this is reproducible on the demo then it should be easier to find the problem and fix.

**Comment by theharshin** [comment] 2019-08-30 06:37
@benhaynes @anelad Actually, I'm not able to reproduce this on local or https://directus.app 😕
Any hint to reproduce this will help me to get started to fix @anelad

**Comment by benhaynes** [comment] 2019-08-30 14:19
Hey @anelad — I am also able to upload images to the demo app/api without any issues. Could you please give the specific steps you're taking (drag and drop image, versus select from computer, etc)... and any browser info that may be relevant?

Here is my source image: (PNG with alpha layer, 196px by 36px) Can't see it because it's white-on-white.
<img src="https://user-images.githubusercontent.com/522079/64027590-01ffcc80-cb0f-11e9-9d99-0c2f2e9e2b0a.png">

And here is the result from dropping this onto the Global Settings `logo` field:
![Screen Shot 2019-08-30 at 10 15 34 AM](https://user-images.githubusercontent.com/522079/64027647-25c31280-cb0f-11e9-9ed2-114cb14cf100.png)

I'm going to close this issue (for now) since it's definitely working in the latest release. I'm very confused as to why this isn't working for you (especially since you're using the demo too!).

**Closed by benhaynes** 2019-08-30 14:20 UTC
Labels: bug

**Comment by anelad** [comment] 2019-08-30 15:55
I've tried now again, and it works.
