### ISSUE TITLE
Error saving M2M relationship when collection has files

### ISSUE THREAD

**Issue by mrtrombone** [directus/app#2595] opened 2020-02-10 21:22 UTC
I have a collection that has an M2M relationship with itself (e.g. a person has a friend relationship with other persons)
When I try to add a relationship  for an item I am able to select however when I save I get error message below.
Collection has a file collection field (e.g. photos). This is what is causing the problem. Removing all files from the item solves the problem but of course I want to be able to add files to my item.
Running the SQL on the DB directly reports that 'data' is not a known field for the collection so for some reason the SQL being build is trying to update the 'data' field.

On the surface the issue sounds similar to [2042](https://github.com/directus/app/issues/2042) however the symptoms (being SQL) seems different.
Also worth noting that the files have not been changed at all so ideally no update would even occur - no diffing is occurring which seems nonsensical

**Directus version:** 8.5.4 (Digital Ocean Droplet)

**message:** "Failed generating the SQL query."
**query:** 

```
UPDATE `directus_files` 
SET 
  `id` = '19',
  `storage` = 'local',
  `private_hash` = 'i92zcyczy1w0sggo',
  `filename_disk` = '959e7849-79e1-4860-8081-bbc38177ff05.png',
  `filename_download` = 'merlotcabsauv-496x1540px-bottle.png',
  `title` = ' Merlotcabsauv 496x1540px Bottle',
  `type` = 'image/png',
  `uploaded_by` = '1',
  `uploaded_on` = '2020-02-10 04:05:59',
  `charset` = 'binary',
  `filesize` = '150956',
  `width` = '496',
  `height` = '1540',
  `duration` = '0',
  `embed` = NULL,
  `folder` = NULL,
  `description` = '',
  `location` = '',
  `tags` = '',
  `checksum` = '6732e95580656730c95e58a97228307f',
  `metadata` = NULL,
  `data` = NULL <<<<<<<<<<<<<<<<<<<<<<<<<<
WHERE 
  `id` = '19'
```

**related mysql error:** unknown column data in field list

**Steps to reproduce:**
1. Create collection with File collection field.
2. Modify collection to have M2M relationship with itself
3. Create item A, add file to file collection
4. Create another item B
5. Modify item B to have relationship with item A

**Comment by pgegenfurtner** [comment] 2020-02-11 10:00
I'm having the same issue. 

When creating the relationship directly via the api, only sending the id of the related items that should be added, it works. It's my current (annoying) workaround.

**Comment by rijkvanzanten** [comment] 2020-02-11 15:07
You're right in saying it's similar to 2042. The interface doesn't know what data to send for each field type, so it sends everything instead of just the ID. We can't just diff on the changed value either, as that would break support for nested JSON in a relational interface (f.e. repeaters / key values etc). 

I'll close this as a duplicate of #2042

**Closed by rijkvanzanten** 2020-02-11 15:07 UTC
