### ISSUE TITLE
Feature request. Collections. Custom in-browser cross-field validation for collection. 

### ISSUE THREAD

**Issue by alex-gorovyi** [directus/app#1430] opened 2019-03-28 05:12 UTC
# Feature Request
Custom in-browser cross-field validation for collection. 

## What problem does this feature solve?
This feature would solve in-browser validation for editing/adding item into a collection, when such custom cross-field validation is required.

If i am not mistaken, currently that kind of validations can be implemented on the PHP side?

Example: Collection has a field that is of `file` interface and another field of `checkbox` interface. File cannot be empty if checkbox is checked, but can be empty if the checkbox is not checked.

## How do you think this should be implemented?
Not sure. My level of understanding of Directus App is that HTML5 client-side validations per-field (incl. RegEx) are available, but the scope of the validations is limited to a single field. 

I think somehow the validations could be added as part of collection's meta data OR as part of per-field "Validations" section: by adding a dependant field name/s and validation rule/s for "master" field/s.

## Would you be willing to work on this?
Yes, if the feature is required and core team members point the direction how this could be implemented.

**Comment by rijkvanzanten** [comment] 2019-03-28 18:59
I think this is a duplicate of https://github.com/directus/app/issues/763

**Closed** 2019-04-22 20:18 UTC
Labels: duplicate
