### ISSUE TITLE
Files Interface: post / patch request payload empty

### ISSUE THREAD

**Issue by pgegenfurtner** [directus/app#2313] opened 2019-12-10 18:05 UTC
In 8.2.0 the files interface does not work anymore.

I have a collection with a files interface.
When I upload new files, (they get uploaded) and click save in the dialog console errors are appearing: 
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'startsWith' of undefined
    at a (get-icon.js:6)
    at c.icon (display.vue:30)
    at an.get (vue.runtime.esm.js:4473)
    at an.evaluate (vue.runtime.esm.js:4578)
    at c.icon (vue.runtime.esm.js:4830)
    at c.a (display.vue?1e1b:1)
    at c.e._render (vue.runtime.esm.js:3542)
    at c.n (vue.runtime.esm.js:4060)
    at an.get (vue.runtime.esm.js:4473)
    at an.run (vue.runtime.esm.js:4548)
    at $i (vue.runtime.esm.js:4304)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at la (vue.runtime.esm.js:1906)
```

No file titles are being shown.
When I try to save the collection, I get an error

```
filename_disk: This value should not be blank. uploaded_on: This value should not be blank. filename_download: This value should not be blank.
```

When I look at the network request, the payload of the files is empty:

```
{
  "header_images": [
    {
      "file": {}
    },
    {
      "file": {}
    },
    {
      "file": {}
    }
  ]
}
```

**Comment by rijkvanzanten** [comment] 2019-12-10 19:41
Duplicate of https://github.com/directus/app/issues/2308

**Closed** 2019-12-10 19:41 UTC
Labels: duplicate
