### ISSUE TITLE
Many-to-One Interface Bug

### ISSUE THREAD

**Issue by Pujan789556** [directus/app#1251] opened 2019-01-14 09:39 UTC
# Bug Report

I got problem with Many 2 One field
It is showing the dropdown for 10 related collection.
If there is more than 10 data in the related collection, there is  nothing in dropdown.

## Steps to Reproduce

1. Create a new collection called pages
2. Add 10 data in pages collection
3. Create another collection called themes
4. Add M2O field on theme with related collection as pages.
5. Display {{page_name}}
6. Add data to collection themes
7. Add one more data to collection pages.
8. Try to add another data on collection themes.

## Expected Behavior
List all 11 data of pages in drop down

## Actual Behavior
Nothing in dropdown or dropdown not clickable.

## Technical Details

- Device: Desktop
- OS: Ubuntu 16.04
- Web Server: Apache
- PHP Version:  7.2.0
- Database:  MySQL 8.0.12
- Install Method: Directus Suit

**Comment by rijkvanzanten** [comment] 2019-01-16 19:09
I think this is a duplicate of #1250

**Closed by rijkvanzanten** 2019-01-16 19:09 UTC
Labels: bug

**Comment by Pujan789556** [comment] 2019-01-24 10:23
I think this is not solved in v7.0.15.

**Comment by Pujan789556** [comment] 2019-01-24 10:24
I am still having the same issue. M2O with more than 10 items is appearing in different modal rather than drop down.

**Comment by Pujan789556** [comment] 2019-01-24 10:38
![screenshot from 2019-01-24 16-10-09](https://user-images.githubusercontent.com/10183860/51672733-4e70b000-1ff4-11e9-9047-a819716ec43f.png)

![screen shot 2019-01-24 at 4 15 17 pm](https://user-images.githubusercontent.com/10183860/51672758-5d576280-1ff4-11e9-9fc8-73fbfb82a0c0.png)


![screenshot from 2019-01-24 16-14-51](https://user-images.githubusercontent.com/10183860/51672752-592b4500-1ff4-11e9-8bf8-7903a3713dfd.png)

**Comment by rijkvanzanten** [comment] 2019-01-24 14:16
That's expected behavior @Pujan789556. When there's too many items to be easily usable in a regular dropdown, we switch to the modal so it's easier to explore the data

**Comment by benhaynes** [comment] 2019-01-24 14:36
We should update that default threshold to a few hundred. Countries, for instance, should all fit in a dropdown.

**Comment by Pujan789556** [comment] 2019-01-25 05:43
@benhaynes Yes, the threshold should be more (at least few hundred). My thought is modal with those colums and a checkbox (looks like multiple select) is not good UX.

**Comment by benhaynes** [comment] 2019-01-25 18:04
We're re-using the main item listing component (which is why the checkboxes are there), but I agree that if you can only select ONE item that the checkboxes are a bit confusing. 

Thoughts @rijkvanzanten ?
