### ISSUE TITLE
Backup and restore

### ISSUE THREAD

**Issue by rioukkevin** [directus/app#2472] opened 2020-01-26 19:42 UTC
I think a good thing missing today on directus is a way to backup schema and data and to restore it when needed without need to access BDD and backup it ;)

Have a nice day and be happy
Kevin

**Comment by benhaynes** [comment] 2020-01-26 20:21
Thanks @rioukkevin! I'll mark this as a duplicate of: https://github.com/directus/app/issues/765

**Closed by benhaynes** 2020-01-26 20:21 UTC
