### ISSUE TITLE
All my tables have datetime fields, but after the initial import they display blank values.

### ISSUE THREAD

**Issue by josedacruz** [directus/app#1680] opened 2019-05-25 20:50 UTC
- I am using docker images.
- My database use audit fields and other datetime columns.
- When I manage a collection all datetime fields display blank values, but they have values in the database.
- I tried to create a table with only datetime and timestamp, it just throws an error when I try to display the table/collection contents.
- if I create a new collection, with directus, with datetime fileds, it works, however with the dateformat mm-dd-yyyy.
- I really like directus to provide rest access to my database and to manage them internally, so I hope you can really fix this.

**Comment by benhaynes** [comment] 2019-05-28 13:55
It sounds like the database and Directus are using different date formats... but I'm not sure. 

@rijkvanzanten @bjgajjar ?

**Comment by rijkvanzanten** [comment] 2019-05-28 13:59
What are the errors thrown? Any errors in the browser devtools?

**Comment by rijkvanzanten** [comment] 2019-07-31 21:28
I'm closing this as I can't reproduce this on my end, the version used is quite old (7.0.18), and there hasn't been a response for months. If this issue happens to you, please let us know and we can reopen this issue

**Closed by rijkvanzanten** 2019-07-31 21:28 UTC
Labels: needs more info, not reproducible

**Comment by benhaynes** [comment] 2019-07-31 23:48
Also, we should have a new Docker install option (with an up-to-date version of Directus) this week! 

@WoLfulus 🔔
