### ISSUE TITLE
Make interface meta translation available in crowdin.com.

### ISSUE THREAD

**Issue by everyx** [directus/app#2305] opened 2019-12-10 03:41 UTC
Hi,

I can not find a way to translate interface meta data, can we add interface mtea.json to crowdin.com?

**Comment by rijkvanzanten** [comment] 2019-12-10 16:27
Yes please, this is on the top of my next-feature-to-implement-list

**Comment by rijkvanzanten** [comment] 2019-12-10 16:27
Duplicate of https://github.com/directus/app/issues/1517

**Closed by rijkvanzanten** 2019-12-10 16:27 UTC
