### ISSUE TITLE
Ability to have per projet authorizations / per item authorization

### ISSUE THREAD

**Issue by dangrth** [directus/app#1411] opened 2019-03-20 11:14 UTC
# Feature Request

Currently, the autorization system works on a per collection basis. It would be useful to have  wider and a finer authorization levels : per project and per item inside collection (based on a field).

## What problem does this feature solve?

Use case I'm currently working on, I have :
* A federation of schools
* Individual schools with directors, who should only access contents from their own school
* Inside the schools, teachers who should only access material relative to their classes

The feature would allow to organize it this way :
* one project per school - the federation is authorized to access all projects
* the direction is only allowed to access the project of its school
* inside the collection "students", the teachers can only access the students belonging to their classroom (test on field "classroom") - having a collection per classroom could also work, but then you lose the ability to adress all students as a while

## How do you think this should be implemented?

No idea, I'm new to Directus - I need a headless CMS, but still considering which one to pick, Directus looks like a good candidate, except I don't know how to achieve this security scheme.
Could this be possible to use hooks to achieve this ?

## Would you be willing to work on this?

I could certainly test the feature since I need it, but I'm to new to Directus to work on it.

**Comment by benhaynes** [comment] 2019-03-20 15:17
Hey @dangrth — a few things:

1. You can use [SCIM](https://docs.directus.io/api/reference.html#scim) to manage users across projects by shifting the user management to a centralized/external source.

2. You can use [`mine` and `role`](https://docs.directus.io/guides/permissions.html#accountability) permissions to limit the items a user/role can see. It's not 100% perfect for this use, but would allow you to limit the items a teacher can view/edit based on a parent user/role key.

3. The two features above answer most of your question, but I believe this Feature Request solves the rest: https://github.com/directus/api/issues/511

I'll close this since it is conceptually a duplicate of https://github.com/directus/api/issues/511 — but let me know if you think I've overlooked something specific you need. Also, keep in mind our [80/20 rule](https://docs.directus.io/getting-started/contributing.html#_80-20-rule).

Thank you for submitting this!

**Closed by benhaynes** 2019-03-20 15:17 UTC
Labels: enhancement, question
