### ISSUE TITLE
Listing View Not Showing M20 Data

### ISSUE THREAD

**Issue by hartwm** [directus/app#1085] opened 2018-11-06 20:59 UTC
# Bug Report

## Steps to Reproduce
1. Create Item in Collection
2. Go to Collections > Items Overview
3. M20 Field does not show data in view

## Expected Behavior
Show the same as the dropdown format by default. In this case, it is "Month/Year - Campaign"

## Actual Behavior
It only shows the string fields and not the dynamic fields. i.e. "{{month}}/{{year}} - {{campaign}}" = "/ -"

## Other Context & Screenshots
<img width="574" alt="screen shot 2018-11-06 at 3 40 33 pm" src="https://user-images.githubusercontent.com/2334164/48093248-d9ec5900-e1dc-11e8-8123-601d4148ccfa.png">
<img width="410" alt="screen shot 2018-11-06 at 3 40 54 pm" src="https://user-images.githubusercontent.com/2334164/48093259-e1136700-e1dc-11e8-8f7d-d4e1cea67169.png">
<img width="765" alt="screen shot 2018-11-06 at 3 41 18 pm" src="https://user-images.githubusercontent.com/2334164/48093261-e4a6ee00-e1dc-11e8-8146-01968539e0ff.png">

Database Attached
[local_2018-11-06.sql.gz](https://github.com/directus/app/files/2555015/local_2018-11-06.sql.gz)

## Technical Details

- Device: iMac 
- OS: 10.13.5
- Browser: Chrome 70.0.3538.77 
- Directus App:  7.0.5 
- Install Method:  cloned `master` branch

**Comment by rijkvanzanten** [comment] 2018-11-07 23:41
The problem here is in how the relationships are setup:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/9141017/48168144-2e1a3a80-e2bc-11e8-9153-821221c7d9f1.png">

For some reason, the app didn't update the existing relationship and created a new row.

This results in the API using the first relationship it comes across that fits for the list view which in this case would be `time_period` to `dealer`. 

If we inspect the API response for `/items/sales`, we can actually see that it's putting the `dealer` info in `time_period`. Time period tries to render using the wrong keys, and ends up with the string we're seeing above.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/9141017/48168211-6883d780-e2bc-11e8-825c-373086326d21.png">

@hartwm did you create these relationships through the application or manually in the database? 

@WellingGuzman can the API use the _newest_ record that "fits" in directus_relations instead of the oldest? That way, we're sure it's using the most up-to-date relationship in case something went wrong in saving them.

**Comment by hartwm** [comment] 2018-11-08 14:04
>@hartwm did you create these relationships through the application or manually in the database?

Via the Admin App. Only edited user data directly in the DB

**Comment by srjrol** [comment] 2018-11-09 18:07
I'm having the same problem here:  https://github.com/directus/app/issues/1109

**Comment by rijkvanzanten** [comment] 2018-11-14 23:08
@srjrol it's similar, but not exactly the same 😄

**Comment by rijkvanzanten** [comment] 2018-11-14 23:12
The problem here is the fact that old relations aren't cleaned up. The API is using the first relation (old one) it comes across instead of the last. I can't reliably delete the relations on the app side, cause there's the possibility that they're being used from the other side as an O2M. We'll have to update the API to use the _last_ record in directus_relations instead of the first.

**Comment by rijkvanzanten** [comment] 2018-11-14 23:14
https://github.com/directus/api/issues/586 should fix this for the client side as well.

**Comment by rijkvanzanten** [comment] 2019-01-11 20:33
I'll close this in favor of 
https://github.com/directus/api/issues/586 as it's not a bug in the application per se, but instead the api trying to use the wrong relationship.

**Closed by rijkvanzanten** 2019-01-11 20:33 UTC
Labels: bug, extension
