### ISSUE TITLE
M2O Interface

### ISSUE THREAD

**Issue by benhaynes** [directus/app#1375] opened 2019-03-06 17:35 UTC
No cancel button for modal (no way to exit)

The whole content area scrolls horizontally if too wide... but the search bar should not.

We should look into a better UX for selecting ONE. The checkboxes are a bit confusing.

**Comment by srjrol** [comment] 2019-03-13 21:08
> We should look into a better UX for selecting ONE. The checkboxes are a bit confusing.
I suggest an autocompleting list.  https://jqueryui.com/autocomplete/

**Comment by benhaynes** [comment] 2019-03-14 15:45
I like that — a header with filter/autocomplete would help a lot.

**Comment by felskov** [comment] 2019-04-08 08:18
@srjrol @benhaynes I've looked into it, and seems that allowing missing cancellation (#1452 ) is simply caused by an "action-required" prop on the v-modal tag.

I can create a pull request if you'd like, but it's a one-liner, and I haven't looked into the other things mentioned in this issue. So it might be faster for you guys to fix it on your own along with the rest of the things you're talking about here :-)

One thing I'd like to note: I'm using listing view preferences to apply a filter to list of selectable items, and sort by a specific column name. I'd be sad to see that feature disappear, if the entire UI was moved to an auto-completed input, but perhaps it'd be possible to maintain these configurations with such a solution as well :-)

**Comment by rijkvanzanten** [comment] 2019-04-08 14:22
> I've looked into it, and seems that allowing missing cancellation (#1452 ) is simply caused by an "action-required" prop on the v-modal tag.

This is true, but there is one downside to removing it: right now the interface immediately stages the value as soon as you select an item, so when you select an item and then hit 'cancel', the value is still staged 🤔 

> One thing I'd like to note: I'm using listing view preferences to apply a filter to list of selectable items, and sort by a specific column name. I'd be sad to see that feature disappear, if the entire UI was moved to an auto-completed input, but perhaps it'd be possible to maintain these configurations with such a solution as well :-)

Good point! I don't want to get rid of that functionality. That being said, it's not the most user friendly to setup right now.  I think I'd like to move to a setup where you can select what field to sort on, what fields to display (and how), and what filters to apply. Then we can use those three to render a dropdown autocomplete instead of using the modal with the nested table view.

**Comment by rijkvanzanten** [comment] 2019-06-14 18:12
This is fixed in https://github.com/directus/app/pull/1677

**Closed by rijkvanzanten** 2019-06-14 18:12 UTC
Labels: bug
