### ISSUE TITLE
Slow API & Ping Times

### ISSUE THREAD

**Issue by cbitting** [directus/app#1803] opened 2019-07-01 20:04 UTC
I'm really enjoying the design and setup of Directus. It seems to have everything and headless cms needs! However, I've run into an issue I can't seem to get get over. Super slow response times. Most of the API calls are coming in between 2 - 4 seconds, making editing / changing pages in the admin brutal.

## Setup:
Amazon Linux 2
PHP 7.3.4
Same results on MySql 5.7 & 8.
Directus 7.6.0
Installed via Git
Apache

## Context

I only have 3 test collections, with about 3 fields each, and maybe 3 records each.

The little latency indicator in the top left averages about 1,200ms.

I've swapped DBs and tried setting up new installs and come to the same conclusion. I didn't dig into the API code yet, I wanted to see if I was missing something (I usually am!).

Thanks in advance for any suggestions!

**Comment by rijkvanzanten** [comment] 2019-07-01 21:08
Interesting. I'm wondering what's causing this. The API can get a little slower once you're querying thousands of items or when you have a lot of deeply nested relationships, but 1.2 seconds for near empty responses doesn't sound right. How does your API connect to the database? Maybe the bottleneck is in the inter-server communication in Apache?

The average ping I'm getting on [the demo installation](https://www.directus.app/#/collections/kiosks) is around 130ms, which is expected.

**Comment by rijkvanzanten** [comment] 2019-07-01 21:09
I'm closing this as it's most likely not something that's caused by the application itself. We can move this to the API repo if it's a reproducible issue on a default LAMP stack.

**Closed by rijkvanzanten** 2019-07-01 21:09 UTC

**Comment by cbitting** [comment] 2019-07-01 21:20
Thanks so much. If it's not normal, I'll continue to play around with it. The API and the app are on the same machine. The DB is a remote connection, but still really fast outside of the API connection.

Thanks again for your input!

**Comment by cbitting** [comment] 2019-07-02 16:04
For historical sake, as an update:

I re-setup this on an Ubuntu server (not Amazon Linux) and using the same db i'm getting average pings of 50ms and 200ms API calls. Very fast now! I'm not sure exactly what the bottleneck was, but it's flying now. Thanks again @rijkvanzanten

**Comment by rijkvanzanten** [comment] 2019-07-02 18:39
Could you as a test switch this fast api to a remote DB? It might be the network connection between server and that is the culprit

**Comment by cbitting** [comment] 2019-07-02 18:46
Thanks it's on the same remote DB as the previous. Working great!
