### ISSUE TITLE
Repeater Interface in Repeater Interface not working

### ISSUE THREAD

**Issue by everyx** [directus/app#2194] opened 2019-11-11 05:26 UTC
Your version of Directus: v7.11.0 (directus.app demo api)

when use repeater interface in another repeater interface, the child interface's fields can not set correct.

![repeater-interface-bug](https://user-images.githubusercontent.com/1665522/68562904-9e870900-0486-11ea-9bb5-76494aaf6834.gif)

**Comment by benhaynes** [comment] 2019-11-11 14:57
I'll leave this to @rijkvanzanten to decide if this is a bug or enhancement. This might be an edge-case, in which we'll limit which interfaces can be configured within a repeater.

**Comment by jacobrienstra** [comment] 2019-11-11 20:16
I'd love to have a repeater in repeater, it would be great for creating things like quizzes (repeater for question, within which has repeater for answers)

**Comment by everyx** [comment] 2019-11-14 15:49
Maybe it's the same problem of #1903 and #1845

**Comment by emilianovelasco** [comment] 2019-11-20 09:38
I had the same problem with the latest version of Directus. I use a "Repeater" within a "Repeater" to create a data table, for me it is an indispensable resource (at least 2 levels).

### I am trying to recreate this data in the form:
<img width="572" alt="Captura de pantalla 2019-11-20 a las 10 22 11" src="https://user-images.githubusercontent.com/1174579/69227092-94999000-0b81-11ea-934d-9041308c9693.png">

I think it is a "bug", my current scenario is:
1 repeater with 2 fields:
_ 1 textinput
_ 1 repeater with 2 fields:
__ 1 textinput
__ 1 textinput

I would catalog it as a "bug", since it does not allow inserting the data from the "collection" form.

Thanks ;)

**Comment by emilianovelasco** [comment] 2019-11-20 09:39
> Maybe it's the same problem of #1903 and #1845

Exactly the same problem ;)

**Comment by benhaynes** [comment] 2019-11-20 15:45
When things don't work in someone's specific setup they always say it's a bug. 😄 

Either way, we're diving into the App bugs starting today and will close anything and everything we can.

**Comment by rijkvanzanten** [comment] 2019-11-20 18:09
This is a duplicate of #1903

**Closed by rijkvanzanten** 2019-11-20 18:09 UTC
Labels: bug, enhancement, tweak
