### ISSUE TITLE
Checkboxes Default — Multiple Values

### ISSUE THREAD

**Issue by benhaynes** [directus/app#2212] opened 2019-11-18 17:48 UTC
When adding a default value to a `checkboxes`  interface, you might want _multiple_ values to be selected. However this doesn't work (while single values do work).

Default: `daily,weekly,monthly`

```
{
  "choices":{
    "daily":"Daily Emails",
    "weekly":"Weekly Emails",
    "monthly":"Monthly Emails"
  },
  "allow_other":false,
  "draggable":false,
  "wrap":false,
  "formatting":true,
  "single":false
}
```

![Screen Shot 2019-11-18 at 12 45 58 PM](https://user-images.githubusercontent.com/522079/69076542-b4a24580-0a01-11ea-9efb-64cea54631fb.png)

No values are selected by default.

**Comment by rijkvanzanten** [comment] 2019-11-18 19:18
Have you tried 

```json
{
  "default": ["daily", "weekly", "monthly"]
}
```
?

**Comment by benhaynes** [comment] 2019-11-18 19:25
That doesn't seem to work either — and I think the default should match the output of the saved field (eg: a database column default).

**Comment by rijkvanzanten** [comment] 2019-11-18 19:35
yeah i agree, just confirming to see if that was the cause of the issue

**Comment by rijkvanzanten** [comment] 2019-11-20 18:50
This is a duplicate of https://github.com/directus/app/issues/2204

**Closed by rijkvanzanten** 2019-11-20 18:50 UTC
Labels: bug
