### ISSUE TITLE
8.3.1 Error when clicking on items in table-layout

### ISSUE THREAD

**Issue by Nitwel** [directus/app#2378] opened 2020-01-02 12:59 UTC
How to reproduce:

1. Login into demo
2. Goto e.g. mailing-list collection
3. Scroll down until new items load
4. Click on a newly generated item
5. You get redirected to "https://demo.directus.io/undefined/"

Havent looked at it yet but seems like the url could not be generated when clicking on the item.

**Comment by rijkvanzanten** [comment] 2020-01-02 17:33
Duplicate of https://github.com/directus/app/issues/2362

**Closed by rijkvanzanten** 2020-01-02 17:33 UTC
Labels: bug
