### ISSUE TITLE
Support edit field grid

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#506] opened 2018-07-02 16:37 UTC
Field Grid: Units (1, 2, 3, 4)? Percentage (25%)?, Include "Full"
Maybe we separate "FLOAT" as a separate variable from "WIDTH"?

Only thirds? Only Halves?

```
1-1-1-1
1-1 - 2
2  -  2
4     -
FUUUUUUUUUUULL (0?)
```

**Comment by rijkvanzanten** [comment] 2018-07-02 16:37
(Don't forget about the side-by-side spacing)

**Comment by benhaynes** [comment] 2018-10-01 20:53
Duplicate of: https://github.com/directus/app/issues/773

**Closed by benhaynes** 2018-10-01 20:53 UTC
Labels: enhancement, hacktoberfest
