### ISSUE TITLE
upload files

### ISSUE THREAD

**Issue by Dominique-Sauquet** [directus/app#1714] opened 2019-06-04 21:58 UTC

**Comment by Dominique-Sauquet** [comment] 2019-06-04 22:05
Hi everyone
I am new to Directus and am facing some issues. 
The first one is: I do select "File" as interface type for my field, the storage is configured as mentioned in the doc:
storage' => [
        'adapter' => 'local',
        'root' => './public/uploads/_/originals',
        'root_url' => '/uploads/_/originals',
        'thumb_root' => './public/uploads/_/thumbnails',
],
but nothing happens if I drag and drop an image. 
The form does not detect any change and if I save the item (after changing other field)  no image is uploaded.
Same trouble with "File library".
Thank you for your help.

**Comment by shealavington** [comment] 2019-06-05 08:55
What do you see in the browser console when trying to upload? 
What's the response from the API in your network tab?
Have you allowed write permissions for uploads? ( [View Docs](https://docs.directus.io/advanced/requirements.html#permissions) )

**Comment by Dominique-Sauquet** [comment] 2019-06-05 16:08
Hi Shea
Thanks for your quick and helpful answer. I was at a meeting and tried as soon as I came back.
I changed the permissions of repositories and it worked for the file upload.

Now I tried to do the same on a collection with 3 fields photo1, photo2, photo3.
The photo is correctly uploaded in the browser but the "save" fails with the following error:
_Attempting to write an array as the value for field "photo1" in "article"_
<img width="1099" alt="Capture d’écran 2019-06-05 à 17 56 28" src="https://user-images.githubusercontent.com/1652838/58971582-0cceed80-87bc-11e9-9225-6d700dc7ddaa.png">

Another point: how can I make buttons appear to edit HTML with WYSIWIG interface.

Thanks for your help.
Dominique

**Comment by shealavington** [comment] 2019-06-06 08:17
What versions of the APP/API/Suite are you running?

**Comment by Dominique-Sauquet** [comment] 2019-06-06 11:48
Hi Shea
I downloaded it very recently (less than 3 weeks). I don't know where to find the info but I found that in composer.json : "Directus 7 API wrapper for custom SQL databases"
I love the idea behind DirectUS but I encounter difficulties putting things together and I progress little step by little step ;-(
I insert an capture of how WYSIWYG appears.
Many thanks!

<img width="657" alt="Capture d’écran 2019-06-06 à 13 46 42" src="https://user-images.githubusercontent.com/1652838/59030570-a00e2e80-8861-11e9-8fd9-55b427dd1f41.png">

**Comment by rijkvanzanten** [comment] 2019-06-06 12:39
The WYSIWYG interface is a medium-style editor, meaning that the modification buttons show up when you select a piece of text. You can use the Advanced WYSIWYG interface if you're looking for a more "standard" full fledged wysiwyg editor.

**Comment by shealavington** [comment] 2019-06-06 12:58
Please ensure you're running on the latest version, as your encounter with an issue may have been fixed already in the last `3 weeks`.

As Rijk mentioned too, that WYSIWYG issue is user error. Please follow his steps to use it correctly, or change it to an 'Advanced WYSIWYG'.

**Comment by Dominique-Sauquet** [comment] 2019-06-06 21:41
Hi Shea and Rijk
I downloaded the new version!
An improvement: the black "manage" button appears under 

But:
1) when filling the form for an item of my collection, I upload a photo (nicely appears into the page) but the save tells me : Attempting to write an array as the value for field "photo1" in "article".
If I go to the "File Library" it is there.

<img width="1062" alt="Capture d’écran 2019-06-06 à 23 16 08" src="https://user-images.githubusercontent.com/1652838/59067208-46355500-88b1-11e9-80c4-b54af3fc659f.png">

2) now if I go to "Admin User" and "Settings" and "Collections & Fields", if I update a field 

- if I do minor changes (for instance placeholder) it works
- if I change the interface (for instance use WYSIWYG nothing happens : you press the save button and nothing! You stay into the update form, no error in the console, nothing in the network.

So bad! Directus looks great but the learning curve is painful (for me)!
Hoping you can help
Dominique


-

**Comment by Dominique-Sauquet** [comment] 2019-06-13 18:14
Hi Ben
Any idea when the bug I encountered will be solved?
Thanks a lot
  Dominique

**Comment by benhaynes** [comment] 2019-06-13 18:21
Unfortunately, no. Being an open-source project we can only work on it a day or two per week (unless a person/company sponsors additional time). We're slotted to work on Directus tomorrow, but I don't know if this will be included in the fixes.

**Comment by shealavington** [comment] 2019-06-14 08:13
I believe that the issue you're seeing will be related to https://github.com/directus/api/issues/1015. Could you confirm if this sounds similar? If this is the case, we can close this issue and manage the issue there.

**Comment by mebenhoehta** [comment] 2019-06-25 06:10
Just fyi, this is still broken on my local test environment with api 2.2.0 / app 7.6
The problem only occurs if  a collection has more than one file upload (e.g. we have four) and more than one is uploaded at once, uploading one and saving  for each one, one after the other, works

I currently cannot log in to directus.app to check it there (I think the site's config is wrong on https://www.directus.app, and I can't remember the api endpoint to use)

**Comment by rijkvanzanten** [comment] 2019-06-25 16:57
I'm closing this as the original post is a duplicate of https://github.com/directus/api/issues/1015

@mebenhoehta this sounds like a different more specific issue with the `files` interface. Is your issue similar to https://github.com/directus/app/issues/1573?

**Closed by rijkvanzanten** 2019-06-25 16:57 UTC
Labels: duplicate
