### ISSUE TITLE
Translated file-interface not rendered when switching language

### ISSUE THREAD

**Issue by JackLeEmmerdeur** [directus/app#1920] opened 2019-08-03 00:51 UTC
Steps:
1. Done setup for content-translation via app
2. Normal input-fields are working in translation
3. File-fields partially not working: When the language pulldown is changed, then the file-interface and it's related controls are not rendered anymore

Found two locations in the code, that could be changed to fix above situation, but I don't know, if that causes side-effects. On my side I've had no erratic behaviour with the files-interface.

So the 2 changes are both in src/interfaces/file/input.vue:

In line 195 change
`this.$emit("input", { id: fileInfo.data.id });`
to
`this.$emit("input", this.image);`

And in line 219 change
`this.$emit("input", { id: file.id });`
to
`this.$emit("input", file);`

**Comment by itsmerhp** [comment] 2019-08-10 10:43
@JackLeEmmerdeur 
I have followed above mentioned steps, but the issue is not reproducing.

Can you please check [this video](https://drive.google.com/file/d/1c8g_yN2i_icgIWYuKfPIByLd4VuNF9Gi/view) and confirm that I am following correct steps?
Please also confirm that you are using the latest APP build.

**Comment by JackLeEmmerdeur** [comment] 2019-08-10 22:23
That's a really good way to bring the each other to the same level of understanding. Thanks.

Yes, I have nearly the same layout in my setup.

One click was missing in your demo to see the bug, I believe.

1. First you opened an existing Resort-Item. Both images already there.
2. Then you created a new Resort-Item.
   - There you inserted an image for english.
   - Then switched to french and inserted the other image.
   - **To see the bug switch back to english, here.**

Even if you don't see the image, when you revisit the first language, it gets updated in the database.
So if you reopen the Resort-Item, like in the beginning of the video, you get both images correctly.
Happens only at editing.

**Comment by bjgajjar** [comment] 2019-08-20 10:56
Fixed in #1971

**Comment by rijkvanzanten** [comment] 2019-08-21 20:08
#1971 was reverted

**Closed** 2019-08-29 15:32 UTC
Labels: bug
