### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by dur41d** [directus/app#700] opened 2018-08-30 15:21 UTC
## Describe the Bug
Getting the following error when navigating to the User Directory:

vue.runtime.esm.js:1737 TypeError: Cannot convert undefined or null to object

and the User directory interface is empty.

## Steps to Reproduce
1. Go to 'User directory'
2. Open browser console.

## Screenshots

![image](https://user-images.githubusercontent.com/1318592/44861329-4d567500-ac46-11e8-8f09-0729215631c8.png)

## Technical Details
- OS: [Windows 10]
- Browser: 68.0.3440.106 (Official Build) (64-bit) (cohort: Stable)
- Directus App:  0470ae201be67cf972f2c49f0e17a150c2dbdfd4 (build/rc2)
- Directus API: 406b27430bd3b4e4e12ba5d62be671116d3250a2 (build/rc2)

**Comment by rijkvanzanten** [comment] 2018-09-10 21:35
This is a duplicate of #698

**Closed by rijkvanzanten** 2018-09-10 21:35 UTC
Labels: duplicate
