### ISSUE TITLE
Error in wysiwyg input when used within modal

### ISSUE THREAD

**Issue by IgordeOliveira** [directus/app#2870] opened 2020-06-12 20:17 UTC
Hello, I'm having a problem here, when I try to edit a field of type many to many ( another collection ), and this collection contains a field of type wysiwyg ( editor ) and saved, the console points out that the editor is undefined (screenshot below), and when I do it several times, it does not save the new content written

• Version of Directus: 8.7.2
• Server, OS & Database Details: Docker, MySql
• Error Messages
![Anotação 2020-06-12 165603](https://user-images.githubusercontent.com/19624377/84542533-08db8280-acd0-11ea-96a6-469bf475a28b.png)

• Steps to Reproduce
Try editing the value of a wysiwyg editor from another collection
• Relevant Info, Screenshots, Schema & Logs
![Anotação 2020-06-12 170212](https://user-images.githubusercontent.com/19624377/84542624-3aece480-acd0-11ea-904a-d15af239fa32.png)
![Anotação 2020-06-12 170251](https://user-images.githubusercontent.com/19624377/84542625-3c1e1180-acd0-11ea-8417-9aaf288dd734.png)

🐰

**Comment by imrick** [comment] 2020-06-30 17:26
Hello, i have the same error within a oneToMany field.

**Steps to reproduce**

1. Create a collection that have a oneToMany field to an other collection
2. Add a wysiwyg field in the many collection
3. Add an item in the many collection field
4. Select an image then click "save" but without typing anything in the editor

**Analysis**

This is related to the debounce on "updateValue". The blur event is indeed trigger properly but the callback happens after the editor was destroyed.

**Possible solution**

Only the "@OnkeyUp" event should be debounced to preserve good performances. By removing debounce on the other events the problem is solved.

**Comment by rijkvanzanten** [comment] 2020-07-01 18:19
Fixed in https://github.com/directus/app/pull/2898

**Closed by rijkvanzanten** 2020-07-01 18:19 UTC
Labels: bug
