### ISSUE TITLE
Install the app in a not in the root of the website

### ISSUE THREAD

**Issue by dur41d** [directus/app#699] opened 2018-08-30 15:13 UTC
**Is your feature request related to a problem? Please describe.**
Currently the app can only be installed in the root of website. Normally the app is my admin interface for content authors and root of the website is dedicated to the public website that uses the content. 

**Describe the solution you'd like**
I would like to be able to install the app in a different location than the root of the website.

**Comment by rijkvanzanten** [comment] 2018-08-30 22:05
This is directly related to https://github.com/directus/app/issues/634

**Comment by benhaynes** [comment] 2018-10-01 14:59
This is a duplicate of #634 – I'll close it and we can monitor progress there (pushing fix today)

**Closed by benhaynes** 2018-10-01 14:59 UTC
