### ISSUE TITLE
Default dropdown option not working

### ISSUE THREAD

**Issue by srjrol** [directus/app#1110] opened 2018-11-09 20:19 UTC
# Bug Report

## Steps to Reproduce

1. Create a dropdown field for a collection.  
2. Set a default value for the dropdown field.
3. The drop downdown does not select the default option automatically.

## Expected Behavior

'value1' text should be displayed "Option 1".

## Actual Behavior

Default Dropdown does not show default value "Option 1" but it is available and set in the options.

![image](https://user-images.githubusercontent.com/34398302/48286154-66d82200-e42a-11e8-97bc-bd06f6d0ff0e.png)
![image](https://user-images.githubusercontent.com/34398302/48286160-69d31280-e42a-11e8-993d-52938eeb7758.png)
![image](https://user-images.githubusercontent.com/34398302/48286171-6d669980-e42a-11e8-8eb4-0e283777ba51.png)
![image](https://user-images.githubusercontent.com/34398302/48286178-722b4d80-e42a-11e8-8bf5-99b42d728b6e.png)

![image](https://user-images.githubusercontent.com/34398302/48286079-1f519600-e42a-11e8-908b-45d6e2564944.png)

**Comment by srjrol** [comment] 2018-11-15 12:57
@rijkvanzanten I did not set this value.  It was set by Directus with the added ' '

**Comment by benhaynes** [comment] 2018-11-15 13:53
Interesting.

**Comment by rijkvanzanten** [comment] 2018-11-15 14:15
What database are you using? MySQL? I just tried this on our demo servers running the latest version and it seems to be working fine on my end.. There must be something in your particular setup that's causing this issue. (Not saying your setup is wrong 😁 )

**Comment by rijkvanzanten** [comment] 2018-11-16 14:13
This turned out to be a problem in the server setup of this particular instance and wasn't reproducible on the live demo.

I'll close this as it's not so much an issue in the app itself. Once we figure out exactly what was wrong in this particular server setup, we can add a note to the docs pointing it out.

**Closed by rijkvanzanten** 2018-11-16 14:13 UTC
Labels: extension, not reproducible

**Comment by benhaynes** [comment] 2018-11-28 12:51
I believe this is actually an issue with Maria DB.

https://github.com/directus/api/issues/549

I've bumped 549 from Low to High priority in Bug Triage, but will leave this closed as it's a duplicate.
