### ISSUE TITLE
Unable to add item with O2M field to collection by non-admin

### ISSUE THREAD

**Issue by kubowler99** [directus/app#1337] opened 2019-02-14 17:54 UTC
# Bug Report

Currently unable to add an item to a collection as a non-admin if the collection has a O2M field associated. 

## Steps to Reproduce
As an Admin user:
1. Create a new role (for example, developer)
2. Create a new user called 'developer@test.com' and add to the 'developer' role
3. Create a new collection called 'm2o_test'
4. Create a new text field in the m2o_test collection called 'name'.
5. Create a new entry in the 'm2o_test' collection. In the name field, call it 'm2o_test_entry'.
6. Create a new collection called 'test'
7. Add an M2O field called name, referencing the 'm2o_test' collection 'id' field, and format the dropdown menu as {{name}}
8. Add a text field called test1.
9. Create a new entry in the 'test' collection. Select 'Published' as the status. Choose 'm2o_test_entry' for the name in the dropdown menu. Type in 'test' in the test1 field. Click the checkmark.
10. The above should verify it works for an admin.
11. Grant the 'developer' role full access to both the m2o_test and test collections.
11. Log off

As the developer@test.com user:

12. Click on the 'test' collection
13. Create a new entry in the 'test' collection. Select 'Published as the status. Choose 'm2o_test_entry' for the name in the dropdown menu. Type in 'test2 in the test1 field. Click the checkmark.
14. Nothing happens. If you check the browser console, you should see the following error:

Failed to load resource: the server responded with a status of 403 (Forbidden)
error.js:9 

class: "Directus\Permissions\Exception\ForbiddenCollectionUpdateException"
code: 302
file: "/home/vcap/app/htdocs/directus/src/core/Directus/Permissions/Acl.php"
line: 1072
message: "Updating item from "directus_users" collection was denied"

## Expected Behavior

A non-admin user should have the ability to add entries to a collection if they have the correct permissions.

## Actual Behavior

Non-admin user is unable to add entries to a collection.

## Technical Details

- Device: MacBook Pro
- OS: MacOS 10.12.6
- Browser: Chrome 72.0.3626.109
- Directus App: 7.0.17
- Directus API: 2.0.17
- Install Method: cloned `master` branch of `directus/directus`

**Comment by rijkvanzanten** [comment] 2019-02-18 14:38
Did this collection have the user_created / user_updated fields too?

I'm thinking this is caused by the fact that the application will send a full copy of the related item (O2M) to the API even for the fields that didn't update (as it might be a new item). If the user_created or user_updated fields are copied over and send (even if they didn't change) the API will consider that an update.

**Comment by kubowler99** [comment] 2019-02-18 15:02
It has the created by/created on fields

**Comment by mvhirsch** [comment] 2019-04-19 12:19
This looks like an duplicate of #1284

**Closed** 2019-07-15 16:17 UTC
Labels: bug
