### ISSUE TITLE
Item not found / have to login again

### ISSUE THREAD

**Issue by HerrHase** [directus/app#2162] opened 2019-10-26 10:36 UTC
There is a strange behavior, i work a few minutes in the backend, on a single item and have already saved it a few times, then after i saved it again, i get this message,

```bash
item not found
```

If i reload the site, i get a redirect to the login. In the log i found this,

```bash
[2019-10-26 12:18:32] api[_].ERROR: Directus\Database\Exception\ItemNotFoundException: Item not found in /var/www/directus/src/core/Directus/Services/ItemsService.php:138
Stack trace:
#0 /var/www/directus/src/core/Directus/Services/ItemsService.php(325): Directus\Services\ItemsService->findByIds
#1 /var/www/directus/src/endpoints/Items.php(121): Directus\Services\ItemsService->update
#2 [internal function]: Directus\Api\Routes\Items->update
#3 /var/www/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#4 /var/www/directus/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#5 /var/www/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#6 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#7 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#8 [internal function]: Slim\DeferredCallable->__invoke
#9 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#10 /var/www/directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(120): Slim\Route->Slim\{closure}
#11 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#12 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#13 [internal function]: Slim\DeferredCallable->__invoke
#14 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#15 /var/www/directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#16 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#17 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#18 [internal function]: Slim\DeferredCallable->__invoke
#19 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#20 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#21 /var/www/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#22 /var/www/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#23 /var/www/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#24 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#25 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#26 [internal function]: Slim\DeferredCallable->__invoke
#27 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#28 /var/www/directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#29 /var/www/directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#30 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#31 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#32 [internal function]: Slim\DeferredCallable->__invoke
#33 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#34 /var/www/directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#35 [internal function]: RKA\Middleware\IpAddress->__invoke
#36 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#37 [internal function]: Slim\DeferredCallable->__invoke
#38 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#39 /var/www/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#40 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#41 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#42 [internal function]: Slim\DeferredCallable->__invoke
#43 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#44 /var/www/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(54): Slim\App->Slim\{closure}
#45 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#46 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#47 [internal function]: Slim\DeferredCallable->__invoke
#48 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#49 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#50 /var/www/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#51 /var/www/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#52 /var/www/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#53 /var/www/directus/public/index.php(5): Directus\Application\Application->run [] []
```

Directus Version 7.11.0
Ubuntu 18.04

Browser
Firefox 69.0.3 on a Linux Mint 19.2

**Comment by benhaynes** [comment] 2019-10-26 13:00
Hmm, that seems odd! Sounds like an issue with the store maybe? What DB/version are you using? Is this Apache?

**Comment by HerrHase** [comment] 2019-10-27 08:07
I use a mysql  Ver 15.1 Distrib 10.4.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2,
as Webserver a Nginx

**Comment by benhaynes** [comment] 2019-10-27 11:31
Ahh, first make sure you are on MariaDB 10.2+ 

https://docs.directus.io/getting-started/installation.html#requirements

**Comment by HerrHase** [comment] 2019-10-28 20:33
To be really sure i had switched to mysql 5.7.27, but after 15 Minutes, same error...

**Comment by alrick** [comment] 2019-10-29 08:28
Some clients reported the same error to me.
Unfortunately I have no more details for now, but I just wanted to point that it's not an isolated issue.

**Comment by HerrHase** [comment] 2019-10-29 18:06
It feels like a authenticate-Problem. @benhaynes is there any way i can help to solve this? Are there any Information that might helpful?

**Comment by benhaynes** [comment] 2019-10-30 00:49
We have a completely new auth flow that will be out int he next release — that's why there has been such a gap since the previous release. So this should be resolved with that new login.

**Comment by DoctypeRosenthal** [comment] 2019-11-05 21:16
So when will this release happen? I cannot access files. When I try to GET http://<my_url>/_/files/8?access_token=staticToken 
I get "Item not found" back. In the backend it works with no problems but I don't understand what I am doing wrong. Testing this from localhost from a React app I develop and the documentation doesn't help. 
Should I switch to another CMS for production? I have a customer waiting for me to finish the project and I thought Directus is save for production. But obviously there are still a lot of rough edges or non-existing edges in it....

**Comment by rijkvanzanten** [comment] 2019-11-06 01:55
@DoctypeRosenthal sounds like your problem has nothing to do with the issue mentioned in the OP. 

Seeing this is an open source project, feel free to update the docs wherever you feel like they're not clear enough.

**Comment by brunipster** [comment] 2019-11-18 04:42
Is any quick fix possible? . I have a presentation in 2 days

**Comment by benhaynes** [comment] 2019-11-18 15:15
This will be fixed in v8 (coming soon), so my recommendation would be to try out the RC versions if you really need this fixed. @rijkvanzanten, does that sound correct?

**Comment by rijkvanzanten** [comment] 2019-11-18 15:25
Yeah! Or you might be able to hack your way around the auth completely by modifying this file temporarily (not tested nor confirmed, try at your own risk)

https://github.com/directus/api/blob/c3692ed89508f5b1d171444272c74f83e98e1887/src/core/Directus/Application/Http/Middleware/AuthenticatedMiddleware.php#L10-L23

**Comment by rijkvanzanten** [comment] 2019-11-20 18:39
This is fixed in v8

**Closed by rijkvanzanten** 2019-11-20 18:39 UTC
Labels: bug
