### ISSUE TITLE
creating many-to-many field won't show many-to-one options

### ISSUE THREAD

**Issue by jasonmarysael** [directus/app#1250] opened 2019-01-12 23:06 UTC
# Bug Report

since the upgrade to 7.0.14 I'm not able anymore to list my many-to-one objects within the creation from a new many-to-many field

![image 591](https://user-images.githubusercontent.com/28600053/51079378-392b8580-16c6-11e9-9266-6bf7cf79d0c6.png)

Double clicking the dropdown menu shows me this:

![image 592](https://user-images.githubusercontent.com/28600053/51079381-4fd1dc80-16c6-11e9-8016-27ea8ef16dc7.png)

## Expected Behavior

The dropdown should list all many-to-one fields

## Actual Behavior

Nothing happens when selecting the dropdown

## Extra info

Creating a new field under the collection directly seems to work fine

![image 593](https://user-images.githubusercontent.com/28600053/51079402-cd95e800-16c6-11e9-8ac2-dda85275e72f.png)

## Technical Details

- Device: Desktop
- OS: Windows 10.1803
- Browser: [eg: Chrome 71.0.3578.98]
- Directus App: 7.0.14
- Directus API: v2.0.14
- Install Method:  cloned `master` branch of `directus/directus`

**Comment by rijkvanzanten** [comment] 2019-01-22 16:52
The M2O uses a modal with the full listing view if the dropdown has more than 20 or so options available. That makes this a duplicate of #1083

**Closed by rijkvanzanten** 2019-01-22 16:52 UTC
Labels: bug, extension
