### ISSUE TITLE
Permissions (wrong) default permissions

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1203] opened 2018-12-15 14:52 UTC
### Steps to reproduce:
1. create new permissiongroup
2. create new user and add the created group
3. login as this user
4. Changed data in the info of an interface cant get saved due to no permissions for updating
5. an error occurs

### info settings
![grafik](https://user-images.githubusercontent.com/22577866/50044271-66622500-0081-11e9-94c4-67c7c9aee43b.png)

### permission settings of directus
![grafik](https://user-images.githubusercontent.com/22577866/50044193-4da53f80-0080-11e9-8ddb-28d8f6d923c4.png)

### Expected behavior
Editng the settings of a layout should be saved and not end in an error

Directus: latest
API: latest

**Comment by rijkvanzanten** [comment] 2018-12-15 14:57
I believe this is a duplicate of https://github.com/directus/api/issues/627

**Comment by Nitwel** [comment] 2018-12-15 14:58
Ah, ups XD
sorry about that :)

**Closed by rijkvanzanten** 2018-12-15 14:57 UTC
Labels: duplicate

**Comment by rijkvanzanten** [comment] 2018-12-15 15:00
No worries :) I'd rather have duplicates than no issue at all 😉
