### ISSUE TITLE
Cloud - Creating a Files interface into a relationship field broke parent Browse view and Admin Edit field view

### ISSUE THREAD

**Issue by Vadorequest** [directus/app#2710] opened 2020-04-04 23:49 UTC
# Status

This issue happened and got fixed by 
- deleting the `images` field from the `Products` collection
- the auto-created `products_directus_files` collection
- Then by recreating the `images` field

The origin of the issue is unknown. The goal of the GH issue is to give as much context as possible to allow to find the source of the bug.

# Workflow

- I created an `images` field using Files Interface in my Products collection.
- I used the Auto-Generate option to create the `images` field, I also set a `image/jpg, image/jpeg, image/png` MIME type filter
- The Products collection has a O2M relationship with the Customers collection (one customer may own multiple products)
- When I went back to the Customers Browse view, I got this:

![image](https://user-images.githubusercontent.com/3807458/78463503-c13be780-76dd-11ea-869a-c29129cf6fc6.png)

Looking at the browser console shown this:

![image](https://user-images.githubusercontent.com/3807458/78463510-cd27a980-76dd-11ea-82ca-ceb43514e04e.png)

I wasn't able to edit the Products.images field anymore, clicking on it didn't open the Field edit view. Instead, I got errors on the browser console on click.

![image](https://user-images.githubusercontent.com/3807458/78463513-cf8a0380-76dd-11ea-88fa-0a4d28720129.png)

I deleted the Products.images field and I attempted to re-create the Products.images field, here is what was shown to me by default:

![image](https://user-images.githubusercontent.com/3807458/78463514-d284f400-76dd-11ea-9560-960b497bcd1b.png)

And when clicking on the Auto-Generate option (I believe it was completely identical as what I had seen just before):

![image](https://user-images.githubusercontent.com/3807458/78463515-d4e74e00-76dd-11ea-9347-dfba21e655f8.png)

It failed, because the auto-generated table `products_directus_files` existed already. (shown both create + fail, it created the field indeed but same as before, I couldn't click on it either)

![image](https://user-images.githubusercontent.com/3807458/78463518-d87ad500-76dd-11ea-82e6-1c6ebd3a06a5.png)

- I deleted the `products_directus_files` collection and deleted the Products.images field too.
- Then, I created the Products.images field again, I used the Auto-Generate option again, **but I didn't set a MIME type** (it's the only difference I can see)

![image](https://user-images.githubusercontent.com/3807458/78463519-db75c580-76dd-11ea-9115-5772f712762b.png)

And this time, everything worked correctly. I was able to Browse my Customers again, and the Edit view worked as well (I haven't tried to actually upload a file yet)

**Comment by Saniq** [comment] 2020-04-06 08:00
This looks like exactly the same issue I had. It is caused by toggling the "Auto-Generate" checkbox multiple times.

Fixed by #2704

**Comment by Vadorequest** [comment] 2020-04-06 08:16
Indeed, I had checked it multiple times the first time to see what it was doing on the UI.

**Comment by Saniq** [comment] 2020-04-06 11:35
That's what I did as well. Then it is definitely the same issue.

**Comment by darioseidl** [comment] 2020-05-12 16:01
This just happened to me as well. Thanks for the detailed explanation! I removed the field and the generated join table, and added the relation again making sure to only quick the checkbox once this time and it then it worked.

**Closed** 2020-05-18 15:26 UTC
Labels: bug
