### ISSUE TITLE
Collection list empty, no rows, no fields

### ISSUE THREAD

**Issue by Alexggp** [directus/app#1958] opened 2019-08-13 06:51 UTC
Hello, 

I've been playing with the table fields options, marking and unmarking some of them and sudlenly an error was displayed and now the collection list its totally empty, theres no rows or colls, and the table fields options it's empty too. 

It only happends in my directus user. 

before:
![image](https://user-images.githubusercontent.com/1389054/62920852-35b8c380-bda7-11e9-8e80-350be22ee896.png)
after:
![image](https://user-images.githubusercontent.com/1389054/62920894-5719af80-bda7-11e9-86c6-45453534382c.png)

I'm using 7.9.0 version

Thank you very much!!

**Comment by Alexggp** [comment] 2019-08-13 07:00
Hello, I have delete from directus.directus_collection_presets the rows that match with my user id and now everything have back to normally.

**Comment by urvashithakar** [comment] 2019-08-13 12:28
Hello @Alexggp,
Not able to replicate this.

**Comment by benhaynes** [comment] 2019-08-13 16:39
Hey @Alexggp — are you able to replicate this on our online demo? If we have actual steps to make this happen (on an install we can confirm is correct) than this will be easy to fix! Thanks for all your help on this one. :)

https://directus.app

`admin@example.com`
`password`

**Comment by edenprojectde** [comment] 2019-08-14 00:28
Looks like this one: https://github.com/directus/app/issues/1939

**Comment by edenprojectde** [comment] 2019-08-14 00:30
A quick fix to this is to make all fields visible in the field options. 

![image](https://user-images.githubusercontent.com/6115966/62986337-63e7e300-be3b-11e9-899b-75aa93ee6007.png)

It will correctly show the Timeline View afterwards, if it is the same issue.

**Comment by rijkvanzanten** [comment] 2019-08-15 00:57
I'll close it as a duplicate of #1939 for now (as @edenprojectde pointed out).

Lemme know if you still have the problem after that fix @Alexggp and we can reopen and investigate further 🙂

**Closed** 2019-08-15 00:57 UTC
Labels: duplicate
