### ISSUE TITLE
Max width for Interfaces

### ISSUE THREAD

**Issue by srjrol** [directus/app#1406] opened 2019-03-18 23:11 UTC
# Bug Report

## Steps to Reproduce

1. Create a text-input field
2. Create a text-area field
3. Set the 'directus_fields' 'width' column for each field to a value of 4.
4. Clear cache/refresh the collection with text fields.

## Expected Behavior
The text-input and text-area fields should be the same width (4 columns).
## Actual Behavior
text-area is able to extend across 4 columns but text-input is limited to 2.

## Other Context & Screenshots

I don't have much experience with CSS but I think the problem is related to the following property which I think is assigned by the type of interface.

.interface-checkbox-relational {
    max-width: var(--width-medium);

The text-input shows a medium (300px) max width but the text-area is set to x-large (600px).

I belive the solution would be to apply the x-large max-width to the interface type.

I notice this issue first with relational checkboxes, but I find it affects other interfaces as well such as the text-input.

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Latest Chrome
- Directus App: 7.0.19
- Directus API: 7.0.19
- Install Method: Cloned `master` branch of `directus/directus`

**Comment by srjrol** [comment] 2019-03-18 23:37
I think I found the solution by editing 
public/extensions/core/interfaces/checkboxes-relational/input.css:
https://github.com/directus/directus/commit/13fea2e15b86f55a2ad7a411de398269db0ad57b
public/extensions/core/interfaces/text-input/input.css:
https://github.com/directus/directus/commit/83a11c00b8b87ee07372fe926c2dc4b50a11510d

**Comment by rijkvanzanten** [comment] 2019-03-18 23:48
I think this is by design. @benhaynes care to chime in?

**Comment by benhaynes** [comment] 2019-03-19 00:47
Partially, but in the end this will be resolved by the new grid system. My feeling is that every interface should have a min/max width and within those bounds you can set what you want. As of now the width options would be: `single,` (half width) `double`, and `full`.

**Comment by rijkvanzanten** [comment] 2019-04-19 21:14
I removed all the max-widths for the interfaces so this should be fixed 🙂

**Closed by rijkvanzanten** 2019-04-19 21:14 UTC
