### ISSUE TITLE
[v2.0.17] Incorrect trim on Locale

### ISSUE THREAD

**Issue by gnh1201** [directus/app#1382] opened 2019-02-13 04:21 UTC
I had mentioned a similar problem in #740.
Since there was no major inconvenience, I decided to use it as it is,
but I found that the problem has spread to the locale after the version upgrade.

the 'en-US' is now displayed as 'n-U' in my User Directory.
https://i.imgur.com/GEm8GKc.png

**Comment by shealavington** [comment] 2019-04-28 00:38
Was this closed in https://github.com/directus/directus/issues/2335 ?

![image](https://user-images.githubusercontent.com/16869302/56856612-2d528f00-6956-11e9-8ed3-bb8d1f97d15d.png)

**Comment by shealavington** [comment] 2019-04-28 00:41
Is this now working? 
Locale is now formatted fully rather than an "en-US"? 
Draft is selected by default meaning you can't accidentally submit an empty status..

![image](https://user-images.githubusercontent.com/16869302/56856628-76a2de80-6956-11e9-84a0-dd3392dba335.png)
![image](https://user-images.githubusercontent.com/16869302/56856642-cda8b380-6956-11e9-99bc-87e2bc1be5de.png)

**Comment by rijkvanzanten** [comment] 2019-04-29 14:45
Does it save correctly @shealavington? No more `n-U` or `raf` in the database?

**Comment by shealavington** [comment] 2019-04-29 15:40
From my testing, that's correct.

The user status now defaults to "Draft" in the app, therefore, you can't submit it empty causing "raf" — Though, as I say this, I guess theoretically, you could submit it as empty through the API, I only tested through the App. 

As far as I remember, the only issue with the Locale was a display one, however, it's now nicely displayed as "English (United States)" rather than "en-US", looking like it's cleared that issue.

I'll go back later, review this and let you know. :smiley:

**Comment by gnh1201** [comment] 2019-05-06 19:03
Today, I did updated to latest version of api/app.
I had a problem every time I registered a new user. I have manually adjusted this with phpmyadmin or adminer.
It was saved as 'raf' and saved as 'n-U'.

**Comment by benhaynes** [comment] 2019-05-07 00:41
Thanks @gnh1201 — are you sure you have updated your database, and cleared any cache? Also, are you using our supported stack? Could you describe your specific setup here so we can rule out any differences caused by that?

**Comment by gnh1201** [comment] 2019-05-07 07:14
I have updated the database and cleared the cache. No special settings exist.

**Comment by shealavington** [comment] 2019-05-07 13:35
I can't reproduce this with my testing @gnh1201

I feel like I'm lacking information, are you installing the full-build, the api/app separately, are you leaving any fields blank? Replication steps will be needed, including details of your setup

**Comment by gnh1201** [comment] 2019-05-21 14:57
1. For example, when I get a chance to select one of such as `Draft`, `Published`, or `Deleted`,
it will be saved as `raf` if I save it without selecting anything.
2. For example, when I do not select any of the timezone and locale in the user directory, it is stored as `n-U` and` merica / New_Yor`.
3. For example, I created a collection called `recipients` and created a field called` currency` in it. I saved the default value as `USD`, but the value is saved as` S`. 'EUR' is stored as 'U'.

Even though I made a steady update, I do not know why this problem persists.

**Comment by shealavington** [comment] 2019-05-21 15:20
> if I save it without selecting anything.

I'm almost certain there was an update where you now can't submit an empty status field *(Screenshot 2)*

> when I do not select any of the timezone and locale in the user directory,

Again, I'm sure there was an update that fixed this, so something is selected by default, you can't really leave it blank now... Unless it's trying to read a default from your config and maybe that's setup incorrectly if you've changed the timezone?

Have you tried this on a fresh install? This could determine if your current data has an impact.

**Screenshot of clicking the '+' to add a new user:**
![Selection_121](https://user-images.githubusercontent.com/16869302/58108141-347e5d00-7be3-11e9-80f5-b44b6d2434d1.png)

**I even just created a new collection with a status, tried to save without selecting a status, and it's saying it can't be saved...**
![Selection_122](https://user-images.githubusercontent.com/16869302/58108321-8cb55f00-7be3-11e9-85e7-a66c8e090124.png)

**Comment by benhaynes** [comment] 2019-05-21 15:57
The update (I think you're talking about) was that `status` fields (actually, all fields) are `required` by default. Though I think status might _always_ be required since it's used by permissions and other system-level stuff.

I'm curious what causes this... maybe @gnh1201 could you send a database dump so we can see if it's connected to that setup? You can send it privately on Slack if you prefer

**Comment by gnh1201** [comment] 2019-05-24 01:43
Yes. If the problem still occurs after the latest update, I will send the database dump.

**Comment by shealavington** [comment] 2019-06-11 08:48
Is this issue still happening @gnh1201 ?

**Comment by gnh1201** [comment] 2019-06-19 06:21
I sent my database dump on Slack. Please confirm. @benhaynes

**Comment by benhaynes** [comment] 2019-06-19 14:27
Yes, we have it @gnh1201 — thanks!

**Comment by bjgajjar** [comment] 2019-06-20 16:18
Hey @gnh1201 

I checked below all scenarios in your given dump.

> 1. For example, when I get a chance to select one of such as `Draft`, `Published`, or `Deleted`,
>    it will be saved as `raf` if I save it without selecting anything.
> 2. For example, when I do not select any of the timezone and locale in the user directory, it is stored as `n-U` and `merica / New_Yor`.
> 3. For example, I created a collection called `receipts` and created a field called `currency` in it. I saved the default value as `USD`, but the value is saved as `S`. 'EUR' is stored as `U`.
> 

And none of them are reproduced at my end. 

Can you please verify that you are using the latest version of `API` and `APP`?

**Comment by shealavington** [comment] 2019-06-20 16:28
I also briefly re-read this thread and noticed that you (@gnh1201) mentioned:

> I have updated the database and cleared the cache. No special settings exist.

Please also ensure you are actually updating your install of Directus... Hopefully you are not just clicking the "Update database" button expecting that to upgrade everything. That button is to be pressed _after_ updating the code, could you please explain what steps you took to upgrade Directus on your end.

_(Also as @bjgajjar said, let us know which versions of the `APP` and `API`  you're running.)_

**Comment by shealavington** [comment] 2019-07-11 16:22
@directus/team Can anyone replicate this? Multiple times now I've tried to replicate this and can't get it to happen. If we can't replicate this, it can be closed as the issue seems stagnant.

**Comment by rijkvanzanten** [comment] 2019-07-11 17:11
@shealavington I seem to have no problem changing my locale on both the live demos and my local copy

**Comment by benhaynes** [comment] 2019-07-11 19:48
Seems like everyone on our team is unable to replicate this. Let's close, and we can re-open if someone can provide a database dump/install where this is happening.

**Closed by benhaynes** 2019-07-11 19:48 UTC
Labels: bug
