### ISSUE TITLE
Can't add Interface on existing field

### ISSUE THREAD

**Issue by ThomasKliszowski** [directus/app#1548] opened 2019-04-24 17:42 UTC
# Bug Report

## Steps to Reproduce

1. Create a field directly on the DB (not in directus)
2. Click on this field in the Directus collection

## Expected Behavior

The "Update Field" form should be displayed, or the "Create Field" (as the directus_fields record does not exist) should not mark the name as already exists.

## Actual Behavior

You get a "Create field" form and you can't create it as the name already exists.

## Other Context & Screenshots

Field:
![image](https://user-images.githubusercontent.com/1174135/56681035-c0769500-66c8-11e9-8763-c788c1dded68.png)

Form:
![image](https://user-images.githubusercontent.com/1174135/56681060-cc625700-66c8-11e9-80cb-245804b9a921.png)

Error:
![image](https://user-images.githubusercontent.com/1174135/56681074-d4ba9200-66c8-11e9-9a64-bc4423f14edc.png)

## Technical Details

- Directus App: 7.3.0

**Comment by rijkvanzanten** [comment] 2019-04-24 18:07
@shealavington

**Comment by shealavington** [comment] 2019-04-24 18:09
Hopping on my computer now, just got in — please ensure you have the latest version, this was that bug that I found Rijk, I thought I'd already pushed a fix for it. 🤔

**Comment by shealavington** [comment] 2019-04-24 18:21
Oooo! Update, just re-read the issue, that's a nice edge-case, good spot. 
It's not what I was working on at-all. 

The screenshot shows an attempt to "Create" a field, which would correctly fail as it exists already, theoretically, you could just click the item and update the interface that way? @ThomasKliszowski

**Comment by shealavington** [comment] 2019-04-24 19:04
@rijkvanzanten What do we think about the following? 

* If the field-name isn't used: Can Continue
* If the field exists, without an interface: Can Continue: Warning
* If the field exists, and has an interface: Can't continue, must update existing.

As shown—You'd be warned that the field already exists, however, you can proceed.
On the other hand, does that not matter, should it just continue showing a '✔️'  ?
![image](https://user-images.githubusercontent.com/16869302/56686395-cb7ef480-66cb-11e9-96a0-729018a06981.png)

**Comment by benhaynes** [comment] 2019-04-24 19:18
So this flow is all for if the admin clicks "New Field" and tries to enter a field that already exists in the database (but doesn't have an interface yet)? I would say that we should show the blank field in the list (it looks like we area already?) and they should click on that to edit it.

I don't think there's a reason to use the New Field button for editing, so I think it should always say `"test" already exists` and _not_ let you go forward.

If there is a field in the database that is not yet tracked in `directus_fields` then I think it should show up in the list like all the others, and you click on it to start managing/configuring it.

Thoughts?

**Comment by benhaynes** [comment] 2019-04-24 19:21
I re-read the issue — and it seems that the _App_ is showing the "New Field" modal. I feel like we should open the Update Field modal with whatever info we have rom the DB (`name`, `datatype`, `length`, `default`, etc).

Sorry for not thoroughly reading the original issue first! 😕

**Comment by shealavington** [comment] 2019-04-24 19:23
I believe that's exactly how it does work @benhaynes.

Currently, we're looking at an "untracked" field, and want to "track" it inside `directus_fields`.
We click on the item and you get to select an interface. 

The issue is currently with my previous code because the name exists, it's refusing to track the file. I'm wondering if it should continue with a Tick to continue to track the file, or if it should show a warning, I guess as this is only for "tracked" fields, it wouldn't need a warning as it's never been in `directus_fields` before...

_(I was mid-writing so thought I'd post haha, just saw your next post too, I did the same thing and skim-read haha)_

**Comment by benhaynes** [comment] 2019-04-24 19:31
Gotcha. How about this then:

We treat these new database columns (in database, not `directus_fields`) the same as Collections. That is to say, we include a "Manage" button in the listing. When you click that button it auto-generates the `directus_fields` row based on the defaults and database schema (the info it was already using to display a default interface).

After that is done, the user can edit the field like normal (all fields are already there).

I think this direction is a bit clearer as to what's happening and avoids muddling up our existing modal logic. 😄

**Comment by ThomasKliszowski** [comment] 2019-04-24 19:31
Thanks for your reactivity guys 🙏.

I agree with @benhaynes.
IMHO, as it's not a new field actually (it's untracked, but this is an internal thing, the user only knows this field exists without Interface), we should display an "Update Form" with the data we are able to fetch.

**Comment by shealavington** [comment] 2019-04-24 19:35
> When you click [the manage] button, it auto-generates the `directus_fields` row based on the defaults and database schema

How will we decide which interface to select by default, `text` + existing schema?

**Comment by benhaynes** [comment] 2019-04-24 19:38
I believe the application already does this. For instance, a tiny end is displayed as a checkbox and varchar is displayed as a text input.

Right @rijkvanzanten

**Comment by shealavington** [comment] 2019-04-24 19:41
True, however, I was thinking: If we're going to generate a row for `directus_fields` should we also select a default "text" interface, or leave that to be updated when going to edit the field?

**Comment by benhaynes** [comment] 2019-04-24 19:42
I think we would select whatever the default instance is for that datatype.

**Comment by shealavington** [comment] 2019-04-24 19:46
Sounds good to me, summary:
* Field is created outside of Directus
* Go to edit a collection's fields
* See field not created by Directus, click "manage"
* Data is generated for `directus_fields` inserting a new row for the item.
* Field is now managed
* Click item, you can manage the data, change the interface and schema
* You can't then edit the field_name. Once set, it's set. (Unless manually ofc.)

Would you have time to mockup the "Manage" button on the view for me?

**Comment by benhaynes** [comment] 2019-04-24 19:49
Exactly right! I can mock things up in a bit, but it should be the exact same as on the settings>collections page (you can use the same button markup/style). The only difference is that you won't be able to un-manage it.

**Comment by shealavington** [comment] 2019-04-24 19:55
![image](https://media.giphy.com/media/1jWbzlKAweG85mBzh1/giphy.gif)

😉 I'll get it done — _I honestly, just wanted to get a GIF in._ 😂

**Comment by shealavington** [comment] 2019-04-24 20:26
I was also wondering, what's going to happen to the click-action for this field, would we just disable editing (clicking) of the field until it's `managed`?

![image](https://user-images.githubusercontent.com/16869302/56691214-4994c880-66d7-11e9-8b39-f9a014afbc38.png)

**Comment by benhaynes** [comment] 2019-04-24 20:45
Yeah, I'd say no click event until it's managed. 

Do we want to remove the `...` icon for un-managed fields? Also, I like where the button is now, but do you think it makes more sense to put it where the interface name goes?

**Comment by shealavington** [comment] 2019-04-24 20:48
The ... is essential for deleting the field of its not wanted, so I would say to keep it, and potentially, I'll have a look at that and see.

**Comment by rijkvanzanten** [comment] 2019-04-24 22:06
We could further visually distinct the non managed field by putting a bit of space between the managed fields and the unmanaged ones. We could even render them in a separate table with column headers that make sense (and that table could show some DB raw info like datatype)

**Comment by benhaynes** [comment] 2019-04-24 23:16
I personally think they should all be in one list... but would be open to discussing.

Do we want to allow deleting a field that is un-managed?

Otherwise, this looks good Shea!! 😄

**Comment by shealavington** [comment] 2019-04-24 23:20
_What I've taken away from the chat above is: If a `field` exists, and the system can't find an interface for it, it will give you the button to `manage` which in theory would select the closest matching interface to the datatype, and save the interface so it can be updated by clicking on it._

Though.. I'm now currently stuck. I'm trying to work out how to lookup what `interface` I should save into `directus_fields` (based on the column `datatype`), but I can't find a way to lookup `datatype -> interface`. 🤷‍♂

**Comment by shealavington** [comment] 2019-04-24 23:59
![image](https://gyazo.com/91083d1d13632c656ad4b09dd1f84e06.gif)

Okay... So it works 😁 Next, I need to await for update/create request to finish before allowing clicking of the field, if you're too quick, it still opens the "Create" version of the modal (as the request may not be finished). 

Thought I'd update you on it "working" haha. It's also so fast _(currently)_, it feels like a "click-to-reveal" haha.

**Comment by rijkvanzanten** [comment] 2019-04-25 00:03
Did you push this up to a branch @shealavington? 🙂  Goodnight!

**Comment by shealavington** [comment] 2019-04-25 00:07
I was doing just that :P G'Night!

https://github.com/shealavington/app/tree/bugs/updating-field

**Comment by benhaynes** [comment] 2019-04-25 02:58
This is awesome!! Thank you Shea! I'll pull and check this out in the morning... such fast turnaround on a fix! 🤗

**Comment by shealavington** [comment] 2019-04-25 07:39
Morning! Before it can be used—I want to ensure the create/update request finishes before allowing clicking on the field. Other than that modification, it works fairly nicely.

_If the field doesn't have an interface, click manage, it will guess the correct interface based on the datatype, you can then click the field to update the field or change the interface._

**Closed** 2019-05-03 16:56 UTC
Labels: bug
