### ISSUE TITLE
Option to keep error notifications on page

### ISSUE THREAD

**Issue by benhaynes** [directus/app#540] opened 2018-07-23 15:10 UTC
Some notifications are longer, or need to be copied... and so maybe they should stay on the page until explicitly dismissed.

**Comment by rijkvanzanten** [comment] 2018-07-23 15:19
This is all possible! We just need to figure out what notifications to leave up. The error messages are very non descriptive (eg "Oops, something went wrong..") by design, with the full error message in the dev console, so I don't think it's that useful to keep them up longer.

**Comment by rijkvanzanten** [comment] 2018-07-23 15:30
Error notifications should stay open until dismissed. This dismiss should be done by hitting a close button (X) in the top right. NOT ON CLICK, cause that would mean you are closing the notification when trying to copy the contents. We should also show the error code as returned by the api in `<small>` in the bottom of the notification, so the developer is able to figure out what went wrong from just the contents of the notifications.

Ref @honzabilek4 something to keep in mind for notifications 😄

**Comment by rijkvanzanten** [comment] 2018-12-13 16:49
We need to define what an error is first. User errors vs system failures

**Comment by honzabilek4** [comment] 2019-02-17 17:49
I can take a look on this.

**Comment by rijkvanzanten** [comment] 2019-02-17 18:55
Thanks @honzabilek4!

**Comment by benhaynes** [comment] 2019-02-17 22:07
Oohh, nice! Thank you @honzabilek4!

**Comment by rijkvanzanten** [comment] 2019-05-20 20:34
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Closed by rijkvanzanten** 2019-05-20 20:34 UTC
Labels: enhancement
