### ISSUE TITLE
Page not found: without id in list page

### ISSUE THREAD

**Issue by rjwismar** [directus/app#1209] opened 2018-12-19 08:10 UTC
# Bug Report

## Steps to Reproduce

1. Go to any collection
2. Click on list item

## Expected Behavior

If in the listview no ID field visible the link handler must also select this id in background to open the item.
Go into the item to edit them.

## Actual Behavior

If no ID field in the listview, the link handler try to open an undefined item.
If a Id field in the listview, the link handler will collect correctly the ID to open the item.
Directus try to open a undefined item and quit this with 'Page Not Found'

### without id in listview

![Image of Screen1](http://api.ssb-festival.de/screen1.png)
![Image of Screen2](http://api.ssb-festival.de/screen2.png)

### with id in listview

![Image of Screen3](http://api.ssb-festival.de/screen3.png)
![Image of Screen4](http://api.ssb-festival.de/screen4.png)

**Comment by rijkvanzanten** [comment] 2018-12-19 14:58
This is a duplicate of https://github.com/directus/app/issues/1188. It has been fixed on `master` already and will be released today 🙂

**Closed by rijkvanzanten** 2018-12-19 14:58 UTC
