### ISSUE TITLE
Failed install in xampp

### ISSUE THREAD

**Issue by King-GO** [directus/app#2297] opened 2019-12-07 15:47 UTC
Directus version 8.1.0
XAMPP with PHP version: 7.3.4; Apache/2.4.39
mod_rewrite is turned on

The last step of installation fails with:

```
api[directus].ERROR: Zend\Db\Adapter\Exception\InvalidQueryException: Statement could not be executed (42S02 - 1146 - Table 'directus.directus_settings' doesn't exist) in C:\xampp\htdocs\directus\vendor\zendframework\zend-db\src\Adapter\Driver\Pdo\Statement.php:244
```

<details>
<summary>Full stack trace</summary>
<pre>
#0 C:\xampp\htdocs\directus\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(239): Zend\Db\Adapter\Driver\Pdo\Statement->execute
#1 C:\xampp\htdocs\directus\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(209): Zend\Db\TableGateway\AbstractTableGateway->executeSelect
#2 C:\xampp\htdocs\directus\vendor\zendframework\zend-db\src\TableGateway\AbstractTableGateway.php(196): Zend\Db\TableGateway\AbstractTableGateway->selectWith
#3 C:\xampp\htdocs\directus\src\core\Directus\Application\CoreServicesProvider.php(1112): Zend\Db\TableGateway\AbstractTableGateway->select
#4 C:\xampp\htdocs\directus\vendor\pimple\pimple\src\Pimple\Container.php(118): Directus\Application\CoreServicesProvider->Directus\Application\{closure}
#5 C:\xampp\htdocs\directus\src\core\Directus\Container\Container.php(27): Pimple\Container->offsetGet
#6 C:\xampp\htdocs\directus\src\helpers\settings.php(20): Directus\Container\Container->get
#7 C:\xampp\htdocs\directus\src\helpers\settings.php(35): Directus\get_directus_settings
#8 C:\xampp\htdocs\directus\src\helpers\settings.php(142): Directus\get_directus_setting
#9 C:\xampp\htdocs\directus\src\core\Directus\Application\Http\Middleware\ProxyMiddleware.php(16): Directus\get_trusted_proxies
#10 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#11 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#12 [internal function]: Slim\DeferredCallable->__invoke
#13 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#14 C:\xampp\htdocs\directus\vendor\akrabat\ip-address-middleware\src\IpAddress.php(113): Slim\App->Slim\{closure}
#15 [internal function]: RKA\Middleware\IpAddress->__invoke
#16 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#17 [internal function]: Slim\DeferredCallable->__invoke
#18 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#19 C:\xampp\htdocs\directus\src\core\Directus\Application\Http\Middleware\CorsMiddleware.php(71): Slim\App->Slim\{closure}
#20 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#21 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#22 [internal function]: Slim\DeferredCallable->__invoke
#23 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#24 C:\xampp\htdocs\directus\src\core\Directus\Application\Http\Middleware\ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#25 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#26 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#27 [internal function]: Slim\DeferredCallable->__invoke
#28 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#29 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#30 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\App.php(392): Slim\App->callMiddlewareStack
#31 C:\xampp\htdocs\directus\vendor\slim\slim\Slim\App.php(297): Slim\App->process
#32 C:\xampp\htdocs\directus\src\core\Directus\Application\Application.php(161): Slim\App->run
#33 C:\xampp\htdocs\directus\public\index.php(5): Directus\Application\Application->run [] []
</pre>
</details>

**Comment by rijkvanzanten** [comment] 2019-12-09 15:04
How did you install @King-GO? Through the admin interface, API directly, or the CLI?

**Comment by King-GO** [comment] 2019-12-09 15:12
download [directus-8.1.0](https://github.com/directus/directus/releases)
unzip to c:\xampp\htdocs\directus
create database via phpmyadmin ;
go to 
http://xx/directus/admin/
install

**Comment by King-GO** [comment] 2019-12-15 02:44
import SQL, 
error
directus_activity
#1071 - Specified key was too long; max key length is 767 bytes

**Comment by rijkvanzanten** [comment] 2019-12-16 15:22
Make sure you're using the required version (or higher) of MySQL. Directus requires MySQL 5.7+; that error sounds like you're on 5.6

**Comment by King-GO** [comment] 2019-12-17 00:13
XAMPP v3.2.3
Database Server version: 10.1.38-MariaDB -


[https://mariadb.com/kb/en/library/mariadb-10138-release-notes/](url)

**Comment by benhaynes** [comment] 2019-12-17 00:21
This is almost certainly caused by not checking the Directus requirements...

https://docs.directus.io/advanced/requirements.html#sql

> In theory, Directus should work with MySQL drop-in alternatives such as MariaDB (10.2+) or Percona Server. However, these are not officially supported so you should proceed at your own risk.

Please upgrade to MariaDB 10.2+ and see if the issue persists. I'll close this in the meantime.

**Closed by benhaynes** 2019-12-17 00:21 UTC
Labels: needs more info
