### ISSUE TITLE
Translation interface is сleared when "Save and Stay"

### ISSUE THREAD

**Issue by dsivokhin** [directus/app#1094] opened 2018-11-07 09:20 UTC
# Bug Report
When you use "Save and stay" in the translation interface fields are cleared. In DB values save ok.

## Steps to Reproduce

1. Go to edit item with translation interface and fill fields
2. Click on "Save and stay"

## Other Context & Screenshots

![default](https://user-images.githubusercontent.com/4669992/48121835-09f03680-e287-11e8-82e0-9b193bb876ea.png)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Directus App: 7.0.5
- Install Method: demo app

**Comment by benhaynes** [comment] 2018-11-07 12:10
Thanks @dsivokhin – this is a duplicate of https://github.com/directus/app/issues/556

**Closed by benhaynes** 2018-11-07 12:10 UTC
