### ISSUE TITLE
Files interface only works on first save

### ISSUE THREAD

**Issue by Kinzi** [directus/app#1573] opened 2019-04-30 11:16 UTC
# Bug Report

The interface for multiple files works only properly on first save. Every update will cause an error like duplicating all relations, or when deleting a file often with a broken SQL query

## Steps to Reproduce

1. Go to your demo installation and add a files interface to any collection. Autogenerate the rel table.
2. Choose a few existing files, save
3. Choose a few more files save again

## Expected Behavior

Relations are updated correctly

## Actual Behavior
See gif:

![files_error](https://user-images.githubusercontent.com/6689405/56958254-71aa7e80-6b52-11e9-9e65-7b9a77802274.gif)

**Comment by benhaynes** [comment] 2019-04-30 13:07
Is this a duplicate of this one? https://github.com/directus/app/issues/1294

**Comment by Kinzi** [comment] 2019-06-17 06:33
So the behavior of this changed. I'm on the latest `build` branches for app and api.

Now this happens:

1. have a files interface with a few relations
2. select "select existing" to add another pic from the library
3. save & reload page
4. file interface broken (doesn't show up)
5. Database gets new broken relation entries

Broken (unneccesary) entries in db:

<img width="407" alt="Bildschirmfoto 2019-06-17 um 09 28 15" src="https://user-images.githubusercontent.com/6689405/59583012-acf11480-90e2-11e9-9794-279e9b5c698b.png">

Broken interface after reload:
<img width="693" alt="Bildschirmfoto 2019-06-17 um 09 31 35" src="https://user-images.githubusercontent.com/6689405/59583040-c7c38900-90e2-11e9-9e9c-c84f38da8a52.png">

**Comment by shealavington** [comment] 2019-06-17 08:57
Ref: https://github.com/directus/api/issues/1015#issuecomment-502335477

Should be fixed for the next release.

**Comment by Kinzi** [comment] 2019-06-17 10:04
@shealavington when is this planned to be released in the build branch?

**Comment by Kinzi** [comment] 2019-06-17 12:39
@shealavington Also funny enough after copying the updates from you linked commit I get my original error again: the pictures duplicate.

So instead of null, no I get this (every relation twice):

<img width="406" alt="Bildschirmfoto 2019-06-17 um 15 38 51" src="https://user-images.githubusercontent.com/6689405/59604870-0fafd380-9116-11e9-8996-d2b42eccf502.png">

**Comment by Kinzi** [comment] 2019-06-24 10:10
Did some investigation here and it seems that this might be an API issue?!?

When you expect the PATCH request in the console it has the correct Payload of whatever changes you make to the files field - however the response has the multitude as described above.

Example patch payload:

```
{
    "images": [{
        "id": 123,
        "item": {
            "id": 12,
            ...
        },
        "image": {
           "id": 13,
            ...
        },
        "$delete": true
    }, {
        "image": {
            "id": 14,
            ...
        }
    }, {
        "image": {
             "id": 15,
            ...
        }
    }]
}
```

Response:

```
{
    "data": {
        "id": 299,
        ...
        "images": [{
            "id": 885,
            "tour": {
            },
            "image": {
                "id": 13,
                ...
            }
        },{
            "id": 886,
            "tour": {
            },
            "image": {
                "id": 14,
                ...
            }
        },{
            "id": 885,
            "tour": {
            },
            "image": {
                "id": 15,
                ...
            }
        },{
            "id": 885,
            "tour": {
            },
            "image": {
                "id": 13,
                ...
            }
        },{
            "id": 886,
            "tour": {
            },
            "image": {
                "id": 14,
                ...
            }
        },{
            "id": 885,
            "tour": {
            },
            "image": {
                "id": 15,
                ...
            }
        }
]}
```

**Comment by Kinzi** [comment] 2019-06-24 10:13
@benhaynes  
Sorry for the push, but can you please 🙏priorize this guys? It's been up here for a while now and I kinda need it :).

**Comment by benhaynes** [comment] 2019-06-24 13:40
We're going as fast as we can. We're in the middle of several client projects at the moment (so we can afford to keep Directus running) so our time is limited.

@bjgajjar @hemratna  — any thoughts on if this is actually an API issue?

All the research/comments here are great as they help us resolve things faster. Thank you!

**Comment by rijkvanzanten** [comment] 2019-07-31 21:03
This should be fixed in https://github.com/directus/app/pull/1881

Please let me know if it still isn't working for you and we can re-investigate.

**Closed by rijkvanzanten** 2019-07-31 21:03 UTC
Labels: bug
