### ISSUE TITLE
Interface: Store latitude and longitude in separate fields in map

### ISSUE THREAD

**Issue by benhaynes** [directus/app#791] opened 2018-09-08 01:16 UTC
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# store latitude and longitude in separate fields in map interface
### :+1: = 1
*Created 4 months ago by @aiomaster*
 

-----
### @aiomaster – :+1: (4 months ago)
It would be cool to have an option that the geo-coordinates of the map interface could be stored in two different columns with FLOAT-type. The current implementation stores it as a single string with a "," to separate lat and lng. I want to show a map with markers in the frontend and don't want to split it everytime. Besides I want to filter the rows based on the current map bounds so I need to compare the lat and lng with them.

**Comment by rijkvanzanten** [comment] 2018-09-08 01:17
Duplicate of https://github.com/directus/app/issues/769

**Closed by rijkvanzanten** 2018-09-08 01:17 UTC
Labels: duplicate
