### ISSUE TITLE
Change profile menu hover behavior

### ISSUE THREAD

**Issue by jooola** [directus/app#2130] opened 2019-10-11 22:20 UTC
Sorry for the half written email, miss clicked the save button.

The bottom left profile menu opens automatically on hover. I usually click on such menu so they open. The problem is that when clicking on it and hover triggers the menu opening, I click on logout by accident.

Is there a way to change this behavior to something less prone to such accidents ? Disable hover and open on click, or move the logout button higher ?

This is just a small, but annoying UX/UI bug I would be glad to get ride of.

**Comment by bjgajjar** [comment] 2019-10-12 11:39
Maybe https://github.com/directus/app/pull/2064 will resolve your issue :) 
Closing this as duplicate of https://github.com/directus/app/issues/2050

**Closed by bjgajjar** 2019-10-12 11:39 UTC

**Comment by benhaynes** [comment] 2019-10-12 23:08
Thanks @jooola — to paraphrase the other ticket, this will be solved in the upcoming design change. The hover menu will be gone, so there won't be any more accidental clicks. In the meantime, we have the PR @WoLfulus made. 👍

**Comment by jooola** [comment] 2019-10-13 00:30
Glad to here this ! Thanks for this !
Cheers
