### ISSUE TITLE
Errors when creating new field

### ISSUE THREAD

**Issue by LukasNavickas** [directus/app#2133] opened 2019-10-11 09:19 UTC
When creating new field (dropdown or WYSIWYG), there is an error after clicking "Create".
Moreover, after the page is refreshed, the field is created with an incorrect type (text area instead of WYSIWYG editor). 
I attach a video of the actual behaviour: https://www.loom.com/share/f41e49f159a547c3ba3b0295ae081064

# Bug Report

## Steps to Reproduce

Check the Video Walkthrough https://www.loom.com/share/f41e49f159a547c3ba3b0295ae081064

## Expected Behavior
Dropdown and WYSIWYG are created properly.

## Actual Behavior
Dropdown and WYSIWYG are NOT created properly, String (Text Area) is assigned automatically.

## Technical Details

- Device: Desktop
- OS: Windows 10
- Database: MySQL 
- Install Method: latest version (I use docker container)

**Comment by benhaynes** [comment] 2019-10-12 23:24
Hey @LukasNavickas — can you confirm which version of Directus you are actually using? You can see your App version by hovering over "Powered by Directus" at the bottom of the Login page. The API and App versions are also included in the response from the Server Information endpoint (located at /).

We have several legacy Docker containers, so you might be on an older version. 🔔 @WoLfulus

**Comment by WoLfulus** [comment] 2019-10-13 03:25
Might be related to one ticket I once opened about not being able to created fields that I previously deleted. I don't know if this was resolved at all, but had I think it had something to do with having a table that has user fields (created by, modified by) in it. After I deleted a field, I couldn't create one with the same name anymore.

Maybe you can try creating this field with another name just to see if it's the same issue? (I completely stopped using user fields so I don't know what is the status of this one)

**Comment by bjgajjar** [comment] 2019-10-14 09:36
> Might be related to one ticket I once opened about not being able to created fields that I previously deleted. I don't know if this was resolved at all, but had I think it had something to do with having a table that has user fields (created by, modified by) in it. After I deleted a field, I couldn't create one with the same name anymore.

Hey Wolfulus - Thanks for mentioning the scenario but It does not reproducible right now.

**Comment by nlebreton** [comment] 2019-10-15 13:37
Hi ,

Please find below the stacktrace in the API when this issue occurs:

`[2019-10-15 10:27:58] api[_].ERROR: Directus\Database\Exception\InvalidQueryException: Failed generating the SQL query. in /var/www/src/core/Directus/Database/TableGateway/BaseTableGateway.php:815
Stack trace:
#0 /var/www/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert
#1 /var/www/src/core/Directus/Database/TableGateway/BaseTableGateway.php(390): Zend\Db\TableGateway\AbstractTableGateway->insert
#2 /var/www/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(412): Directus\Database\TableGateway\BaseTableGateway->addRecordByArray
#3 /var/www/src/core/Directus/Services/TablesService.php(863): Directus\Database\TableGateway\RelationalTableGateway->createRecord
#4 /var/www/src/core/Directus/Services/TablesService.php(564): Directus\Services\TablesService->addFieldInfo
#5 /var/www/src/endpoints/Fields.php(54): Directus\Services\TablesService->addColumn
#6 [internal function]: Directus\Api\Routes\Fields->create
#7 /var/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#8 /var/www/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#9 /var/www/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#10 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#11 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#12 [internal function]: Slim\DeferredCallable->__invoke
#13 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#14 /var/www/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(121): Slim\Route->Slim\{closure}
#15 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#16 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#17 [internal function]: Slim\DeferredCallable->__invoke
#18 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#19 /var/www/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#20 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#21 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#22 [internal function]: Slim\DeferredCallable->__invoke
#23 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#24 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#25 /var/www/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#26 /var/www/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#27 /var/www/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#28 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#29 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#30 [internal function]: Slim\DeferredCallable->__invoke
#31 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#32 /var/www/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#33 /var/www/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#34 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#35 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#36 [internal function]: Slim\DeferredCallable->__invoke
#37 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#38 /var/www/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#39 [internal function]: RKA\Middleware\IpAddress->__invoke
#40 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#41 [internal function]: Slim\DeferredCallable->__invoke
#42 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#43 /var/www/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#44 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#45 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#46 [internal function]: Slim\DeferredCallable->__invoke
#47 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#48 /var/www/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(54): Slim\App->Slim\{closure}
#49 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#50 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#51 [internal function]: Slim\DeferredCallable->__invoke
#52 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#53 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#54 /var/www/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#55 /var/www/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#56 /var/www/src/core/Directus/Application/Application.php(161): Slim\App->run
#57 /var/www/public/index.php(5): Directus\Application\Application->run [] []
172.19.0.1 - - [15/Oct/2019:13:27:58 +0000] "POST /_/fields/banner HTTP/1.1" 500 718 "http://localhost:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"`

**Comment by LukasNavickas** [comment] 2019-10-15 13:38
> Hi ,
> 
> Please find below the stacktrace in the API when this issue occurs:
> 
> `[2019-10-15 10:27:58] api[_].ERROR: Directus\Database\Exception\InvalidQueryException: Failed generating the SQL query. in /var/www/src/core/Directus/Database/TableGateway/BaseTableGateway.php:815 Stack trace: #0 /var/www/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert #1 /var/www/src/core/Directus/Database/TableGateway/BaseTableGateway.php(390): Zend\Db\TableGateway\AbstractTableGateway->insert #2 /var/www/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(412): Directus\Database\TableGateway\BaseTableGateway->addRecordByArray #3 /var/www/src/core/Directus/Services/TablesService.php(863): Directus\Database\TableGateway\RelationalTableGateway->createRecord #4 /var/www/src/core/Directus/Services/TablesService.php(564): Directus\Services\TablesService->addFieldInfo #5 /var/www/src/endpoints/Fields.php(54): Directus\Services\TablesService->addColumn #6 [internal function]: Directus\Api\Routes\Fields->create #7 /var/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func #8 /var/www/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke #9 /var/www/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke #10 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke #11 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array #12 [internal function]: Slim\DeferredCallable->__invoke #13 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func #14 /var/www/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(121): Slim\Route->Slim\{closure} #15 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke #16 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array #17 [internal function]: Slim\DeferredCallable->__invoke #18 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func #19 /var/www/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure} #20 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke #21 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array #22 [internal function]: Slim\DeferredCallable->__invoke #23 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func #24 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure} #25 /var/www/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack #26 /var/www/vendor/slim/slim/Slim/App.php(503): Slim\Route->run #27 /var/www/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke #28 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke #29 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array #30 [internal function]: Slim\DeferredCallable->__invoke #31 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func #32 /var/www/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure} #33 /var/www/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke #34 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke #35 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array #36 [internal function]: Slim\DeferredCallable->__invoke #37 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func #38 /var/www/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure} #39 [internal function]: RKA\Middleware\IpAddress->__invoke #40 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array #41 [internal function]: Slim\DeferredCallable->__invoke #42 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func #43 /var/www/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure} #44 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke #45 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array #46 [internal function]: Slim\DeferredCallable->__invoke #47 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func #48 /var/www/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(54): Slim\App->Slim\{closure} #49 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke #50 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array #51 [internal function]: Slim\DeferredCallable->__invoke #52 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func #53 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure} #54 /var/www/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack #55 /var/www/vendor/slim/slim/Slim/App.php(297): Slim\App->process #56 /var/www/src/core/Directus/Application/Application.php(161): Slim\App->run #57 /var/www/public/index.php(5): Directus\Application\Application->run [] [] 172.19.0.1 - - [15/Oct/2019:13:27:58 +0000] "POST /_/fields/banner HTTP/1.1" 500 718 "http://localhost:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"`

Exactly. The version is 7.11.0

**Comment by nlebreton** [comment] 2019-10-15 13:39
The docker image is directus-api:v2.6.0-apache.

**Comment by bjgajjar** [comment] 2019-10-16 07:19
@nlebreton @LukasNavickas - If you check the response of that API; either in postman or in browser [Network tab]; you will get the query too.

Can you please provide that? So I can check the issue.

If you find it private then you guys can join our slack [channel](https://directus.chat) too. You can find me **@binal** over there and connect in a private message.

**Comment by nlebreton** [comment] 2019-10-16 08:20
@bjgajjar 

If by "request", you mean "http request", it should be the one at the end of the log :

`[15/Oct/2019:13:27:58 +0000] "POST /_/fields/banner HTTP/1.1" 500 718 "http://localhost:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"`

Is this what you expected?

**Comment by bjgajjar** [comment] 2019-10-16 08:53
@nlebreton - Thanks for the helping. Lukas already connected in slack :) I'll update you soon on this.

**Comment by urvashithakar** [comment] 2019-10-24 11:51
Agree with @bjgajjar.
This issue is not reproducible in live demo server.

**Comment by rijkvanzanten** [comment] 2019-11-20 18:37
I'm suspecting it might've been the same problem as https://github.com/directus/app/issues/1149

Either way, I'm not able to reproduce this on my end either.. so I'll have to close this for now until we figure out what causes this and how to reproduce it

**Closed by rijkvanzanten** 2019-11-20 18:37 UTC
Labels: not reproducible
