### ISSUE TITLE
Save the prompt network error after M2M and o2m select items

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1922] opened 2019-08-04 02:57 UTC
## Bug Report

#1877 This is an extension of issue 1877

The speed is still very slow. If you select more than one, there will be Network Error.
I use git clone -b develop https://github.com/directus/app

https://streamable.com/rn84q

## Technical Details

- Device: [Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.3.1]
- APP Version: [git clone -b develop https://github.com/directus/app]

**Comment by urvashithakar** [comment] 2019-08-28 09:01
Hey @cdwmhcc,

I am not able to replicate this in the latest build. Could you try updating to the latest build and let me know if the problem still occurs for you?

For your reference;
>  git clone -b develop

The `develop` branch is for the development purpose so you may face issues over there. But we have a stable branch `master`. So  I would say you must use it.

**Comment by bjgajjar** [comment] 2019-08-31 05:55
As this issue is not reproducible in the latest version; I am closing this. Feel free to reopen it.

**Comment by cdwmhcc** [comment] 2019-09-03 14:42
> As this issue is not reproducible in the latest version; I am closing this. Feel free to reopen it.

Oh, no!
You can't reproduce it because your collection fields are too few. This problem persists. You can use the database I gave you for testing.

**Comment by cdwmhcc** [comment] 2019-09-03 14:59
@rijkvanzanten 
https://streamable.com/1gx9c
Latest version，The problem still exists.

**Comment by benhaynes** [comment] 2019-09-03 15:03
> SLOW
Haha, thanks @cdwmhcc

**Comment by cdwmhcc** [comment] 2019-09-03 15:08
## Q1: It just adds an ID, and it's not clear why all the data should be rewritten?

![image](https://user-images.githubusercontent.com/8030134/64185186-4688c080-ce9f-11e9-8c43-1d40b5ee3eab.png)
![image](https://user-images.githubusercontent.com/8030134/64185356-96678780-ce9f-11e9-9a69-cc1f80fc8f55.png)

## Q2: If I only open `Allow Select`, there is no need to rewrite the data at all.

![image](https://user-images.githubusercontent.com/8030134/64184988-f14caf00-ce9e-11e9-9a2c-b0a51d02eb13.png)

**Comment by cdwmhcc** [comment] 2019-09-03 15:15
> > SLOW
> 
> Haha, thanks @cdwmhcc

Haha，I have not been able to visit GitHub recently, but today is finally OK!!

**Comment by bjgajjar** [comment] 2019-09-10 07:16
@cdwmhcc - It will be a great help if you can provide your SQL dump. I ping you in the slack message. You can provide over there.

**Comment by cdwmhcc** [comment] 2019-09-11 02:58
> @cdwmhcc - It will be a great help if you can provide your SQL dump. I ping you in the slack message. You can provide over there.

OK

**Comment by tonydamage** [comment] 2019-12-12 16:37
I was facing similar issue - the M2M API request- triggers full update of referenced records even if there is no change in referenced record itself (found out in model where user should not be able to edit referenced field).

This behaviour could be easily fixed if the M2M & M2O interfaces will not send full referenced record in JSON, but only partial record (ID) if the item was not modified (API server then skips update on referenced record).

**Comment by rijkvanzanten** [comment] 2019-12-12 16:51
> This behaviour could be easily fixed

I wish it was easy @tonydamage. See https://github.com/directus/app/issues/1883, and the changes in https://github.com/directus/app/issues/1882, which is the aftermath of https://github.com/directus/app/commit/f357bb67126a0dd0bd54627b65b5c5edd491ac55. The O2M already does that to an extent, but there's all sorts of issues with nested relational and JSON / Array based values. We need to remodel the way interfaces receive and stage data to be saved in order to truly resolve this, as of right now the only way to get around this is to do diffing within the interface and keep a separate internal state for its value to have a diff between what's displayed, saved, and staged.

**Comment by tonydamage** [comment] 2019-12-12 17:12
@rijkvanzanten : Looking at the JS code for `M2M` interface I can see that. 
Easy win (I will try that one myself) is in `checkboxes-relational` since they are also affected, but they do not provide way to edit content.

The `M2M` use-case is different - since from M2M you can create and edit new items (and nested collections).

**Comment by andgar2010** [comment] 2020-01-25 20:12
I was facing similar issue.
When you change an item and select dropdown list m2o 
![msedge_2vL4DD3g0r](https://user-images.githubusercontent.com/19521054/73126641-666e6d00-3f83-11ea-930f-c0324a5e6a23.png)

and save you get an error message:
![image](https://user-images.githubusercontent.com/19521054/73126632-3921bf00-3f83-11ea-8b1a-43aa6f31aab5.png)

![image](https://user-images.githubusercontent.com/19521054/73126714-fad8cf80-3f83-11ea-8d0d-7d0b7f13e4f9.png)

![image](https://user-images.githubusercontent.com/19521054/73126725-0e843600-3f84-11ea-9e28-cab8cc9d8115.png)


But I made refresh page and shows item is saved, but M2O show error get by dropdown template for missing label "CREADA"
![image](https://user-images.githubusercontent.com/19521054/73126787-d16c7380-3f84-11ea-8e49-3b0875dc5dba.png)

**Comment by andgar2010** [comment] 2020-01-25 20:17
@benhaynes @rijkvanzanten 
I was facing similar issue.
When you change an item and select dropdown list m2o 
![msedge_2vL4DD3g0r](https://user-images.githubusercontent.com/19521054/73126641-666e6d00-3f83-11ea-930f-c0324a5e6a23.png)

and save you get an error message:
![image](https://user-images.githubusercontent.com/19521054/73126632-3921bf00-3f83-11ea-8b1a-43aa6f31aab5.png)

![image](https://user-images.githubusercontent.com/19521054/73126714-fad8cf80-3f83-11ea-8d0d-7d0b7f13e4f9.png)

![image](https://user-images.githubusercontent.com/19521054/73126725-0e843600-3f84-11ea-9e28-cab8cc9d8115.png)


But I made refresh page and shows item is saved, but M2O show error get by dropdown template for missing label "CREADA"
![image](https://user-images.githubusercontent.com/19521054/73126842-93238400-3f85-11ea-8f38-84a848e1a998.png)

**Comment by rijkvanzanten** [comment] 2020-01-31 00:35
I can't reproduce the original issue. @andgar2010 your issue looks like something else than mentioned above. Could you please [open a new issue](https://github.com/directus/api/issues/new) for that? 🙂

**Closed by rijkvanzanten** 2020-01-31 00:35 UTC
Labels: bug
