### ISSUE TITLE
Clone data from one directus installation to another

### ISSUE THREAD

**Issue by siauderman** [directus/app#2829] opened 2020-05-27 10:01 UTC
There should be an easy way to migrate all data and files from one directus installation to another, a 1-click solution preferably.

**Comment by benhaynes** [comment] 2020-05-27 13:06
Duplicate of: https://github.com/directus/api/issues/31

Requires the API endpoints...

**Closed by benhaynes** 2020-05-27 13:06 UTC

**Comment by rijkvanzanten** [comment] 2020-05-28 21:59
@siauderman Copying the whole installation + a dump of the DB is all it takes to make a full identical copy

**Comment by Bloc67** [comment] 2020-06-08 13:31
> @siauderman Copying the whole installation + a dump of the DB is all it takes to make a full identical copy

Does that mean all installation files, even configurations for database etc?

**Comment by rijkvanzanten** [comment] 2020-06-08 13:32
The database schema information is stored in the database as well @Bloc67 :)
