### ISSUE TITLE
Change field note input from type text to textarea?

### ISSUE THREAD

**Issue by dev7ch** [directus/app#1810] opened 2019-07-03 09:03 UTC
# Feature Request

![image](https://user-images.githubusercontent.com/15183757/60578791-21ce7a80-9d82-11e9-9cfb-275d9dcb27b1.png)

Change Field Note input from type text to textarea which is resizable (and you can input html or MD)

## What problem does this feature solve?

Better description for input mask, e.g assume you wnat to add a link into the field note ...

## How do you think this should be implemented?
change field type

## Would you be willing to work on this?

Yes, if approved i gonna make a PR and solve it

**Comment by benhaynes** [comment] 2019-07-03 12:44
We most likely won't be supporting HTML, but we already support markdown. I think that satisfies this request, right?

**Comment by dev7ch** [comment] 2019-07-03 12:48
Yes, markdown input would satisfy it as well.

Currently i was able to use `<br >`  and `<a href=""></a>` Tags but with a limited lenght. (LONGTEXT or BLOB  DB Schema Type could be better i believe)

**Comment by dev7ch** [comment] 2019-07-03 12:50
Another thing i was thinking. Is a Tooltip really enough as description?

What`s about having 2 fields here, a Tooltip text and  a Note textarea input?

**Comment by benhaynes** [comment] 2019-07-03 12:57
The main issue is finding a design that works for inline notes. If they go above the interface then the alignment of everything is off... and they are less noticeable after the interface (especially for long/tall interfaces). So that's the problem to solve first.

**Comment by dev7ch** [comment] 2019-07-03 14:59
mmh yeas indeed.

Whats about this?
![image](https://user-images.githubusercontent.com/15183757/60602274-c87f3f00-9db3-11e9-98c8-3838ece877ea.png)

I think it would not affect the layout (could be position:absolute), and adding a toggler if the desc on the bottom is omre than one line

**Comment by benhaynes** [comment] 2019-07-03 20:43
So you're saying it should go below the interface? Is the red text the note in this example?

**Comment by dev7ch** [comment] 2019-07-04 13:27
Yes, but i ll make a sketch/design with better explanation later

**Comment by dev7ch** [comment] 2019-07-06 16:16
![image](https://user-images.githubusercontent.com/15183757/60758435-e698a980-a016-11e9-841f-41229a0f3292.png)

The idea was/is to have a fixed space around 18px under the input field to put important inforation or links to explanations under the field and just see the without hovering or clinking a icon.

Due there is enough padding/margin between the input fields i dont think it will break the layout and design.

There is a trick with scss and line-height how you could count one line, and the toggler/dropdown of longer infos could be an overlay (to not break the display:grid;)

**Comment by benhaynes** [comment] 2019-07-08 15:05
Thanks @dev7ch — this is pretty close to what we had before moving to the icon (except that this has a collapsed fixed height).

I don't think there is any issue with having the text expanding _below_ the interface (as you have it here) so I don't think we'd need to accordion it. The issue was when it was _above_ the interface, since then it misaligned things depending on if there was a note and how tall it was.

So the question becomes: if we wanted to have two different note styles (hidden behind icon and this exposed note) how would we intuitively/simply let admins setup notes?

We can solve the "link click" issue on the current notes... but we need to decide if it makes sense to have two different types of notes.

@rijkvanzanten — thoughts?

**Comment by dev7ch** [comment] 2019-07-08 15:40
thanks @benhaynes for taking time, yes an option could help a bit.

But the main issue is the `text` should be a `textarea` to let you enter related information without restrictions

**Comment by dev7ch** [comment] 2019-07-08 15:43
I just thought the layout could be broken in 50/50 width of to input fields if there are multiple lines.

in general it feels for me a text input field is good for a tooltip, but a tooltip is critical design for important related information ( e.g. 2 lines or more)

**Comment by benhaynes** [comment] 2019-07-08 16:57
Gotcha. Rijk is off today, but let's get his thoughts on this (re: tooltip vs note below interface) and then we can update the Settings as needed.

**Comment by rijkvanzanten** [comment] 2019-07-09 15:53
We tried having the note below, but having multiple lines will cause spacing issues

**Comment by benhaynes** [comment] 2019-07-09 17:26
The spacing issues are when the note is above... so technically this won't cause too much trouble for layout. I don't think we need to make this expand on click tough — since that hides info and then we might as well just use/fix the icon notes.

I just don't know if splitting notes into two possible designs is the right solution (seems more complex). Perhaps we focus on a better icon note toggle that allows for clicking links?

As for using a text area instead of a text input: if you're creating complex multi-line notes then I would say that a "Note Interface" might be a better option. Then you have more control and can have very complex explanations/layouts for each field (including 50/50 widths).

**Comment by dev7ch** [comment] 2019-07-10 14:22
> I just don't know if splitting notes into two possible designs is the right solution (seems more complex). Perhaps we focus on a better icon note toggle that allows for clicking links?

yes a one field would be better but if you like tooltips you could keep that text field.

Whats about alternatively place the text area inside/under the advanced Section on field creation?

Again i think it is very bad design for a note with content which should help the user, tooltips are for short **additional informations**  (ofc depends on personal view).

>  then I would say that a "Note Interface" might be a better option

Do you mean the "Divider Interface"?

I haven`t found it the "Note interface", the "Divider interface" has also some issues (restrictions) and this would mean a huge click overload (Assume you have 70 field to add, this means 140 fields with description, think of ordering, etc :( )

I think the most clean way would be to add 2 fields: 

- field `text` named "tooltip" for tooltips
- field `textarea` named "note" for notes with links and filling instructions (could be in in advanced accordion)

Right now i am useing directus for our production with around > 200 additional commits and sadly this seems too increase.

I really hope some day this can go back to 0.

**Comment by benhaynes** [comment] 2019-07-16 15:23
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Closed by benhaynes** 2019-07-16 15:23 UTC
Labels: enhancement, question

**Comment by benhaynes** [comment] 2019-07-16 15:32
We'll keep one field in Settings for adding a _Note_, and it can stay where it is (not hidden under advanced). We can discuss making this a textarea (as opposed to a text input).

Yes, I meant the divider interface. We could also create a new dedicated `note` interface that is more specifically for this use.

We have another ticket to address the [clickability](https://github.com/directus/app/issues/1812) — so this one should only be for changing to the textarea in Settings. Let's see if we get some community 👍 here.

**Comment by lluishi93** [comment] 2019-08-01 08:20
@benhaynes Are you finally going to enable some kind of red color note or something similar below the fields? If the problem is spacing, maybe you could limit the note's character count somehow, or put a toggle associated with the note, to decide if it's tooltip or text below the field.

**Comment by benhaynes** [comment] 2019-08-03 16:15
https://github.com/directus/app/pull/1919

**Comment by dev7ch** [comment] 2019-08-03 16:19
oh glad to see this ref :)
