### ISSUE TITLE
Table View: In-Line Item Edits

### ISSUE THREAD

**Issue by srjrol** [directus/app#1442] opened 2019-04-01 23:31 UTC
# Feature Request
I think a great feature could be to allow item edits from within the row of a table.  Here is my crude representation:

![image](https://user-images.githubusercontent.com/34398302/55365934-1b431500-54ac-11e9-8085-d66cdc20c9ed.png)

## What problem does this feature solve?
No longer have to load item view to make a change or reload table when returning.
## How do you think this should be implemented?
I think an edit button added to the row which changes it into an editable state would work great.  I think it's nice if we could include the field icons (email in this example).  This could also be toggled via the INFO menu perhaps.  Not sure about the placement of the edit button/column.

https://demos.telerik.com/kendo-ui/grid/editing-inline
## Would you be willing to work on this?
Sure but I'm not much of a coder.

**Comment by srjrol** [comment] 2019-04-01 23:40
I think one placement for the edit button could be where it already resides for editing mulltiple rows but have it display for a single row.  It is a bit of an extra step but possibly easier to implement.

![image](https://user-images.githubusercontent.com/34398302/55366271-935e0a80-54ad-11e9-8a8b-18491ba8f1ac.png)

**Comment by benhaynes** [comment] 2019-04-02 15:47
Hey @srjrol — love it!

This is actually a duplicate of: https://github.com/directus/app/issues/723 so I'll close it here. I like your mock-ups though, and editing a row instead of a cell might be better... we'll have to test. Perhaps you can add these images to the main ticket?

My main question is how do we handle larger interfaces (eg: wysiwyg, text, maps, O2M, etc). We could either:

* Not allow them to be edited
* Expand the row to fit the larger height
* Open the interface in a modal (only works for editing individual cells one at a time)
* Edit the _raw_ value in a text-input (not very user friendly)

Thoughts?

**Closed by benhaynes** 2019-04-02 15:47 UTC
