### ISSUE TITLE
Textboxes 8.0.0-rc2 are broken on Safari and Firefox

### ISSUE THREAD

**Issue by lbrpdx** [directus/app#2246] opened 2019-11-27 16:07 UTC
On a freshly installed 8.0.0-rc2, using MacOS 10.14.6, I have issues with `text input` and `text area` fields:
 * using Safari 13.0.3, I can't enter text in any of those fields at all (typing prints nothing on the screen)
 * using Firefox 70.0.1, I can enter/delete text into these fields, but I can't select/highlight text

Those two text field types work fine with Chrome 78.0.3904.108

**Comment by rijkvanzanten** [comment] 2019-11-27 16:38
Duplicate of #2233

**Closed by rijkvanzanten** 2019-11-27 16:38 UTC
