### ISSUE TITLE
404 error for tabular/layout.css

### ISSUE THREAD

**Issue by thepurpleblob** [directus/app#1491] opened 2019-04-14 11:11 UTC
# Bug Report

## Steps to Reproduce

1. create an instance of a collection
2. save it

## Expected Behavior

Save seems to work fine

## Actual Behavior

console shows...

GET http://................/extensions/core/layouts/tabular/layout.css net::ERR_ABORTED 404 (Not Found)

**Comment by rijkvanzanten** [comment] 2019-04-14 14:03
This is a duplicate of #1242

**Closed by rijkvanzanten** 2019-04-14 14:03 UTC
Labels: bug, question
