### ISSUE TITLE
M2M If "Visible Columns" is empty, the Form to add is not loading correctly.

### ISSUE THREAD

**Issue by edenprojectde** [directus/app#1949] opened 2019-08-10 05:06 UTC
M2M If "Visible Columns" is empty, the Form to add something to the field is not loading correctly. 
My solution to this would be to make the field to be Required and also be prefilled with the Primary Key. 

Following just the flow of the Interface will probably let some users be bamboozled without the hint of 
> "Oh it's the id! if i find "id" in the field-options i can probably change it there!"

-- some random users thoughts.

![image](https://user-images.githubusercontent.com/6115966/62817786-677a2200-bb3c-11e9-8f51-b37b4783feeb.png)

![image](https://user-images.githubusercontent.com/6115966/62817790-7a8cf200-bb3c-11e9-9bb3-31bc3beb388d.png)

Directus Suite(App) v7.9.0
PHP Zend Engine v3.3.7 with Zend OPcache v7.3.7-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c)
Nginx Server
OS: Ubuntu

**Comment by bjgajjar** [comment] 2019-08-12 07:03
It is duplicate of #1865 which is resolved in #1942

You will get this resolution in next release :)

**Closed** 2019-08-12 07:06 UTC
Labels: bug
