### ISSUE TITLE
v8.4.0 filebrowser has wrong detail link

### ISSUE THREAD

**Issue by dwasilew** [directus/app#2550] opened 2020-02-06 07:49 UTC
Hello Directus Team,

I am on version v8.4.0 (docker image) and have a strange issue in the file browser. 

If i load the file browser page and click on a image or file everything works and the detail page is loading. But if i scroll further down, starting at the second "page" (the item which are loaded after scrolling) clicking on a picture or file sends me to the login page and I am able to select a project despite having only on project set up. After this i can't login and have to reload the page.

**Steps to reproduce**
- upload at least that many images that they don't fit on one page
- scroll down that the file browser has to lazy load additional items
- click on one of the new loaded files

I would try to fix it if somebody can point me in a direction. Still pretty new to this whole vue thing.

If i click one of the first items it laods the url:
`http://localhost/_/files/7?fields=id%2Cstorage%2Cprivate_hash%2Cfilename_disk%2Cfilename_download%2Ctitle%2Ctype%2Cuploaded_by%2Cuploaded_on%2Ccharset%2Cfilesize%2Cwidth%2Cheight%2Cduration%2Cembed%2Cfolder%2Cdescription%2Clocation%2Ctags%2Cchecksum%2Cmetadata%2Cdata%2Cpreview`

if i click one of the lazy loaded it tries to load this one:

`http://localhost/undefined/`

Have a nice day,
Daniel

**Comment by rijkvanzanten** [comment] 2020-02-06 14:37
This is a duplicate of https://github.com/directus/app/issues/2362

**Closed by rijkvanzanten** 2020-02-06 14:37 UTC
Labels: bug
