### ISSUE TITLE
Fields order and hidden fields issues on listing view

### ISSUE THREAD

**Issue by romaiiinnn** [directus/app#1901] opened 2019-08-01 00:17 UTC
### Description
**In listing view**, the fields are not displayed in the correct order (as ordered in the collection settings). 
Also, fields marked as "**hidden on browse**" are still displayed.

**The details view is correct** though (the fields order and hidden fields).

### See printscreens

Example with a collection 'Content'

![Capture d’écran, le 2019-07-31 à 19 58 51](https://user-images.githubusercontent.com/45723322/62256557-b3f08f80-b3cf-11e9-8a7f-ed192e73dc66.png)

![Capture d’écran, le 2019-07-31 à 19 59 08](https://user-images.githubusercontent.com/45723322/62256566-be128e00-b3cf-11e9-9db7-554dcbac0675.png)

![Capture d’écran, le 2019-07-31 à 19 59 29](https://user-images.githubusercontent.com/45723322/62256576-cf5b9a80-b3cf-11e9-9fbd-d6578e122950.png)

![Capture d’écran, le 2019-07-31 à 20 10 17](https://user-images.githubusercontent.com/45723322/62256589-d682a880-b3cf-11e9-8f49-f8571d0ea74b.png)

![Capture d’écran, le 2019-07-31 à 19 43 52](https://user-images.githubusercontent.com/45723322/62256617-f023f000-b3cf-11e9-9bb6-3fa1bc140829.png)

Directus API 2.3.1
Directus App 7.8.0

**Comment by rijkvanzanten** [comment] 2019-08-01 01:00
You can set what fields show up on the listing view, and the order of them, by clicking on the (i) icon in the top right and modifying the layout settings.

> Also, fields marked as "hidden on browse" are still displayed.

This doesn't sound right though. I'll move that to a new issue as it's unrelated to the rest of this one

**Comment by rijkvanzanten** [comment] 2019-08-01 01:01
> Also, fields marked as "hidden on browse" are still displayed.

Duplicate of https://github.com/directus/app/issues/1720

**Closed** 2019-08-01 01:01 UTC
Labels: invalid

**Comment by romaiiinnn** [comment] 2019-08-01 01:55
> You can set what fields show up on the listing view, and the order of them, by clicking on the (i) icon in the top right and modifying the layout settings.

Don't you think that the default display in the listing should follow the order set in the collection settings?

**Comment by benhaynes** [comment] 2019-08-01 11:39
Yes, I agree Could you open up a feature request so we can track that?
