### ISSUE TITLE
Unable to set unrequired M2O back to null

### ISSUE THREAD

**Issue by awbranch** [directus/app#2262] opened 2019-12-01 19:44 UTC
App Version: 7.11.0

If you have a M2O field that is not required, once you select a value for it, there is no way to unset it back to null.

## Steps to reproduce

Create Collection: Person
With Fields: 
Name: TextInput: Required: true
Parent: Many to One to Person: Required: false

Create a person named "Father"
Create a person named "Child"

Set the "Child" parent to "Father"
Now try to set it back to null. You can't.

**Comment by benhaynes** [comment] 2019-12-01 20:50
Did you try clicking the field label? There is a context menu for each field that lets you perform additional actions like resetting the value.

**Comment by rijkvanzanten** [comment] 2019-12-01 23:30
Duplicate of https://github.com/directus/app/issues/1613

**Closed by rijkvanzanten** 2019-12-01 23:30 UTC
Labels: question
