### ISSUE TITLE
Can't select an icon in collection settings

### ISSUE THREAD

**Issue by Zielgestalt** [directus/app#643] opened 2018-08-16 22:11 UTC
When adding a new collection or editing a collection i can't select a icon for the collection. I just get a text input field. Shouldn't it be a "search and select" field?

![image](https://user-images.githubusercontent.com/41578219/44237735-f1a1db80-a1b1-11e8-80b0-dcfda643d271.png)

Tested locally and on next.directus.app with both apis.

**Comment by rijkvanzanten** [comment] 2018-08-16 22:15
Yeah you're right.. It's supposed to be one of these:

![image](https://user-images.githubusercontent.com/9141017/44237848-24cb7700-a180-11e8-9f8f-50a8e132b5da.png)

Settings are stored a little differently from every other collections, which makes the API return the wrong fields: instead of the field info (and interfaces used) for settings, the actual database columns of the `directus_settings` are returned.

As soon as [this ticket](https://github.com/directus/api/issues/296) gets fixed, this should solve itself.

**Comment by rijkvanzanten** [comment] 2018-09-19 21:34
This is caused by a wrong value for `interface` in the `directus_fields` row for `icon`. It has been fixed in the demo sql file and will be ported over to the install migration too

**Closed by rijkvanzanten** 2018-09-19 21:34 UTC
Labels: bug
