### ISSUE TITLE
Error in Log when using wrong pwd

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1131] opened 2018-11-18 18:32 UTC
When logging in with a wrong password, an error gets print out to the logs.
**Also, please remove remove the logging of passwords in the logs!!**

API: 2.0.8

Error:
<details>
<summary>Full error</summary>
<pre>
#0 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Authentication/Provider.php(115): Directus\Authentication\Provider->findUserWithCredentials('admin@example...', 'Baum')
#1 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Services/AuthService.php(47): Directus\Authentication\Provider->login(Array)
#2 /data/web/1/000/114/698/451251/htdocs/api/src/endpoints/Auth.php(49): Directus\Services\AuthService->loginWithCredentials('admin@example...', 'Baum')
#3 [internal function]: Directus\Api\Routes\Auth->authenticate(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#4 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#5 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Array)
#6 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#7 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#8 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\TableGatewayMiddleware), Array)
#9 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#10 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Slim\Route))
#11 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#12 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#13 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#14 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#15 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#16 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\IpRateLimitMiddleware), Array)
#17 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#18 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#19 /data/web/1/000/114/698/451251/htdocs/api/vendor/akrabat/rka-ip-address-middleware/src/IpAddress.php(93): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#20 [internal function]: RKA\Middleware\IpAddress->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#21 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(RKA\Middleware\IpAddress), Array)
#22 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#23 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#24 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#25 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#26 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\CorsMiddleware), Array)
#27 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#28 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#29 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#30 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#31 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\ResponseCacheMiddleware), Array)
#32 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#33 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Closure))
#34 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#35 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#36 /data/web/1/000/114/698/451251/htdocs/api/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#37 /data/web/1/000/114/698/451251/htdocs/api/src/core/Directus/Application/Application.php(161): Slim\App->run(false)
#38 /data/web/1/000/114/698/451251/htdocs/api/public/index.php(5): Directus\Application\Application->run()
#39 {main} [] []
</pre>
</details>

**Comment by rijkvanzanten** [comment] 2018-11-18 18:55
Ref https://github.com/directus/api/issues/555

**Comment by benhaynes** [comment] 2018-11-19 21:38
Thanks @Nitwel — @WellingGuzman is working on a fix for this but it's only partially complete. I'll close this since it's a duplicate of what Rijk posted and this is an API issue. Please follow up with that ticket for resolution.

**Closed by benhaynes** 2018-11-19 21:38 UTC
Labels: duplicate
