### ISSUE TITLE
Not able to add a One-to-Many-Field to Collection

### ISSUE THREAD

**Issue by HerrHase** [directus/app#1699] opened 2019-05-31 10:04 UTC
# Bug Report

## Steps to Reproduce

I have tried to update a Collection to Reference to himself with a one-to-many i get this after saving,

```
INSERT INTO `directus_fields` (`collection`, `field`, `type`, `interface`, `required`, `sort`, `note`, `hidden_detail`, `hidden_browse`, `options`, `readonly`, `validation`, `width`) VALUES ('section', 'sections', 'o2m', 'one-to-many', '', NULL, NULL, '', '', '[]', '', NULL, 'full')
```

After refreshing the site, the new field don't show up. I'm not sure if this is related, i have observe this Behavior not the first time.

I have tried to Reference to another Collection, but same Error.

1. Adding a Markdown Field to a Colletion, it shows me also a Error. I refresh the site, a "Manage"-Button shows up. After pressing him all works fine.

2. Changing the Option "Field Width" also shows me a Error, I refresh the site, nothing shows up, the option not changed.

## Technical Details

- Device: Virtualbox
- OS: Ubuntu 18.04 LTS
- Web Server: nginx/1.14.0
- PHP Version: 7.2.17
- Database: Mariadb 10.3.15
- Install Method: cloned `master` branch

**Comment by bjgajjar** [comment] 2019-08-09 06:33
Hey @HerrHase,

> I have tried to update a Collection to Reference to himself with a one-to-many I get this after saving,

I assume that you want to add `O2M` relation for a collection with itself. For that, you should add `M2O` field over there instead of `O2M`. Let me explain this via an example.

Let's suppose `category` collection has many `subcategory`. So basically the `subcategory` and  `category` will be stored in `category` collection only. But we might include an extra field `parent_id` for storing the `id` of `category`.

Thus, when the user needs to add `O2M` for collection to itself; then they should add `M2O` field instead of `O2M`. As for this scenario, the collection has an `O2M` as well as `M2O` relation with the self only. 

As per the current structure od `Directus` when you want to add `O2M` you must have `M2O` field. Thus here we have to add `M2O` instead of O2M`.

This was the flow which should be there and you may get the error in the older version. Can you please check it in the latest version? As I am not able to reproduce it with the latest one.

**Comment by bjgajjar** [comment] 2019-08-13 10:18
As this not an issue actually; I am closing this. Feel free to reopen it.

**Closed by bjgajjar** 2019-08-13 10:18 UTC
Labels: bug

**Comment by HerrHase** [comment] 2019-09-09 14:09
Thanks @bjgajjar, works now perfect!
