### ISSUE TITLE
Can't remove M2O relation

### ISSUE THREAD

**Issue by danyright** [directus/app#1045] opened 2018-10-27 10:06 UTC
# Bug description
After creating a Many-to-One field, if you delete this field and create a One-to-Many field with the same relation, it creates a "Server error" preventing the listing of the items or creation of a new item in the collection (in which the field was created).

## Steps to Reproduce

1. Create a new 'category' collection, with one, text input, 'name' field
2. Create a new 'test' collection, with one, text input, 'name' field and one, many-to-one, 'category' field - with a relation to category.id.
3. Create a new 'category' item, and create a new 'test' item with a category -- it works
4. Remove the many-to-one 'category' field from the 'test' collection
5. Create a new one-to-many 'category' field for the 'test' collection
6. Try to add a new 'test' item -- you can't, and in the listing you see an error: 
```
 Server Error
 Something is wrong with this instance’s server or database.
```

## Expected Behavior
There should be no errors ;-)

## Actual Behavior
I don't know the details of the behind the scenes operations, but I noticed that after deleting the many-to-one field, there is still an entry in the 'directus_relations' MySQL table describing the link created by the many-to-one field (I believe) (see attached screenshot).

I believe this is what creates the issue, because when removing the entry in the table manually (via phpMyAdmin) I do not encounter the problem.
_Once the field is deleted (from the app/GUI), the listing and item creation are available without errors._

I also noticed an Apache error on the server :

`  | 500 | GET   /XXX/public/_/items/atest?fields%5B0%5D=%2A.%2A&fields%5B1%5D=id&meta=total_count%2Cresult_count&limit=50&offset=0  HTTP/1.0`

## Other Context & Screenshots
Screenshot showing the content of table 'directus_relations' after creating **and** deleting _two_ many-to-one and _one_ one-to-many relations. The last entry is another field linked to second category collection.
![screenshot_20181027_115416](https://user-images.githubusercontent.com/4611396/47602479-d63c2380-d9df-11e8-95ae-70437943bef5.jpg)

## Technical Details

- Device: Laptop
- OS: Linux
- Browser: Firefox developer edition
- Directus App: 7.0.2
- Directus API: 2.0.2
- Install Method: git - cloned build-v7 branch

PS: I tried to update my installation to v7.0.3 (master branch, commit d9a2e27c9) but the app was not loading (apparently the Vue JS app file is not loading).

**Comment by benhaynes** [comment] 2018-10-27 12:38
Thank you for reporting this @danyright ... we always appreciate such detailed issues. I think you're correct in saying the problem is the `directus_relations` not being cleared. This should be an easy fix, but I wonder if this was partially "by design" since relations can be shared with other fields. We'll look into it and get it resolved ASAP!

The bigger issue here seems to be you saying 7.0.3 didn't work... any specific errors there?

**Comment by danyright** [comment] 2018-10-27 12:52
Ok, let me know if I can help.

Regarding the 7.0.3 update, I wasn't sure if I should open a separate ticket?
Anyhow, here's what I do to update (from directus/directus repo, branch 'build-v7') : $ git checkout master
since I saw you changed the branches of the directus repo. 
Checking with `git log` tells me I'm at origin/HEAD.

When trying to access directus (`install_folder/public/admin`) I now get a blank page.
I don't see any Apache errors, but here's what I get in the browser's console (even after clearing my browser's cache) :
![screenshot_20181027_145044](https://user-images.githubusercontent.com/4611396/47604299-f841a000-d9f7-11e8-8b92-3c050a5363f3.png)

**Comment by benhaynes** [comment] 2018-10-27 13:02
Thanks again @danyright – Unless @rijkvanzanten has an explanation for this, I will shift it to a dedicated ticket.

**Comment by danyright** [comment] 2018-10-27 13:54
I tried a fresh installation, cloning: `$ git clone https://github.com/directus/directus.git`
I get the same error when trying to access `/public/admin`

CentOS 7, Plesk 17.8, PHP 7.2.11

**Comment by benhaynes** [comment] 2018-10-27 15:06
Thanks @danyright – we're fixing this install issue right now and will be pushing a new release shortly. Also, I've updated the install Docs to be clearer (pointing the document root to `/public`).

**Comment by danyright** [comment] 2018-10-27 15:47
Thanks!
Euh actually I realize I did not setup my instances in the recommended way.
What I did is create a vhost (Plesk subscription) which I use for multiple directus instances.
So I have one domain, and then multiple folders, each folder containing 1 directus instance.
```
E.g.:
mydomain.com/instance1/public/admin
mydomain.com/instance2/public/admin
mydomain.com/instance25/public/admin
...
```
So my document root actually points to the mydomain.com folder and not 'public'.

Though I doubt this is the reason for the error (since it worked with v6.X & v7.0.2) I thought I'd mention it...

**Comment by rijkvanzanten** [comment] 2018-11-02 20:15
Relationships are used both ways, so it's quite tricky to delete the whole relationship if you delete just one "side" of it.

We're thinking of creating a separate relationships panel in settings that would allow the user to manage all the relationships in the system. That should make it way easier to debug these kind of issues and make sure that the relations are setup correctly. Seeing that it takes quite a long time to implement a proper fix, I have to postpone fixing this for a little bit to prioritize some other smaller yet important bugs

**Comment by rijkvanzanten** [comment] 2019-01-28 22:11
This was fixed in https://github.com/directus/api/commit/a3d7dc112132ddafbaa3445dd8999f9100d40f62

**Closed by rijkvanzanten** 2019-01-28 22:11 UTC
Labels: bug, extension
