### ISSUE TITLE
Adding M2M Relation in another M2M Modal

### ISSUE THREAD

**Issue by onlinelessons** [directus/app#1730] opened 2019-06-07 13:35 UTC
Hello,

I have multiple courses which have a m2m relation to lessons. The lessons have a m2m relation to downloads with a junction table. If i click on new lesson in the lessons collection, i can add downloads, save them and everything works fine.
Another way (which is the prefered one for the editor) is to click on courses collection. In the course page i click on "add new" lesson, which opens the new lesson modal:
![image](https://user-images.githubusercontent.com/47600858/59106205-141a0680-8936-11e9-9395-499bd5fed32b.png)

In the lesson modal I add a new download relation:
![image](https://user-images.githubusercontent.com/47600858/59106393-91de1200-8936-11e9-9a31-6a6408a4a988.png)

After safe, no download is shown:
![image](https://user-images.githubusercontent.com/47600858/59106611-1c267600-8937-11e9-9f18-ac94272a4b74.png)

If i click on safe lesson and open the modal again by clicking on the lesson, the download shows up correctly.
Then I click on cancel and return to the course an click safe here, the lesson downloads gets stored in the database:
junction table:
![image](https://user-images.githubusercontent.com/47600858/59107189-5c3a2880-8938-11e9-9154-bcac80d721f6.png)

downloads table:
![image](https://user-images.githubusercontent.com/47600858/59107341-b63aee00-8938-11e9-80e1-469af86dee20.png)

The I go back, open the course, click on the lesson and the modal shows up. In the modal, the download is empty:
![image](https://user-images.githubusercontent.com/47600858/59107816-bd163080-8939-11e9-9f2a-4e3068c68613.png)

 and if i click on it, all inputs are empty, too:
![image](https://user-images.githubusercontent.com/47600858/59107540-2ba6be80-8939-11e9-887e-559254efcd73.png)

**Comment by almondevon** [comment] 2019-06-12 16:43
Hello, this is happening to me as well. Creating and deleting nested items works, but I'm not able to view the changes, or even view the related data after refreshing. It looks like the data just isn't being pulled from the DB. From sniffing the network, it looks like it is only grabbing the join table for the second level of nest.

![secondlevel](https://user-images.githubusercontent.com/40006358/59369261-a559f600-8d05-11e9-9ce1-9221d762c38f.png)

If I add and additional .* (final is component.*.*.*.*) to the query string parameters on the initial GET request, I receive the full correct data.

I hope this help! Let me know if you need any more info. I am on Directus 7.5

**Comment by onlinelessons** [comment] 2019-08-21 12:24
unfortunately still not working...

**Comment by urvashithakar** [comment] 2019-09-09 11:12
I think it is duplicate of  [#1211](https://github.com/directus/api/issues/1211).

**Comment by benhaynes** [comment] 2019-09-09 13:18
Yes, it seems like it is a duplicate. I'll close this one now that it's been referenced in the other ticket.

**Closed by benhaynes** 2019-09-09 13:18 UTC
Labels: bug, duplicate
