### ISSUE TITLE
Ability to delete from File Library lacking protection

### ISSUE THREAD

**Issue by Brian-Myers-Bose** [directus/app#2127] opened 2019-10-11 18:42 UTC
Hi,

First, I am new to Directus.  This is a really excellent tool, and I’m enjoying using very much.  

This is my first bug report.  I can see that some may consider this a feature request, though from my perspective, this issue could easily lead to corrupted collections and is therefore a bug.  However you want to think about it…

Let us say that I have an image of a beach (beach.jpg), and I associate this image with multiple collections (eg. Real Estate For Sale, Vacation Packages, Outdoor Excursions, Corporate Events).

I have another image saved in File Library of me standing by the beach (beach_vacation.jpg).  I decide to assign an avatar within Editing My Profile.  
1. I choose “+ Existing” to select an image from the File Library, and upon display, I find that I accidentally chose beach.jpg instead of beach_vacation.jpg. (ie. It’s a picture of a beach and not me at the beach)
2. I click on the 3-dots icon, and I’m provided with the choices of “Deselect” and “Delete”.
3. I choose “Delete”, and without any warning or protection, I have just deleted that image from my File Library and therefore corrupted the four collections associated with said image. (Real Estate For Sale, Vacation Packages, Outdoor Excursions, Corporate Events)

Proposal 

- Situations like avatar creation should not allow the option to “Delete”
- If the deletion will potentially affect the breadth of the system, then this action should be restricted to the single shared point, aka. File Library
- Any deletion of this type should  be accompanied by a warning and a confirmation screen.
   * “This deletion will remove this file from the library and all collections which reference this file will be affected”
   * “Press DELETE to confirm deletion of this file.

Thanks for your consideration,
Brian

**Comment by benhaynes** [comment] 2019-10-12 23:36
Thanks @Brian-Myers-Bose — this is a thoughtful Feature Request (and/or Bug). I agree that at the very least we should have a confirmation alert for deletion from within interfaces.

I would be down to discuss only allowing file deletion from the File Library... since I agree it's a serious operation that might unintentionally break other item relations to that file. Perhaps when deleting a file from File Library (or anywhere) we should display a global modal that lists all the places that asset/relational item is used. That would allow for a more informed DELETE.

**Comment by Brian-Myers-Bose** [comment] 2019-10-14 14:18
If I can add any value to the discussion or code, I'm open to pitching in.

**Comment by benhaynes** [comment] 2019-10-14 18:02
Thank you! We always welcome PRs if you can draft a fix in the App codebase. Vue.js is very easy to get into if you want to give it a try.

Also, our team is available on Slack to help if you run into issues: https://directus.chat

@rijkvanzanten — do you agree with only hard-deleting files from the File Library? Or do you think we should have a global confirmation modal that fetches relational usage and lets the user confirm?

**Comment by Brian-Myers-Bose** [comment] 2019-10-15 12:39
That sounds doable.  I don't want to commit just yet until I know my schedule, but I'm about 70%.

**Comment by Brian-Myers-Bose** [comment] 2019-10-16 14:48
I wanted to get started on giving back to the community last night, but the instructions on building Directus starting with a git clone are not good.  I have submitted this as a feature request ("Better installation instructions #2142"), detailed out the issues, and provided a Word doc I built for performing an install from master.zip.  I'll attempt to create build instructions for the git install as well, and then I'll be able to do some development.

**Comment by benhaynes** [comment] 2019-10-19 22:21
That Docs PR is amazing... thank you so much @Brian-Myers-Bose! Our team has been super busy on client projects for the last year or so, but now we're all back on Directus full-time and ready to start getting these Docs (and codebase) polished up. I really appreciate you taking the time to add/outline some improvements to our installation Docs! 😄

**Comment by rijkvanzanten** [comment] 2019-11-20 18:30
I'm closing this as a duplicate of https://github.com/directus/app/issues/1385

This doesn't just apply to files, but to any relationship in general. When you try to delete an item that has an active relationship to another item, the application should warn you about it before actually deleting the item.

We should be able to find active relationships from the front-end by combining the info we have in the store about relationships from a field + doing some fetches to the api with filters trying to read if there's rows that have the to-be-deleted item linked

**Closed** 2019-11-20 18:31 UTC
Labels: duplicate
