### ISSUE TITLE
Use display components on cards (tile view)

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/app#605] opened 2018-08-06 22:03 UTC
Right now, the different sections in the card use the full value. It should use the display component of the interface used instead.

**Comment by benhaynes** [comment] 2018-12-13 04:32
Does this make sense if they are icons or thumbnails or something else that's weird?

**Comment by benhaynes** [comment] 2018-12-13 04:37
Duplicate of https://github.com/directus/app/issues/974

**Closed by benhaynes** 2018-12-13 04:37 UTC
Labels: enhancement
