### ISSUE TITLE
Changing an existing field interface to relational will throw error

### ISSUE THREAD

**Issue by andriipol** [directus/app#1630] opened 2019-05-14 16:27 UTC
Not able to relate new field in the latest version. It worked in the previous versions.
Steps to reproduce:
1. I create a new field by my application that has manyToOne relation.  When I push a managed button and see the pop-up error "Trouble processing request. " 
2. After that Interface of the field becomes Numeric. 
3. Then I try to relate this field to a needed table and see an error that this field already exists.
Please take a look on the issue.
![bug_1](https://user-images.githubusercontent.com/12764733/57714519-5759c000-767d-11e9-9a11-5536b58a9401.jpg)
![bug_3](https://user-images.githubusercontent.com/12764733/57714979-5d03d580-767e-11e9-8a78-e57ae7a0b487.jpg)
![bug_2](https://user-images.githubusercontent.com/12764733/57714518-5759c000-767d-11e9-9761-e2672d8f4a8a.jpg)

**Comment by benhaynes** [comment] 2019-05-14 17:01
Thanks @andriipol — we'll look into this.

@shealavington — do you remember seeing anything like this when you were working on that code?

**Comment by andriipol** [comment] 2019-05-14 18:14
Thanks a lot. I like your team :)

**Comment by shealavington** [comment] 2019-05-15 09:26
As far as I'm aware I tried to break it, and I couldn't get it to go wrong..

**Would you be able to write me some step-by-step instructions to replicate this issue?**

From your final screenshot, it looks like you're trying to create a `new field` with the same name as your `existing field` (Numeric one), are you trying to `update` the "Numeric Field" to change it to a relational interface, or `create` a new field with the same name but with a relational interface?..

**Comment by andriipol** [comment] 2019-05-15 09:40
These screenshots were made step by step:
First, a new field was created by my application related ManyToOne to another table.
Second, I saw this field in directions. I pushed 'Manage' and an error was poped-up 'Trouble processing'(first screenshot).
After that,  the field became Numeric like in the second screenshot.
Then I pushed this field to make it ManyToOne relation to the table I needed and saw the error that the field was already existed (see the third screenshot)

**Comment by shealavington** [comment] 2019-05-15 09:40
**Update** 

I've managed to replicate the issue... The issue occurs when updating the numeric interface to become a relational interface.

However... Upon reloading the page, the interface has successfully been changed to the relational interface I selected (Many to One), and can have its "relation" collections changed, and it should work...

This seems to be unrelated to the "Manage" system @benhaynes. :smile: _(Which makes me happy)_ :wink: 


---

The error comes from a call to: `/_/relations` after clicking an interface, and it returns: `message: "collection_many: This value should not be blank. field_many: This value should not be blank."`

Therefore, I believe the frontend is trying to save the relationship before any interface is selected, which is failing as we haven't been through the relation setup yet as we're changing a field, not creating it.

**Comment by benhaynes** [comment] 2019-05-15 11:23
Thank you @andriipol and @shealavington for taking the time to find the root issue! Rijk will take a look next week when he's back unless someone has time before then. Glad it wasn't your code Shea 😊

**Comment by rijkvanzanten** [comment] 2019-05-20 14:57
I haven't confirmed this, but I have a hunch that the individual interfaces you can select are `<button>` elements, that in turn `submit` the form parent, which in turn saves the interface changes before being done setting up.

**Comment by benhaynes** [comment] 2019-05-20 17:31
That seems likely! Maybe related to: #1635 and/or #1637?

**Comment by rijkvanzanten** [comment] 2019-05-28 12:15
Hey @andriipol! I tweaked the way the field setup goes to the next tabs when changing interface on an existing interface. Could you try updating to 7.4 and let me know if the problem still occurs for you?

**Comment by andriipol** [comment] 2019-05-28 12:21
Sure, I'll let you know

**Comment by andriipol** [comment] 2019-05-29 13:27
Updating to 7.4 didn't solve the problem. Same popup message "Trouble processing request". Then it becomes Numeric and tells that this field is used.

**Comment by urvashithakar** [comment] 2019-08-28 12:38
Hey @shealavington,
> The issue occurs when updating an existing interface to become a relational interface.

It seems like this issue is resolved in the latest version. I am not able to replicate in the live demo.

@andriipol 

> Updating to 7.4 didn't solve the problem.

Currently, we have 7.10 version so kindly check once with upgrading your current version.

**Comment by bjgajjar** [comment] 2019-08-31 05:55
As this issue is not reproducible in the latest version; I am closing this. Feel free to reopen it.

**Closed by bjgajjar** 2019-08-31 05:55 UTC
Labels: not reproducible
