### ISSUE TITLE
Request for server info being rejected

### ISSUE THREAD

**Issue by pichardoJ** [directus/app#1641] opened 2019-05-20 20:38 UTC
### Issue

The request to get the server info ([documentation reference](https://docs.directus.io/api/reference.html#server)) is being sent without a _Authorization_ header which leads to the following error message:

> Access to XMLHttpRequest at 'SERVER_URL' from origin 'APP_URL' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

![Screen Shot 2019-05-20 at 3 10 48 PM](https://user-images.githubusercontent.com/12650088/58049378-522fc180-7b12-11e9-8b3e-7d8c882c1957.png)

### Expected behavior 

The request should include the _Authorization_ with the right token same as the other requests:

![Screen Shot 2019-05-20 at 3 11 17 PM](https://user-images.githubusercontent.com/12650088/58049815-60321200-7b13-11e9-973e-205c8dda592f.jpg)

![Screen Shot 2019-05-20 at 3 27 12 PM](https://user-images.githubusercontent.com/12650088/58050255-72f91680-7b14-11e9-8c3a-5bc231ebd936.jpg)

### Environment

- *App:* Pre-bundled build version (latests commit)
- *Api:* Pre-bundled build version (latests commit, build branch)
- *Browser:* Chrome

**Comment by rijkvanzanten** [comment] 2019-05-20 20:46
When does this request happen? I don't see it on [the live demo](https://directus.app)

**Comment by pichardoJ** [comment] 2019-05-20 21:21
@rijkvanzanten This request happens in _hydrate.js_

```javascript
return (
    Promise.all([
      ...
      store.dispatch("getServerInfo")
    ])
)
```
So far according to my understanding everytime a route is loaded if the `store.state.hydrated` is `false`  then `hydrateStore()` is called and then the request is made.

**Comment by rijkvanzanten** [comment] 2019-05-20 21:41
Does your (local) API run? Can you open that `/` page manually?

**Comment by pichardoJ** [comment] 2019-05-21 12:14
@rijkvanzanten Yes, if I make the request using curl and the right header it works.

**Comment by rijkvanzanten** [comment] 2019-05-21 13:37
I'm trying to wrap my head around what could cause this for you (and only in development mode). I'm not having this issue.. 

It's just this request that fails?

**Comment by pichardoJ** [comment] 2019-05-21 13:41
@rijkvanzanten Yes is only this request and it fails with the bundled app and development mode, could it be something related to configuration?

**Comment by pichardoJ** [comment] 2019-05-21 13:48
This is the configuration for the app

```javascript
/* eslint-disable */

(function directusConfig() {
  const config = {
    api: {
      "http://api.vohc.cfni.org/_/": "VOHC API"
    },
    allowOtherAPI: false,
    routerMode: "hash", // hash | history
    routerBaseUrl: "/"
  };
  window.__DirectusConfig__ = config;
})();

```
And this is for the API
```php
return [
    'app' => [
        'env' => 'production',
        'timezone' => 'UTC',
    ],

    'settings' => [
        'logger' => [
            'path' => __DIR__ . '/logs/app.log',
        ],
    ],

    'database' => [
        'type' => 'mysql',
        'host' => 'localhost',
        'port' => 3306,
        'name' => 'mock,
        'username' => 'mock',
        'password' => 'mock',
        'engine' => 'InnoDB',
        'charset' => 'utf8mb4',
    ],

    'cache' => [
        'enabled' => false,
        'response_ttl' => 3600, // seconds
        'pool' => [
            // 'adapter' => '',
            // 'path' => '',
            // 'host' => '',
            // 'port' => '',
        ],
    ],

    'storage' => [
        'adapter' => 'local',
        'root' => 'public/uploads/_/originals',
        'root_url' => '/uploads/_/originals',
        'thumb_root' => 'public/uploads/_/thumbnails',
    ],

    'mail' => [
        'default' => [
            'transport' => 'sendmail',
            'from' => 'mock'
        ],
    ],

    'cors' => [
        'enabled' => true,
        'origin' => ['*'],
        'methods' => [
            'GET',
            'POST',
            'PUT',
            'PATCH',
            'DELETE',
            'HEAD',
        ],
        'headers' => [],
        'exposed_headers' => [],
        'max_age' => null, // in seconds
        'credentials' => false,
    ],
]
```

**Comment by rijkvanzanten** [comment] 2019-05-21 13:52
That does look good to me.. Can you create a dummy account so I can try logging in? Curious to see what causes this

**Comment by rijkvanzanten** [comment] 2019-05-21 13:52
You can also send it to me in a private message [on Slack](https://directus.chat)

**Comment by rijkvanzanten** [comment] 2019-05-21 14:44
This was caused by the server not allowing `OPTIONS` requests. This was fixed by allowing this method in the Nginx config.

**Closed by rijkvanzanten** 2019-05-21 14:44 UTC
Labels: not reproducible
