### ISSUE TITLE
New fields aren't using fallback/default interface

### ISSUE THREAD

**Issue by benhaynes** [directus/app#868] opened 2018-09-26 22:38 UTC
If you add a field to the database, it shows up in Settings, but does not yet have a record in `directus_fields`. If you go to a page that uses those fields, it throws errors for each instead of using the fallback.

eg: A varchar should just use a text-input interface if it doesn't have one set.

![screen shot 2018-09-26 at 6 35 52 pm](https://user-images.githubusercontent.com/522079/46113161-46764000-c1bb-11e8-84b8-40880c5d074a.png)

This _should_ be a bug (feature parity with6.x) but I'll add it as an enhancement.

**Comment by benhaynes** [comment] 2018-09-28 13:18
This actually _is_ kinda working, but only uses the `text-input` interface. We should base the default interface on the datatype/length.

**Comment by rijkvanzanten** [comment] 2018-09-28 13:36
Duplicate of https://github.com/directus/app/issues/704

**Closed by rijkvanzanten** 2018-09-28 13:36 UTC
Labels: duplicate
