### ISSUE TITLE
Options in Edit Fields not working properly

### ISSUE THREAD

**Issue by Nitwel** [directus/app#1396] opened 2019-03-16 18:27 UTC
Having temporary duplicates in settings of an Field will remove the duplicate on edit which is kinda annoying when you just copyed a sertain amount and now want to edit them.

![grafik](https://user-images.githubusercontent.com/22577866/54479812-71b02280-4821-11e9-85fd-9df49129c7bc.png)

**Comment by rijkvanzanten** [comment] 2019-03-18 14:28
Good point. Right now it will convert the provided string of JSON in to an object before staging it for save. That staging will override the provided value with the staged value. Seeing that having two keys in JSON will result into a single object, this edit will remove the duplicated key. 

Not too sure how to fix this yet, as I imagine the only fix would be to decouple the staged value from the visible edit. But that would in turn kill the preview of saved values, as that's the same property right now 🤔

**Comment by dev7ch** [comment] 2019-04-13 19:45
i guess it could be related to codeMirror.js settings, btw i think the code mirror editor interface needs a bit closer look

**Comment by rijkvanzanten** [comment] 2019-05-22 22:16
I'm not sure if this is a problem that we can fix..

The interface parses the JSON when it's staging to make sure we're only attempting to save valid JSON objects. When JSON.parse throws an error, the stage is ignored.

However, apparently JSON.parse has no trouble parsing an object with duplicated keys...:

![image](https://user-images.githubusercontent.com/9141017/58212528-0f5e1d00-7cbd-11e9-8609-ec3a4e7bd1d0.png)

Seeing that it's this low-level browser API that's causing the issue, I'm not sure if there's something we can do about it at this point. We can't read the value as a JS object (cause we'd need to use JSON.parse for that), so the only real solution to this would be to read the actual text content and try to convert the object keys into an array to then check for duplicates. This would add a tremendous amount of complexity and would be incredibly hard to build properly..

What do we think @Nitwel @dev7ch @benhaynes, worth it? (80/20)

I'm personally in camp #wontfix

**Comment by Nitwel** [comment] 2019-05-22 22:24
The issue here wasn't about that it should be a feature to support duplicate entrys but while editing, when you want to duplicate some rows to edit them the editor will just delete them. Its kinda annoying because it should only do that when you are done editing. But I also know that while editing it automaticly saves which makes fixing this much harder than when you save it by yourself.

**Comment by rijkvanzanten** [comment] 2019-05-22 22:30
Yeah! I know. My bad if that wasn't clear from my response. The problem is indeed that the value is staged whenever the value is considered valid (by parsing it with JSON.parse). Unfortunately, JSON.parse considers a duplicate key valid and removes one, making it very hard for us to check for this edge case.

**Comment by Nitwel** [comment] 2019-05-22 22:36
One approach would be to add a validate button that parses the JSON so while editing you only get a marked spot where you messed up something. But there's more important stuff to to at the moment, you can close this and maybe add it to the 'feature requests' projects.

**Comment by rijkvanzanten** [comment] 2019-05-22 22:40
The JSON interface actually does that now already 😄 

It was added after you posted this issue in https://github.com/directus/app/pull/1533. Maybe that already does enough to fix it? Haven't tested it yet

**Comment by rijkvanzanten** [comment] 2019-05-22 22:41
Nope, that didn't help. Same issue :(

**Comment by benhaynes** [comment] 2019-05-22 22:50
This issue has happened to me too, and it is quite annoying. However, given the complexity of the solution I think we should move this to a feature request and wait to find a more elegant/simple fix.

**Comment by benhaynes** [comment] 2019-05-22 22:50
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Closed by benhaynes** 2019-05-22 22:50 UTC
Labels: bug
