### ISSUE TITLE
File Manager with Folders

### ISSUE THREAD

**Issue by TorbenHammes** [directus/app#2964] opened 2020-08-26 12:13 UTC
It would be great if files and images could be structured and organized in folders. Is there already an extension here? I have not found anything for this.
Something like https://filerun.com/

Thanks in advance and best wishes from Berlin
Torben

**Comment by rijkvanzanten** [comment] 2020-08-26 13:50
<img width="1739" alt="Screen Shot 2020-08-26 at 9 49 28 AM" src="https://user-images.githubusercontent.com/9141017/91311755-70f31e00-e781-11ea-873e-9a3df4048578.png">

Like this? 😉 It's coming in v9

**Comment by rijkvanzanten** [comment] 2020-08-26 13:51
Duplicate of https://github.com/directus/app/issues/228

**Closed by rijkvanzanten** 2020-08-26 13:51 UTC
Labels: duplicate
