### ISSUE TITLE
How to translate the table name and field name in v7 ?

### ISSUE THREAD

**Issue by Chris533** [directus/app#1162] opened 2018-12-02 00:36 UTC
Hello, could someone please tell me how to translate table name and field name?

_Originally posted by @Chris533 in https://github.com/directus/app/issues/779#issuecomment-443432805_

**Comment by Chris533** [comment] 2018-12-02 00:36
![how_to](https://user-images.githubusercontent.com/17868145/49334292-5f60fe80-f60d-11e8-948e-36c64bcda9ad.jpg)

**Comment by benhaynes** [comment] 2018-12-03 14:11
You would use: `directus_fields.translations` and `directus_collections.translations`. I'm working on adding a section to the Docs on this now (specific JSON format). But here it is in the meantime:

```json
{
  "en-US": "My Collection",
  "nl-NL": "Mijn Collectie"
}
```

**Comment by rijkvanzanten** [comment] 2018-12-03 14:15
@benhaynes Lets keep this open until we have an interface to set it up in the app as well

**Comment by rijkvanzanten** [comment] 2018-12-03 14:16
Ah wait never mind, that would make it a duplicate of https://github.com/directus/app/issues/422 😁

**Closed by rijkvanzanten** 2018-12-03 14:16 UTC
Labels: question
