### ISSUE TITLE
Slug interface, don't change slug after created

### ISSUE THREAD

**Issue by simonking76** [directus/app#2498] opened 2020-01-30 22:16 UTC
I'm getting regular issues with the slug interface: when I mirror the title field, the slug is created and the page will eventually be indexed in Google. 

A while later a user changes the title because they want to 'optimise it for SEO'.  The slug gets changed, the URL is now different and the indexed url in google is now broken.

I recall there used to be a setting on the slug interface to 'not update once created' or something similar, I might be wrong. So even if the title is changed, the slug stays the same.

I'd like to request an option to not update slugs once created. It is useful to change the slug when the title is changed, but unless you're creating 301 redirects at the same time, it's potentially damaging to your indexed URLs.

Thanks,
Simon

**Comment by benhaynes** [comment] 2020-01-30 23:05
Duplicate of: https://github.com/directus/app/issues/2421

**Closed by benhaynes** 2020-01-30 23:05 UTC
