### ISSUE TITLE
In o2m, click the Add New button,It always creates a blank items

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1911] opened 2019-08-01 17:16 UTC
Bug Report

![](https://raw.githubusercontent.com/cdwmhcc/public/master/directus-o2m-error.gif)

## Expected Behavior

In o2m, click the **Add New** button，
Close the modal box in any way
It always creates a blank items

## Actual Behavior
Fix it

## Technical Details

- Device: [Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.3.1]
- APP Version: [7.8.0]

**Comment by benhaynes** [comment] 2019-08-01 17:20
Duplicate of https://github.com/directus/app/issues/1851

**Closed by benhaynes** 2019-08-01 17:20 UTC
