### ISSUE TITLE
m2m interface creates / leaves empty items when you **cancel** adding new item.

### ISSUE THREAD

**Issue by anelad** [directus/app#1823] opened 2019-07-07 17:45 UTC
Let's assume we have **posts** and **tags** entities. Tags have only **name** field. Posts have **name** and **tags** fields where tags field is related to Tags entity with many-to-many relation.

Now, let's pre-add some tags. Ex: Tag 1, Tag 2, Tag 3.

Now let's reproduce the issue. 

1. Add existing tags. No problem.
2. Add new tag. Save it. No problem.
3. Add new tag but do not save it. Click on **Cancel** or **X**. The tags list have an empty item. Try to save the post; get an error saying name could not be empty.

I also sharing a gif here:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5767654/60771972-ec19f080-a0f7-11e9-9b08-b393ef7f91f3.gif)

**Comment by theharshin** [comment] 2019-08-09 09:36
Duplicate of https://github.com/directus/app/issues/1851

**Closed** 2019-08-09 10:27 UTC
Labels: bug

**Comment by anelad** [comment] 2019-08-09 13:16
@theharshin #1851 is duplicate of this, not the opposite you know :D

**Comment by rijkvanzanten** [comment] 2019-08-09 15:38
![](https://media.giphy.com/media/WxDZ77xhPXf3i/giphy.gif)
