### ISSUE TITLE
Add "Explain" support

### ISSUE THREAD

**Issue by benhaynes** [directus/app#371] opened 2018-05-09 22:49 UTC
If this permission is set, the user will automatically get a Prompt when updating/changing/deleting any item. This can not be bypassed – cancelling or closing simply cancels the save action.

We should also add an "Explain and save" or "Save with explanation" option to the Save options (three dots on Item Detail Save button). That way users can use this voluntarily too.

**Comment by rijkvanzanten** [comment] 2018-05-18 22:48
This needs to wait for #255 to be implemented (which in turn needs #330)

**Comment by rijkvanzanten** [comment] 2018-06-21 21:44
This is a duplicate of #245

**Closed by rijkvanzanten** 2018-06-21 21:44 UTC
Labels: invalid
