### ISSUE TITLE
Feature Request : Add ability to search fields when creating a new collection

### ISSUE THREAD

**Issue by rwatts3** [directus/app#1232] opened 2019-01-05 20:50 UTC
# Feature Request
First and foremost thank you for providing such a great list of supported fields out of the box.
This request is to add a search box to the field modal so that we can quickly select a field.
## What problem does this feature solve?
This feature allows users to rapidly build out fields by providing a search mechanism.
## How do you think this should be implemented?
This should be a search input just beneath the modal text "Select an interface below"
## Would you be willing to work on this?
Yes i'm willing to assist.

A tool such as fuzzy searching or http://fusejs.io/ would suffice.

**Comment by benhaynes** [comment] 2019-01-07 16:03
Thanks @rwatts3! I think this is a duplicate of:

https://github.com/directus/app/issues/1178

I'll close it... but rest assured that this is on our Refactor milestone and should be included in the next few weeks!

**Closed by benhaynes** 2019-01-07 16:03 UTC
