### ISSUE TITLE
v8 develop branch - Login broken after restart api server

### ISSUE THREAD

**Issue by everyx** [directus/app#2251] opened 2019-11-29 10:31 UTC
### Technical Details
* Device: Desktop
* OS: Docker Desktop on Windows 10
* Web Server: Caddy on Docker
* PHP Version: 7.4
* Database: MySQL 8
* Install Method: cloned develop branch

### Details
When I just restart the api server, and refresh app login page, then login, we got `Couldn't reach api` error, the server responded with a status of 500 (Internal Server Error), but if I click "Clear storage" at Chrome DevTools, it work again.

I'm not sure is a app bug or api, and I have submit a issue https://github.com/directus/api/issues/1497 contain this, it also have another bug.

The api log is below:
```
api.fengsi.io_1  | [2019-11-29 10:22:33] api[test].ERROR: Directus\Database\Exception\InvalidQueryException: Failed generating the SQL query. in /var/www/src/core/Directus/Database/TableGateway/BaseTableGateway.php:755
api.fengsi.io_1  | Stack trace:
api.fengsi.io_1  | #0 /var/www/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(209): Directus\Database\TableGateway\BaseTableGateway->executeSelect
api.fengsi.io_1  | #1 /var/www/src/core/Directus/Database/TableGateway/DirectusUserSessionsTableGateway.php(68): Zend\Db\TableGateway\AbstractTableGateway->selectWith
api.fengsi.io_1  | #2 /var/www/src/core/Directus/Services/UserSessionService.php(75): Directus\Database\TableGateway\DirectusUserSessionsTableGateway->fetchSession
api.fengsi.io_1  | #3 /var/www/src/endpoints/Auth.php(125): Directus\Services\UserSessionService->find
api.fengsi.io_1  | #4 /var/www/src/endpoints/Auth.php(73): Directus\Api\Routes\Auth->storeCookieSession
api.fengsi.io_1  | #5 [internal function]: Directus\Api\Routes\Auth->authenticate
api.fengsi.io_1  | #6 /var/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
api.fengsi.io_1  | #7 /var/www/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
api.fengsi.io_1  | #8 /var/www/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->__invoke
api.fengsi.io_1  | #9 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
api.fengsi.io_1  | #10 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
api.fengsi.io_1  | #11 [internal function]: Slim\DeferredCallable->__invoke
api.fengsi.io_1  | #12 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
api.fengsi.io_1  | #13 /var/www/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
api.fengsi.io_1  | #14 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
api.fengsi.io_1  | #15 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
api.fengsi.io_1  | #16 [internal function]: Slim\DeferredCallable->__invoke
api.fengsi.io_1  | #17 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
api.fengsi.io_1  | #18 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
api.fengsi.io_1  | #19 /var/www/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
api.fengsi.io_1  | #20 /var/www/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
api.fengsi.io_1  | #21 /var/www/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke        
api.fengsi.io_1  | #22 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
api.fengsi.io_1  | #23 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
api.fengsi.io_1  | #24 [internal function]: Slim\DeferredCallable->__invoke
api.fengsi.io_1  | #25 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
api.fengsi.io_1  | #26 /var/www/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
api.fengsi.io_1  | #27 /var/www/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
api.fengsi.io_1  | #28 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
api.fengsi.io_1  | #29 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
api.fengsi.io_1  | #30 [internal function]: Slim\DeferredCallable->__invoke
api.fengsi.io_1  | #31 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
api.fengsi.io_1  | #32 /var/www/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
api.fengsi.io_1  | #33 [internal function]: RKA\Middleware\IpAddress->__invoke
api.fengsi.io_1  | #34 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
api.fengsi.io_1  | #35 [internal function]: Slim\DeferredCallable->__invoke
api.fengsi.io_1  | #36 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
api.fengsi.io_1  | #37 /var/www/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
api.fengsi.io_1  | #38 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
api.fengsi.io_1  | #39 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
api.fengsi.io_1  | #40 [internal function]: Slim\DeferredCallable->__invoke
api.fengsi.io_1  | #41 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
api.fengsi.io_1  | #42 /var/www/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}      
api.fengsi.io_1  | #43 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
api.fengsi.io_1  | #44 /var/www/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
api.fengsi.io_1  | #45 [internal function]: Slim\DeferredCallable->__invoke
api.fengsi.io_1  | #46 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
api.fengsi.io_1  | #47 /var/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
api.fengsi.io_1  | #48 /var/www/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
api.fengsi.io_1  | #49 /var/www/vendor/slim/slim/Slim/App.php(297): Slim\App->process
api.fengsi.io_1  | #50 /var/www/src/core/Directus/Application/Application.php(161): Slim\App->run
api.fengsi.io_1  | #51 /var/www/public/index.php(5): Directus\Application\Application->run [] []
```

**Comment by rijkvanzanten** [comment] 2019-11-29 16:54
Duplicate of https://github.com/directus/api/issues/1473

**Closed by rijkvanzanten** 2019-11-29 16:54 UTC
Labels: duplicate
