### ISSUE TITLE
Hooks documentation

### ISSUE THREAD

**Issue by PurpleEdge2214** [directus/app#1024] opened 2018-10-22 03:03 UTC
## Describe the Bug
Is this documentation correct...

https://github.com/directus/docs-v7/blob/master/extensions/hooks.md#create-an-action-hook

...in my api.php it looks like this...

```
'hooks' => [
        'actions' => [],
        'filters' => [],
    ],
```
i.e. actions and filters have separate values.

For "filters" The documentation here...

https://docs.directus.io/api/admin-guide/configure.html#config-options

..appears to be wrong, maybe you could have a link to the correct docs...

https://github.com/directus/docs-v7/blob/master/extensions/hooks.md#create-a-filter-hook

**Comment by benhaynes** [comment] 2018-10-25 23:31
Duplicate of https://github.com/directus/docs-v7/issues/31

**Closed by benhaynes** 2018-10-25 23:31 UTC
Labels: question
