### ISSUE TITLE
Input field type of Dropdown / Options / Choices

### ISSUE THREAD

**Issue by morrenke** [directus/app#2081] opened 2019-09-19 08:24 UTC
Is there a way to change input field type of Choices when I should set the options for a dropdown interface? I would like to add json instead of typing manually. Please check the pictures below:
![dropdown_json](https://user-images.githubusercontent.com/23039613/65226686-97b3c980-dac7-11e9-83b8-9590745278f7.png)
![dropdown_manual](https://user-images.githubusercontent.com/23039613/65226698-9bdfe700-dac7-11e9-815e-2a1fcf8e29fc.png)

**Comment by bjgajjar** [comment] 2019-09-27 11:54
Duplicate of https://github.com/directus/app/issues/2083

**Closed by bjgajjar** 2019-09-27 11:54 UTC
