### ISSUE TITLE
Divider Interface label

### ISSUE THREAD

**Issue by dev7ch** [directus/app#1688] opened 2019-05-28 10:27 UTC
If a divider is added as an interface the "required" toggler is disabled, but it`s not possible to hide the label and the optional, e.g. "Divider -- Optional"

I think it would be helpfull to add a toggler for display label or just remove it completely if title is entered?

![image](https://user-images.githubusercontent.com/15183757/58471381-05686e00-8144-11e9-9d83-920d66dd3ddc.png)

**Comment by rijkvanzanten** [comment] 2019-05-28 12:30
Duplicate of #1683

**Closed by rijkvanzanten** 2019-05-28 12:30 UTC
Labels: duplicate
