### ISSUE TITLE
Nested O2M not working in modals

### ISSUE THREAD

**Issue by Kinzi** [directus/app#1267] opened 2019-01-22 11:35 UTC
# Bug Report

When setting up nested O2M relationships the app crashes when trying to create or select the 2nd level relation. 

It's reproducable in the demo app 

## Steps to Reproduce

Movies -> O2M -> Theatres.id -> O2M -> Ticket_Sales.id

1. Set up nested O2M in demo app like above
2. Click on Movies -> Item
3. Click on Theatres -> Add new
4. In Theatres Modal click on Ticket_sales -> Add new 

## Expected Behavior

A second modal opens with the nested element

## Actual Behavior

App crashes

## Other Context & Screenshots
![bildschirmfoto 2019-01-22 um 13 32 37](https://user-images.githubusercontent.com/6689405/51533121-9fdd3b80-1e4a-11e9-871b-f33966cf5c13.png)

## Technical Details

- Demo Server

**Comment by rijkvanzanten** [comment] 2019-01-22 15:08
This is a duplicate of https://github.com/directus/app/issues/1083

**Closed by rijkvanzanten** 2019-01-22 15:08 UTC
Labels: duplicate
