### ISSUE TITLE
Internal server error when selecting file

### ISSUE THREAD

**Issue by ambu50** [directus/app#1779] opened 2019-06-21 14:30 UTC
After upgrading from 190521A to 190607A, the File interface started to give internal server error every time I upload a new file or select existing file. When I downgraded to 190521A the issue is gone. Below are the error logs from my server.

`[2019-06-21 15:50:21] api[_].ERROR: TypeError: Argument 3 passed to Directus\Database\TableGateway\RelationalTableGateway::recordActivity() must be of the type array, null given, called in hidden_details/g/src/core/Directus/Database/TableGateway/RelationalTableGateway.php on line 551 in /home1/fivetec2/public_html/tammny-admin/src/core/Directus/Database/TableGateway/RelationalTableGateway.php:2300
Stack trace:
#0 hidden_details/g/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(551): Directus\Database\TableGateway\RelationalTableGateway->recordActivity
#1 hidden_details/g/src/core/Directus/Services/ItemsService.php(161): Directus\Database\TableGateway\RelationalTableGateway->updateRecord
#2 hidden_details/g/src/endpoints/Items.php(121): Directus\Services\ItemsService->update
#3 [internal function]: Directus\Api\Routes\Items->update
#4 hidden_details/g/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func
#5 hidden_details/g/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke
#6 hidden_details/g/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#7 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#8 hidden_details/g/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#9 [internal function]: Slim\DeferredCallable->__invoke
#10 hidden_details/g/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#11 hidden_details/g/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(81): Slim\Route->Slim\{closure}
#12 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#13 hidden_details/g/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#14 [internal function]: Slim\DeferredCallable->__invoke
#15 hidden_details/g/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#16 hidden_details/g/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#17 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#18 hidden_details/g/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#19 [internal function]: Slim\DeferredCallable->__invoke
#20 hidden_details/g/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#21 hidden_details/g/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#22 hidden_details/g/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#23 hidden_details/g/vendor/slim/slim/Slim/App.php(515): Slim\Route->run
#24 hidden_details/g/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#25 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#26 hidden_details/g/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#27 [internal function]: Slim\DeferredCallable->__invoke
#28 hidden_details/g/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#29 hidden_details/g/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#30 hidden_details/g/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#31 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#32 hidden_details/g/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#33 [internal function]: Slim\DeferredCallable->__invoke
#34 hidden_details/g/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#35 hidden_details/g/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#36 [internal function]: RKA\Middleware\IpAddress->__invoke
#37 hidden_details/g/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#38 [internal function]: Slim\DeferredCallable->__invoke
#39 hidden_details/g/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#40 hidden_details/g/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#41 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#42 hidden_details/g/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#43 [internal function]: Slim\DeferredCallable->__invoke
#44 hidden_details/g/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#45 hidden_details/g/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#46 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#47 hidden_details/g/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#48 [internal function]: Slim\DeferredCallable->__invoke
#49 hidden_details/g/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#50 hidden_details/g/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#51 hidden_details/g/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#52 hidden_details/g/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#53 hidden_details/g/src/core/Directus/Application/Application.php(161): Slim\App->run
#54 hidden_details/g/public/index.php(5): Directus\Application\Application->run [] []`

**Comment by rijkvanzanten** [comment] 2019-06-21 14:41
Duplicate of https://github.com/directus/app/issues/1767

**Closed by rijkvanzanten** 2019-06-21 14:41 UTC
Labels: duplicate
