### ISSUE TITLE
Fileupload size 0B maxUploadSize is null

### ISSUE THREAD

**Issue by Felix-IR** [directus/app#1228] opened 2019-01-04 11:06 UTC
# Bug Report

## Steps to Reproduce

1. Trying to upload any file following upload field is shown: 
![image](https://user-images.githubusercontent.com/17576933/50684669-b4ca6a00-1016-11e9-8c5c-813946c6cc95.png)
2. The Max. Size is set to 0B
3. Inspect the store state

## Expected Behavior
There should be the correct upload size set. This should be done via `api.serverInfo()` from  `src/store/modules/server-info/actions.js`

## Actual Behavior
The store state has a set value of maxUploadSize of null
![image](https://user-images.githubusercontent.com/17576933/50685225-a5e4b700-1018-11e9-9b8e-038bc9f964e5.png)

[Added further research]
 in `src/store/modules/server-info/actions.js` the `api.serverInfo().catch(console.log))` gives following result: 

```
{code: -1, message: "Network Error", error: Error: Network Error
    at t.exports (webpack-internal:///./node_modules/@directus/sdk-js/dist/dire…}
code: -1
error: Error: Network Error at t.exports (webpack-internal:///./node_modules/@directus/sdk-js/dist/directus-sdk.umd.min.js:1:6101) at XMLHttpRequest.d.onerror (webpack-internal:///./node_modules/@directus/sdk-js/dist/directus-sdk.umd.min.js:1:5158)
config: {adapter: ƒ, transformRequest: {…}, transformResponse: {…}, timeout: 600000, xsrfCookieName: "XSRF-TOKEN", …}
request: XMLHttpRequest {onreadystatechange: ƒ, readyState: 4, timeout: 600000, withCredentials: false, upload: XMLHttpRequestUpload, …}
response: undefined
message: "Network Error"
stack: "Error: Network Error↵    at t.exports (webpack-internal:///./node_modules/@directus/sdk-js/dist/directus-sdk.umd.min.js:1:6101)↵    at XMLHttpRequest.d.onerror (webpack-internal:///./node_modules/@directus/sdk-js/dist/directus-sdk.umd.min.js:1:5158)"
__proto__: Object
message: "Network Error"
__proto__: Object 
```

## Technical Details

- Device: Desktop
- OS: MacOS 10.12
- Browser: Chrome 71.0.3578.98 
- Directus App: v7.0.12 commit 933acc8d9b82ed2c10eaf94291390be04214e437
- Directus API: 2.0.13 using docker image
- Install Method: docker for api and app checked out locally for debugging

**Comment by rijkvanzanten** [comment] 2019-01-04 14:43
I think this is a duplicate of https://github.com/directus/docker/issues/14.

It's caused by an issue the docker configuration.

**Closed by rijkvanzanten** 2019-01-04 14:43 UTC
Labels: bug

**Comment by Felix-IR** [comment] 2019-01-04 14:51
Yes it's a duplicated bug. 
Thx for mentioning it and closing!
