### ISSUE TITLE
Translation Tool

### ISSUE THREAD

**Issue by miloshavlicek** [directus/app#1681] opened 2019-05-26 12:57 UTC
# Feature Request

## What problem does this feature solve?
App UI translation process is a bit complicated for new contributors at this time (I mean editing app/src/lang/locales/xxx.js in this repository and comparing to en-US.js). It could be good to use some translation tool to automate and speed up this process for better translation process open also for non-technical users, discussing and reviewing translations.

## How do you think this should be implemented?
I can recommend great tool Weblate: https://weblate.org which can be also connected to Google Translation API.

## Would you be willing to work on this?
Yes, I can contribute to resolve this issue.

**Comment by rijkvanzanten** [comment] 2019-05-28 14:43
Duplicate of https://github.com/directus/app/issues/793

We're looking at integrating Crowdin. It looks very similar in terms of functionality of weblate

**Closed by rijkvanzanten** 2019-05-28 14:43 UTC
Labels: duplicate
