### ISSUE TITLE
Cannot select multiple items in collection table view

### ISSUE THREAD

**Issue by srjrol** [directus/app#1944] opened 2019-08-09 14:13 UTC
Selecting multiple items with the checkboxes is no longer working.  So, the ability to edit multiple items is not available.  The select all box doesn't work either.

Windows 10
Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Firefox Quantum 68.0.1 (64-bit)
Using the latest combined release Spouting Whale — (190807A)

**Comment by rijkvanzanten** [comment] 2019-08-09 15:22
Duplicate of https://github.com/directus/app/issues/1935

**Closed by rijkvanzanten** 2019-08-09 15:22 UTC
Labels: duplicate
