### ISSUE TITLE
Add tree view

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1847] opened 2019-07-15 05:49 UTC
# Feature Request
I created categories for my collection
There are many subcategories under the category.
Parent Category Mixed with SubCategory
It looks very messy.

![image](https://user-images.githubusercontent.com/8030134/61197302-b59b3180-a706-11e9-830d-81778ea514f3.png)

If you can use a tree display, it becomes clear.

![image](https://user-images.githubusercontent.com/8030134/61197308-bf249980-a706-11e9-871e-e2c179a52e03.png)

## What problem does this feature solve?
If use many to one, the experience will be great.

## How do you think this should be implemented?

![image](https://user-images.githubusercontent.com/8030134/61197390-30644c80-a707-11e9-8375-584b45249177.png)

There may be a lot of problems here.
I'd like to hear your suggestions.

**Comment by rijkvanzanten** [comment] 2019-07-15 14:09
Duplicate of https://github.com/directus/app/issues/1781

**Closed by rijkvanzanten** 2019-07-15 14:09 UTC
Labels: duplicate
