### ISSUE TITLE
Adjusting collection view options results in API error

### ISSUE THREAD

**Issue by justrealmilk** [directus/app#1888] opened 2019-07-29 07:03 UTC
_App version 7.7.0 - both cloned from master_

Upon attempting to adjust column view options, an error occurs and the view options themselves aren't saved to the database.

_Peaking at request with DevTools_

Payload sent: `{"view_query":{"tabular":{"fields":"id,cola,colb"}}}`

API response: `{"error":{"code":4,"message":"view_options: This value should be of type json."}}`

My suspicion is that it's expecting view_options not view_query?

**Comment by rijkvanzanten** [comment] 2019-07-29 13:36
Duplicate of https://github.com/directus/api/issues/1136 which was closed in https://github.com/directus/api/pull/1138

**Closed by rijkvanzanten** 2019-07-29 13:36 UTC
Labels: bug
