### ISSUE TITLE
Radio button interface problem in both 8.1 & 8.2

### ISSUE THREAD

**Issue by paolodedomini** [directus/app#2325] opened 2019-12-11 19:01 UTC
When i try to use a radio button in the console i get:
`vue.runtime.esm.js:1888 TypeError: Cannot read property 'match' of null
    at i (get-fields-from-template.js:12)
    at c.showPlaceholder (row.vue:92)
    at an.get (vue.runtime.esm.js:4473)
    at an.evaluate (vue.runtime.esm.js:4578)
    at c.showPlaceholder (vue.runtime.esm.js:4830)
    at c.u (row.vue?5192:4)
    at c.e._render (vue.runtime.esm.js:3542)
    at c.n (vue.runtime.esm.js:4060)
    at an.get (vue.runtime.esm.js:4473)
    at new an (vue.runtime.esm.js:4462)`
I just can't add options to the field but i can save it.
if i try to add an element in that collection i acctually can see the radiobtn but the interface goes crazy:
[screenshot](https://drive.google.com/open?id=1J6zB0jqoKS-qlrfD585HbpJQFoYrXJEb)
All the options you see, are gettin out from nowere as i was unable to insert any option in the first place!
Thanx

**Comment by rijkvanzanten** [comment] 2019-12-11 19:07
Duplicate of https://github.com/directus/app/issues/2306

**Closed by rijkvanzanten** 2019-12-11 19:07 UTC
Labels: duplicate
