### ISSUE TITLE
m2m issue on display

### ISSUE THREAD

**Issue by eudora-fabia** [directus/app#2165] opened 2019-10-26 16:45 UTC
Using the Directus Demo, I created `artworks` m2m with `venues`.

[Here is the recording of the issue](https://drive.google.com/file/d/17LY5OsajVyNmfa__3uG9H2WV7HK1uNd8/view?usp=sharing)

**Comment by urvashithakar** [comment] 2019-11-06 05:56
Hello @eudora-fabia ,
It seems like it is a duplicate of  #2139

**Comment by benhaynes** [comment] 2019-11-06 13:50
I'll close this as a duplicate — @eudora-fabia, let us know if this is a separate issue.

**Closed by benhaynes** 2019-11-06 13:50 UTC
Labels: bug, needs more info
