### ISSUE TITLE
File and Files interface doesn't react to "+ NEW FIILE" button when they are in a relation 

### ISSUE THREAD

**Issue by deniswoeffray** [directus/app#1187] opened 2018-12-10 09:37 UTC
# Bug Report
File and Files interface doesn't react to "+ NEW FILE" button when they are in a relation 

## Steps to Reproduce

1. Add a relation child OneToMany Collection to a parent Collection
2. Add a relation File or Files in the child Collection
3. When you want to add a child from the parent in the editor interface you can't add a file ou many files from the modal

## Expected Behavior

Be able to add a new file or many new files of a OneToMany relation child.

## Actual Behavior

When the "+ NEW FILE" button is clicked in the modal, the loader appear and disappear but nothing else.

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/11177884/49723640-936c9d00-fc67-11e8-8270-2fb65f5ad8fa.png)

## Technical Details

- Device: [Desktop]
- OS: [Windows 10.1803]
- Browser: [Chrome 68.0.3440.106]
- Directus App: [7.0.11]
- Install Method: [cloned `master` branch]

**Comment by rijkvanzanten** [comment] 2018-12-10 12:10
This is caused by / a duplicate of https://github.com/directus/app/issues/1083

**Closed by rijkvanzanten** 2018-12-10 12:10 UTC
