### ISSUE TITLE
List, float numbers and custom fields for users

### ISSUE THREAD

**Issue by rnwzd** [directus/app#2328] opened 2019-12-12 07:55 UTC
Hi,

I am new to directus and wondered if it is possible to have a list relationship. Like One-to-Many-with-order (or even better One-to-Any).
I am making something like an online educational website (like DuoLingo) and I need some way to implement courses (i.e. list of articles and/or videos).
I also need to store user experience, so I am using a collection (Xp) which has a relation to user and to some other type (i.e. article, video). It would be useful to have a custom field in user type (like One-to-many) to see which are his experiences.
It would be also useful to see all the articles of an author for example.
Otherwise now I would have to create a dummy collection "user-related" to store all user relationship with other content.

PS I also noticed the lack of float numbers, which could be useful for many reasons

**Comment by rijkvanzanten** [comment] 2019-12-12 14:27
The one to many interface supports manual sorting (by adding a sort field on the related collection and configuring the o2m to use that). We don't have "multi-collection" relationships yet (where 1 interface can have a list of items from _multiple_ related collections). Keep an eye on https://github.com/directus/app/issues/712 for that one

**Comment by rijkvanzanten** [comment] 2019-12-12 14:31
As for Floats, the numeric interface supports floats 🙂 

![image](https://user-images.githubusercontent.com/9141017/70720624-22205980-1cc2-11ea-825a-f4e514a4e129.png)

**Comment by rijkvanzanten** [comment] 2019-12-12 14:31
I'll close this as a duplicate of #712

**Closed by rijkvanzanten** 2019-12-12 14:31 UTC
