### ISSUE TITLE
Some mistakes, I don't know how to solve them.

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1576] opened 2019-05-01 20:43 UTC
# Bug Report

## 1、Relatiornal field error
01、Create a Collection named `categories`.
02、Add field `name`, `slug`, type text filed
03、Then enter categories to create categories `A`, `B`
04、Create a Collection named `Blog`.
05、Add field `title`, `slug`, `content`
06、Add another relational field, One to many,
07、Name it `categories`.
08、Then go to Blog and add new content
09、Selecting a Category B by Relational Field

#### Then Category `A` in Collection automatically becomes Category `B`!

>Has been submitted to you

## 2、Cannot use filters for elatiornal field

``` javascript
client.getItems("blog",{
    filter: {
        categories: {
            name: {
                like: 'B'
            }
        },
    }
}),
```

Through the above category filtering, the database will report errors and can not return the corresponding data normally.

## 3、Cannot use files

01、Create a Collection named `Blog`.
02、Add field `title`, `slug`, `content`
03、Add field `files`

It can't be added. The chrome console prompts errors

![image](https://user-images.githubusercontent.com/8030134/57041340-8ee76600-6c94-11e9-8a86-b375e6443f4f.png)

I tried to reinstall the latest version, and now I can create it, but when I went into the blog to add content, it didn't work properly.

![image](https://user-images.githubusercontent.com/8030134/57041364-99096480-6c94-11e9-91d8-22f5fe3c796c.png)

## 4、Display exception

Displayed as empty after Selected

![image](https://user-images.githubusercontent.com/8030134/57041277-6e1f1080-6c94-11e9-81f6-aa643db79f85.png)

#### 1、When I query a collection

``` javascript
client.getItems("movies",{
    offset: 0,
    limit: 10
}),
```
respond data

``` json
data: [xxxxxx]
meta: {
  result_count: 10, 
  total_count: 185
}
```

I can get the total number of entries by "total_count"
Paging with Paging Plug-ins
For example:

1 2 3 4 5 6 total:185

When I click 3, offset passes: 3 * 10 - 10

``` javascript
client.getItems("movies",{
    offset: 0,
    limit: 3 * 10 - 10
}),
```
No problem here.

#### 2、But when I use filter parameters for filtering

``` javascript
client.getItems("movies",{
    offset: 0,
    limit: 10,
    filter: {
        title: {
            contains: 'hello'
        }
    }
}),
```
respond data
``` json
data: [xxxxxx]
meta: {
  result_count: 10, 
  total_count: 185
}
```

`total_count` returns the total number of `movies`, not the filtered total number of `title contains hello`. How do I get the total number of `title contains "hello"` after filtering through filter?

How to get `total_filter`

## 6、This problem often arises after updating the latest version

 need to click on the link on the page to log in again, the refresh is invalid.

![image](https://user-images.githubusercontent.com/8030134/57041223-47f97080-6c94-11e9-83ec-0ead1c7a93fe.png)

![image](https://user-images.githubusercontent.com/8030134/57050555-c9aac780-6caf-11e9-9db2-479a68e629a4.png)

## Technical Details

- Device: [Desktop]
- OS: [macOS 10.13 High Sierra, CentOS Linux 7.6.1810]
- Browser: [ Chrome 73.0.3683.103 x64]
- Directus App: [ 7.1.0]/[ 7.3.0]
- Directus API: [2.0.20]/[2.0.22]
- Install Method: [cloned `master`  branch]
- Web Server: [Nginx 1.8.1]
- PHP Version: [7.2.13]
- Database: [MySQL 5.7.2]

**Comment by cdwmhcc** [comment] 2019-05-02 01:13
提个建议，这里用这种方式进行操作更方便快捷

![image](https://user-images.githubusercontent.com/8030134/57052535-75591500-6cba-11e9-82ee-675a9b955e9a.png)

![image](https://user-images.githubusercontent.com/8030134/57052543-9457a700-6cba-11e9-9497-8dc36d32dba0.png)

**Comment by cdwmhcc** [comment] 2019-05-02 01:23
规则设置，目前根据我的了解，我只能针对下图中的模块设置规则。

![image](https://user-images.githubusercontent.com/8030134/57052618-19db5700-6cbb-11e9-8621-2ff4ff42896e.png)

如果我想针对任意的字段设置规则，就做不到了，建议每个字段都可以设置规则，应用到的地方也比较多，例如访客不能查看内容、下载地址，限定某个角色组才可以查看内容和下载地址。

![image](https://user-images.githubusercontent.com/8030134/57052759-fbc22680-6cbb-11e9-9794-d81079f3d625.png)

**Comment by shealavington** [comment] 2019-05-03 08:35
5: This works as it should. However your suggestion is a feature request to remove the limit from the count, so that you can paginate.

7: Has been fixed and should be released in today's release.

I'm not sure about the status of the others.

**Comment by cdwmhcc** [comment] 2019-05-03 16:38
> 5: This works as it should. However, your suggestion is a feature request to remove the limit from the count, so that you can paginate.
> 
> 7: Has been fixed and should be released in today's release.
> 
> I'm not sure about the status of the others.

Am I annoying?
No more people reply to my question
😭😭😭

**Comment by benhaynes** [comment] 2019-05-03 16:56
Technically each of these questions should have been added as individual issues — so it is a bit annoying for us to respond/debug. ;)

But you should also not expect answers so quickly. This is an open-source project servicing many users and our small team needs to take time to review and respond to all of them equally (based on the priority of the bug).

I'd recommend opening individual tickets for these problems if you want to get proper responses. Also, GitHub isn't for debugging configuration issues — it's for bugs and feature requests. If you need help with your specific setup then I'd try StackOverflow or the Slack community: https://directus.chat (I know you're already on there).

**Comment by henrikwirth** [comment] 2019-05-05 09:51
4: I openend an issue here: #1581  and submitted a pull request here: #1583

**Comment by shealavington** [comment] 2019-05-05 11:34
1. Should be a many-to-many.

2. This may be fixed, by fixing 1.

3. @cdwmhcc and I worked out that this is an issue Caused by MacOS 10.13 🤷‍♂ 

4. PR created by Henrikwirth ❤️ 

5. > This works as it should. However, your suggestion is a feature request to remove the limit from the count, so that you can paginate.

6. Maybe because you need to upgrade the database after updating?

7. > Has been fixed in the latest release. 

As for the extra comments, they look like feature suggestions. They should go into individual feature requests. 😃 As Ben mentioned, this is such a big list, it's difficult to respond to all of these at once.

**Comment by cdwmhcc** [comment] 2019-05-05 11:44
> 1. Should be a many-to-many.
> 2. This may be fixed, by fixing 1.
> 3. @cdwmhcc and I worked out that this is an issue Caused by MacOS 10.13 🤷‍♂
> 4. PR created by Henrikwirth ❤️
> 5. > This works as it should. However, your suggestion is a feature request to remove the limit from the count, so that you can paginate.
> 6. Maybe because you need to upgrade the database after updating?
> 7. > Has been fixed in the latest release.
> 
> As for the extra comments, they look like feature suggestions. They should go into individual feature requests. 😃 As Ben mentioned, this is such a big list, it's difficult to respond to all of these at once.

I understand. I finally know how to submit a question on github. Thank you.

**Comment by shealavington** [comment] 2019-05-06 17:13
From what I can tell, nothing else will come from this issue, therefore I'm closing it.

**Closed by shealavington** 2019-05-06 17:13 UTC

**Comment by cdwmhcc** [comment] 2019-05-06 17:18
> From what I can tell, nothing else will come from this issue, therefore I'm closing it.

I've submitted the question separately, and you can safely close it now.
