### ISSUE TITLE
Many to many selector clicks save button to report error

### ISSUE THREAD

**Issue by cdwmhcc** [directus/app#1875] opened 2019-07-22 19:42 UTC
## Collections:

**soft**:  id | title |  categories (many to many)

![image](https://user-images.githubusercontent.com/8030134/61659829-14f6d400-acfb-11e9-9e7d-9c1b955a1362.png)

**soft_categories**: id | name | parent_category (many to one)

![image](https://user-images.githubusercontent.com/8030134/61659886-3a83dd80-acfb-11e9-9464-79ffa94fb1c4.png)

### https://streamable.com/acef9

![image](https://user-images.githubusercontent.com/8030134/61660169-da416b80-acfb-11e9-825d-4a8c0270a746.png)

## Technical Details

- Device: [eg: Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.3.0]
- APP Version: [7.7.0]
- Install Method: [cloned `master` branch]

**Comment by rijkvanzanten** [comment] 2019-07-23 21:10
what layout is that using? I don't recognize that select tree list. Could you verify if the issue also happens without your custom layout potentially interfering?

**Comment by cdwmhcc** [comment] 2019-07-23 22:49
> what layout is that using? I don't recognize that select tree list. Could you verify if the issue also happens without your custom layout potentially interfering?

I tried my best to translate it into English.Didn't you understand my description? 

It has nothing to do with trees.

![image](https://user-images.githubusercontent.com/8030134/61752637-fff37100-adde-11e9-8a3e-62189856aa1f.png)

**Comment by theharshin** [comment] 2019-09-11 06:33
I think the cause of error was a `null` selection of items. The interface did not have a check for any item was selected or not. I've added that check in recent PR:
https://github.com/directus/app/pull/2020/files#diff-086ba11acfa2f4e5e83ad9d59eae0fc3R403

@cdwmhcc You can try in the latest build and let us know if the issue is still there.

**Comment by cdwmhcc** [comment] 2019-09-11 15:17
> I think the cause of error was a `null` selection of items. The interface did not have a check for any item was selected or not. I've added that check in recent PR:
> https://github.com/directus/app/pull/2020/files#diff-086ba11acfa2f4e5e83ad9d59eae0fc3R403
> 
> @cdwmhcc You can try in the latest build and let us know if the issue is still there.

OK, I haven't updated two major versions. Can I update them directly?

**Comment by bjgajjar** [comment] 2019-10-12 11:22
> OK, I haven't updated two major versions. Can I update them directly?

Yes! Please upgrade your version and let us know if the issue still persists.

**Comment by rijkvanzanten** [comment] 2019-11-20 18:08
This was fixed in #2020

**Closed by rijkvanzanten** 2019-11-20 18:08 UTC
Labels: needs more info
