### ISSUE TITLE
Connecting to DigitalOcean managed Mysql DB

### ISSUE THREAD

**Issue by botzill** [directus/app#2967] opened 2020-08-31 10:40 UTC
Hi.

I'm trying to install the latest version of directus and connect to DO managed mysql by I get `Failed to connect to the database` when I run the command:

```
./bin/directus install:database
```

Do I need to specifcy the certificates when I connect to it or sslmode and if yes is there any ENV for it?

Thx.

**Comment by rijkvanzanten** [comment] 2020-08-31 13:55
Duplicate of https://github.com/directus/directus/discussions/2829#discussioncomment-59374

**Closed by rijkvanzanten** 2020-08-31 13:55 UTC
