### ISSUE TITLE
Extension problems in Directus demo

### ISSUE THREAD

**Issue by elmonty** [directus/app#1528] opened 2019-04-22 12:58 UTC
# Bug Report

## Steps to Reproduce

1. Log into Directus demo
2. Click on Showtimes
3. Select a record to edit

## Expected Behavior

Expected behavior is to see no error messages. Link records should display the linked information instead of [object Object].

## Actual Behavior

![directus-errors](https://user-images.githubusercontent.com/345789/56501402-a8dab900-64dc-11e9-9662-d2cc572e2b43.png)

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Browser: [eg: Chrome 68.0.3440.106]
- Directus App: [eg: 7.0.0]
- Directus API: [eg: 2.0.0]
- Install Method: [eg: cloned `master` branch of `directus/directus`]

**Comment by rijkvanzanten** [comment] 2019-04-22 13:23
Can you confirm this is happening on Chrome?

**Comment by rijkvanzanten** [comment] 2019-04-22 13:24
It seems like Chrome is requesting all the chunks for all the interfaces at once, triggering rate limiters on servers because of the high number of small files. In normal operation, like I'm seeing Safari, only the chunks that are needed to render the current view should be loaded..

**Comment by elmonty** [comment] 2019-04-22 13:34
Yes, this is in Chrome.

**Comment by shealavington** [comment] 2019-04-22 13:47
I can confirm I've been getting this too.

**Comment by rijkvanzanten** [comment] 2019-04-22 13:59
The build chain was adding prefetch links into the HTML to prefetch all the different chunks. This means that there are about 100 files being loaded in at once, causing the server to apply the rate limit, which in turn prevents the application from rendering the application completely. These chunks don't need to be prefetched at all, seeing that most of them might not even be used. Commit https://github.com/directus/app/commit/c5f0dcf37b49d1a64d5898bcc18b7b23c72644ba disables this. I'll release a hot fix at the end of the day today, as this might cause issues on most browsers: https://caniuse.com/#feat=link-rel-prefetch

**Comment by rijkvanzanten** [comment] 2019-04-22 13:59
Closed in https://github.com/directus/app/commit/c5f0dcf37b49d1a64d5898bcc18b7b23c72644ba

**Closed by rijkvanzanten** 2019-04-22 13:59 UTC
Labels: bug

**Comment by benhaynes** [comment] 2019-04-22 17:16
🔥 Hotfix inbound!🔥
_Patch will be pushed EOD today._
