### ISSUE TITLE
v8.3.1 Files Interface - "This item is not available"

### ISSUE THREAD

**Issue by gianniskarmas** [directus/app#2405] opened 2020-01-11 05:31 UTC
Old v7 project upgraded sequentially to 8.3.1.
This happens in all collections' file fields and no errors in console.
Does not happen in a newly created collection though so maybe a migration bug.
Would really appreciate any hints of how to fix.
![directus file interface problem](https://user-images.githubusercontent.com/3495993/72199354-c23ce000-3432-11ea-850d-9bc0bf58895a.gif)

**Comment by rijkvanzanten** [comment] 2020-01-13 17:11
That warning shows up whenever the file interface can't read the referenced file. Something must be going wrong between the translations interface and nested file interface

**Comment by gianniskarmas** [comment] 2020-01-14 06:19
This is happening to translated as also to direct collection fields after migration.
Creating a new collection and field works.
Maybe the relation to the renamed 'filename_disc' or returned api response that now includes the hash link has not been migrated to the interface? What do you think.
Which file is responsible so I can have a look? Can I just delete the migrations in directus folder and database and refresh to run the migrations again?

**Comment by rijkvanzanten** [comment] 2020-01-14 14:39
I think the problem might be that the translations interface doesn't fetch the correct level of depth for the nested file interface to be able to render out the file 🤔

**Comment by gianniskarmas** [comment] 2020-01-14 14:48
FYI my languages collection looks like this and used to work before the upgrade.
![image](https://user-images.githubusercontent.com/3495993/72354027-ef142000-36dc-11ea-80e7-da994f514b19.png)

**Comment by jesseint** [comment] 2020-01-15 09:17
I faced the same problem yesterday. Directus still 8.3.0 (was planning to upgrade it today to 8.3.1) in my dev environment which I installed using docker. 

My problem though a bit different.. I created a new collection (so it is not migration)and the file preview (it is an image) in translation show "This item is not available". Other collections without translation show image preview just fine.

But however, I also have directus 8.3.0 in my local and the file preview in my local working perfectly fine even in translation. I also check the db in my local and it looks fine too.

I re-checked and fix the relationships, clean up the data again and try to re enter new data.. still doesn't work...

**Comment by jesseint** [comment] 2020-01-15 12:47
Apparently the preview was not appear because of the wrong relations I set initially. I missed to set the parent_id to translation collection, instead I set "status" field which was the default because it is on the top. I fixed this immediately when I double checked it but file preview was still said "Item is not available". So, I went to the DB directly and check, I found that the image ID is set there but somehow the preview still error.

So, as you may know that directus_relations field doesn't get deleted when you change the relations, it just put a new entry for the new relation and somehow also affecting the file preview. I deleted manually the db entry for the wrong relations and also the data from the collection where the relations was still wrong. After that, now it is working.

I hope this can help.

**Comment by benhaynes** [comment] 2020-01-15 14:12
Thanks @jesseint! One important takeaway here is to clean up the `directus_relations` when removing those relationships. I believe we have a ticket for that one, but I can't find it right now.

**Comment by gianniskarmas** [comment] 2020-01-26 01:12
This issue can be merged with #2412, and have one less to count ;)

**Comment by benhaynes** [comment] 2020-01-26 20:22
Duplicate of: https://github.com/directus/app/issues/2412

**Closed by benhaynes** 2020-01-26 20:22 UTC
Labels: bug
