### ISSUE TITLE
Bug : Edit an Item that have nested one-to-many Items with translations

### ISSUE THREAD

**Issue by stouch** [directus/app#2684] opened 2020-03-25 08:42 UTC
Version 8.6.2

Steps to reproduce :
![steps_to_reproduce](https://user-images.githubusercontent.com/17531455/77517631-c480d900-6e7c-11ea-8640-91a438084a37.gif)

Problem summary : 
When you have nested items {X} attached to an item A, and when your nested items {X} have translations : 
-> From the edit page of A, if you open the edit modal for one of the item X, you cannot view or edit its translations.

**Comment by stouch** [comment] 2020-03-28 17:15
Sorry for my bad english.. But anyone else have this bug ? Is there a fix planned in a future version ?

**Comment by rijkvanzanten** [comment] 2020-03-29 20:32
Duplicate of https://github.com/directus/app/issues/2589

**Closed by rijkvanzanten** 2020-03-29 20:32 UTC
