### ISSUE TITLE
Translations do not work

### ISSUE THREAD

**Issue by alextomas** [directus/app#1917] opened 2019-08-02 15:19 UTC
I have followed all the steps explained in https://docs.directus.io/guides/relationships.html#translations and it doesn't work for me. Directus saves the translations, but when I try to edit a "Blog" record (for example) the translation information does not appear in the textarea.

**Comment by rijkvanzanten** [comment] 2019-08-02 15:30
Duplicate of https://github.com/directus/app/issues/1849, attempted in https://github.com/directus/app/pull/1879, fixed in https://github.com/directus/app/pull/1914

**Closed by rijkvanzanten** 2019-08-02 15:30 UTC
Labels: duplicate

**Comment by alextomas** [comment] 2019-08-02 15:57
I can't see the fix in this reply :S

**Comment by rijkvanzanten** [comment] 2019-08-02 16:00
What do you mean? The issue was mentioned before in #1849, someone tried fixing it in #1897 but it didn't turn out to be working for everyone, after which @oliverpool fixed it in #1914. That was merged into `develop` an hour ago meaning it'll make it to master in the next release which will most likely be in a week or so
