### ISSUE TITLE
Many 2 Many Select Existing-modal creates list of blank items

### ISSUE THREAD

**Issue by LievenVandeperre** [directus/app#2026] opened 2019-09-05 03:52 UTC
Verion: latest relese

When you have a collection with a many to many relationship and want to show the user the data from the related table instead of the junction table (which is pretty common) The interface to show those items are showed properly, but the modal to select existing items are shown as empty items.

![image](https://user-images.githubusercontent.com/3865219/64310556-cd719200-cfa0-11e9-9e86-a31e9970b0f5.png)

above is perfect. however when i click the 'selelect existing'button this is the result:

![image](https://user-images.githubusercontent.com/3865219/64310586-ef6b1480-cfa0-11e9-8ca7-32920003638f.png)

labelsettings:
![image](https://user-images.githubusercontent.com/3865219/64310634-1c1f2c00-cfa1-11e9-85c0-c372ac088df2.png)

How it should be: both the overview on the main screen and the modal screen should show the proper info

**Comment by itsmerhp** [comment] 2019-09-07 05:47
@LievenVandeperre 
Unable to reproduce the issue, please check below screenshots:

![Edit collection item](https://user-images.githubusercontent.com/49250107/64470455-ab267280-d160-11e9-878b-61cbb37165e7.png)
![Select existing items popup](https://user-images.githubusercontent.com/49250107/64470454-ab267280-d160-11e9-8a3e-70d4fb2166c9.png)

Can you please share your SQL dump in slack private channel, so that we can reproduce the issue?
Please also confirm that you are using the latest APP build.

**Comment by bjgajjar** [comment] 2019-09-10 06:05
Agree with @itsmerhp. This issue is not reproducible in the latest version; I am closing this. Feel free to reopen it.

**Closed by bjgajjar** 2019-09-10 06:05 UTC
Labels: bug

**Comment by andgar2010** [comment] 2020-01-22 00:06
I made it but it comes out white. I tried different parameters in settings, but it's still white.

![msedge_EOvGtsrhsU](https://user-images.githubusercontent.com/19521054/72853851-8d295c80-3c80-11ea-8f00-8fb70b469e44.png)

Interface interface-many-to-many A:
![msedge_VNO8oUdRHk](https://user-images.githubusercontent.com/19521054/72853861-96b2c480-3c80-11ea-9c14-516e5779fb47.png)

Interface interface-many-to-many B:
![msedge_JPXQDNX5E3](https://user-images.githubusercontent.com/19521054/72853877-a500e080-3c80-11ea-8254-6e005ac0b801.png)

Interface interface-many-to-many OPTIONS A:
![msedge_soMDgI986c](https://user-images.githubusercontent.com/19521054/72853927-cd88da80-3c80-11ea-8b2c-d6c8ae895cdb.png)

Interface interface-many-to-many OPTIONS B:
![msedge_UiYTqZNu7G](https://user-images.githubusercontent.com/19521054/72853933-cf529e00-3c80-11ea-864f-7aaf385a8f70.png)
