### ISSUE TITLE
After update the standard fields disappeared and lead to an irreversible error on tables set to Timeline.

### ISSUE THREAD

**Issue by edenprojectde** [directus/app#1939] opened 2019-08-09 04:57 UTC
After upgrading from 7.8.0 i lost the basic fields of my tables(Created On, Created By etc.) at least they are not selectable/visible in the Views options. With that it seems the Timeline view is broken. And after setting a table's View to Timeline, it wont load correctly again if left on Calendar and refreshing afterwards.

To reproduce:
1. Get a table
![image](https://user-images.githubusercontent.com/6115966/62754722-63350280-ba71-11e9-9bf9-438cb6fc11ea.png)
2. Set it to Timeline
3. :
![image](https://user-images.githubusercontent.com/6115966/62754798-a7280780-ba71-11e9-8e0c-4de7754cf6ff.png)

Directus Suite(App) v7.9.0
PHP Zend Engine v3.3.7 with Zend OPcache v7.3.7-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c)
Nginx Server
OS: Ubuntu

**Comment by rijkvanzanten** [comment] 2019-08-09 22:00
I think this issue is caused by the fact that since https://github.com/directus/app/pull/1908 fields that are `hidden_on_browse` are now actually hidden. The app still tries to load them because the saved preferences for this page try to request them from before they were hidden.

@edenprojectde Could you try turning off "hidden on browse" for those fields to see if my thinking is correct?

**Comment by edenprojectde** [comment] 2019-08-09 22:46
> @edenprojectde Could you try turning off "hidden on browse" for those fields to see if my thinking is correct?
Yea the table is working now again after changing them to visible on Browse

**Comment by rijkvanzanten** [comment] 2019-08-12 13:40
Note to self / whomever is taking this on in @directus/app-team:

We should check if all the fields in `viewQuery` exist in the currently viewed collection before requesting them. That ensures that the application doesn't try to read fields that the API will 401.

**Comment by bjgajjar** [comment] 2019-08-12 13:42
@rijkvanzanten 

I already add this condition for `param` in #1955

**Comment by bjgajjar** [comment] 2019-08-19 06:53
> We should check if all the fields in `viewQuery` exist in the currently viewed collection before requesting them.

We have already that condition for all the fields except `sort` and the condition of `sort` is already added in  #1955. 

Thus closing this issue. Feel free to reopen it if still have an issue.

**Closed by bjgajjar** 2019-08-19 06:53 UTC
Labels: bug

**Comment by nashtu3000** [comment] 2019-08-22 19:02
Thanks. The turning off of hidden on browse did the trick for me as well.
