### ISSUE TITLE
Collections display view issue

### ISSUE THREAD

**Issue by andrewksimon** [directus/app#1947] opened 2019-08-09 16:43 UTC
I did a ```git pull origin``` last night on my install to update to 190807A and fix avatar issues (as in GH-1871). While that issue had been fixed, it had created a new one.

**Issue**
Vue errors out in console and fails to display an existing collection. 
Console logs state:
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'field' of undefined
    at a.primaryKeyField (items.vue:376)
    at nr.get (vue.runtime.esm.js:4473)
    at nr.evaluate (vue.runtime.esm.js:4578)
    at a.primaryKeyField (vue.runtime.esm.js:4830)
    at a.viewQuery (items.vue:302)
    at nr.get (vue.runtime.esm.js:4473)
    at nr.evaluate (vue.runtime.esm.js:4578)
    at a.viewQuery (vue.runtime.esm.js:4830)
    at a.rd (items.vue?78f2:1)
    at a.e._render (vue.runtime.esm.js:3542)
```
*Please note that this was working and functional prior to the update.*

Reference image (prior to update):
![image](https://user-images.githubusercontent.com/24998798/62666549-d9424800-b951-11e9-9537-0784cfbe8ecb.png)

What the user sees after the update:
![image](https://user-images.githubusercontent.com/24998798/62794588-757b6480-baa2-11e9-9b82-fe531cc8cd19.png)

What the console displays:
![image](https://user-images.githubusercontent.com/24998798/62794610-862bda80-baa2-11e9-92f9-efa88bfe7e25.png)

**Technical Details:**
- Device: [Laptop]
- Browser: [Chrome, Edge]
- OS: [Windows 10.1803]
- Web Server: [Nginx: 1.10.3]
- PHP Version: [7.3.8]
- API Version: [2.4.0]
- APP Version: [7.9.0]

**Comment by rijkvanzanten** [comment] 2019-08-09 19:15
Hey @andrewksimon! Thanks for contributing 🙂 

I can't seem to reproduce this issue on my end.. Can you share some more information on your exact schema setup? If you could, a DB dump would be super useful. You can send it to me [on Slack](https://directus.chat) too. 

The fix for #1934 / #1944 might've caused this issue, but I'm not sure until I can reproduce it..

**Comment by edenprojectde** [comment] 2019-08-09 21:54
Probably a duplicate of this: https://github.com/directus/app/issues/1939

**Comment by rijkvanzanten** [comment] 2019-08-09 21:56
Ah! You're right. Good catch :)

**Closed** 2019-08-09 21:56 UTC
Labels: duplicate
