### ISSUE TITLE
Cannot escape many to one dialog without changes

### ISSUE THREAD

**Issue by miloshavlicek** [directus/app#1687] opened 2019-05-28 08:57 UTC
**Steps to reproduce:**
1. Go to a detail page of an item with many to one relationship interface (e.g. https://directus.app/#/collections/tickets/2)
2. Click to an Optional o2m interface > dialog will be opened
3. Do not select anything
4. Try to escape without changes

![image](https://user-images.githubusercontent.com/2387790/58465128-56259a00-8137-11e9-99a7-102078cfff27.png)
![image](https://user-images.githubusercontent.com/2387790/58465144-5f166b80-8137-11e9-99d3-fdfa8f48d659.png)

**Solution ideas:**
- Add an ability to click on dialog backdrop to escape without changes
- Add window close icon to the right top corner of the dialog to escape without changes

**Workarounds:**
- Click F5 to reload page

**Comment by rijkvanzanten** [comment] 2019-05-28 12:22
Duplicate of #1375

**Closed by rijkvanzanten** 2019-05-28 12:22 UTC
Labels: duplicate

**Comment by rijkvanzanten** [comment] 2019-05-28 12:23
This will be addressed in https://github.com/directus/app/pull/1677

**Comment by miloshavlicek** [comment] 2019-05-28 14:38
Thank you and sorry, I didn't notice the thread.
